"""Verify the produced archive, retained proof, and exact identity-only delta."""
import collections, hashlib, io, json, re, zipfile
import xml.etree.ElementTree as ET
from pathlib import Path
from audit_identity import ROOT, OUT, save, sha, occurrences

old_path = ROOT/'build/libs/achievetodo-mc26.2+0.1.5.2.jar'
new_path = ROOT/'build/libs/achievetodo-mc26.2+0.1.5.3.jar'
allowed_files = {'LICENSE','README.md','gradle.properties','build.gradle','gradle/BuildConfig.java.txt',
                 'src/main/generated/java/com/diskree/achievetodo/BuildConfig.java'}
inputs = json.loads((OUT/'protected_input_hashes.json').read_text(encoding='utf-8'))
changed = []
for name, before in inputs.items():
    p = ROOT/name
    assert p.exists(), f'Protected file removed: {name}'
    after = sha(p.read_bytes())
    if after != before:
        assert name in allowed_files, f'Unexpected semantic/evidence change: {name}'
        changed.append(dict(path=name,beforeSha256=before,afterSha256=after))
assert sha(old_path.read_bytes()) == '7d6f303aa23ee5c188c315197f4c7e4f20c3256b8ec4d6d78fab9909c523f7ba'

jar_matches, jar_path_matches = [], []
with zipfile.ZipFile(old_path) as old, zipfile.ZipFile(new_path) as new:
    names = new.namelist()
    assert len(names) == len(set(names)), 'Duplicate archive metadata or entries'
    assert set(names) == set(old.namelist()), 'Archive/package structure changed'
    delta = [n for n in names if new.read(n) != old.read(n)]
    assert set(delta) == {'fabric.mod.json','LICENSE_achievetodo','com/diskree/achievetodo/BuildConfig.class'}, delta
    metadata = json.loads(new.read('fabric.mod.json'))
    expected_metadata = json.loads(old.read('fabric.mod.json'))
    expected_metadata.update(version='0.1.5.3',authors=['Glower4ek'],contact={'sources':'https://github.com/Glower4ek/AchieveToDo'})
    assert metadata == expected_metadata, 'Non-identity mod metadata changed'
    assert new.read('com/diskree/achievetodo/BuildConfig.class') == old.read('com/diskree/achievetodo/BuildConfig.class').replace(b'0.1.5.2',b'0.1.5.3'), 'Unexpected generated bytecode change'
    assert metadata['version'] == '0.1.5.3'
    assert metadata['authors'] == ['Glower4ek']
    assert metadata['contact'] == {'sources':'https://github.com/Glower4ek/AchieveToDo'}
    assert 'contributors' not in metadata
    license_text = new.read('LICENSE_achievetodo').decode()
    assert license_text == old.read('LICENSE_achievetodo').decode().replace('Copyright (c) 2024 diskree','Copyright (c) 2026 Glower4ek')
    mixins = json.loads(new.read('achievetodo.mixins.json'))
    assert mixins['package'] == 'com.diskree.achievetodo.injection.mixin'
    for side in ['mixins','client','server']:
        for name in mixins.get(side,[]):
            assert (mixins['package']+'.'+name).replace('.','/')+'.class' in names
    for side in metadata['entrypoints'].values():
        for name in side: assert name.replace('.','/')+'.class' in names
    leakage = [n for n in names if re.search(r'(^|/)(reference|planning|debug|gametest|certification|test)(/|\.)|Test\.class$|GameTest|Pre26Smoke|AuthorIdentity',n,re.I)]
    assert not leakage, leakage
    def scan(z, parent=''):
        for info in z.infolist():
            if info.is_dir(): continue
            name = parent+info.filename
            data = z.read(info)
            for row in occurrences(data,name,True):
                if row['category'] != 'E':
                    assert name == 'LICENSE_bacap-better-ru', row
                    row.update(category='H',decision='KEEP',reason='Third-party BACAP Better RU 2.3 original resource author; not AchieveToDo ownership. CC0 provenance preserved.')
                jar_matches.append(row)
            for m in re.finditer('diskree',name,re.I):
                assert re.search(r'com[/\\.]diskree',name,re.I), name
                jar_path_matches.append(dict(path=name,offset=m.start(),category='E',decision='KEEP',reason='Required unchanged technical namespace entry path.'))
            if zipfile.is_zipfile(io.BytesIO(data)):
                with zipfile.ZipFile(io.BytesIO(data)) as nested: scan(nested,name+'!')
    scan(new)

def junit(folder):
    totals = dict(tests=0,failures=0,errors=0,skipped=0)
    suites = []
    for p in sorted((OUT/folder).glob('TEST-*.xml')):
        node=ET.parse(p).getroot()
        stats={k:int(node.attrib.get(k,0)) for k in totals}
        for k,v in stats.items(): totals[k]+=v
        suites.append(dict(name=node.attrib['name'],**stats,sha256=sha(p.read_bytes())))
    assert totals['tests'] > 0 and not any(totals[k] for k in ['failures','errors','skipped']),totals
    return dict(totals=totals,suites=suites)

save('final_jar_occurrences.json',dict(content=jar_matches,paths=jar_path_matches))
baseline=junit('baseline-junit')
post=junit('junit')
assert baseline['totals']['tests']==82
assert post['totals']['tests']==86
for log in ['baseline','final_gates','production_build']:
    assert (OUT/(log+'.exit')).read_text().strip()=='0'
build_metadata=json.loads((OUT/'gradle_output_metadata.json').read_text(encoding='utf-8'))
assert build_metadata['projectVersion']=='mc26.2+0.1.5.3'
assert build_metadata['archivesName']=='achievetodo'
assert any(Path(j['archive'])==new_path for j in build_metadata['jarTasks'])
assert '"0.1.5.3"' in (ROOT/'src/main/generated/java/com/diskree/achievetodo/BuildConfig.java').read_text(encoding='utf-8')

rows=json.loads((OUT/'repository_occurrences_before.json').read_text(encoding='utf-8'))
archives=json.loads((OUT/'archive_occurrences_before.json').read_text(encoding='utf-8'))
paths=json.loads((OUT/'path_occurrences_before.json').read_text(encoding='utf-8'))
assert not any(r['decision']=='REVIEW' for r in rows+archives), 'Unresolved occurrence classification'
counts=collections.Counter(r['category'] for r in rows+archives)
path_counts=collections.Counter(r['category'] for r in paths)
category_names=dict(A='CURRENT_AUTHOR_OR_OWNER_METADATA',B='CURRENT_USER_FACING_CREDIT',C='CURRENT_PROJECT_URL_OR_CONTACT',
    D='CURRENT_COPYRIGHT_NOTICE',E='TECHNICAL_NAMESPACE',F='HISTORICAL_IMMUTABLE_EVIDENCE',
    G='HISTORICAL_PROVENANCE_STATEMENT',H='THIRD_PARTY_REFERENCE',I='TEST/FIXTURE',J='OTHER')
remaining=[]
for name in {r['path'] for r in rows}:
    remaining.extend(occurrences((ROOT/name).read_bytes(),name))
save('repository_remaining_occurrences.json',remaining)
save('preservation_audit.json',dict(verdict='IDENTITY_ONLY_1152_PRESERVATION_GREEN',checkedProtectedFiles=len(inputs),
    changedFiles=changed, unchangedProtectedFiles=len(inputs)-len(changed), jarChangedEntries=delta,
    unchangedJarEntries=len(names)-len(delta),productCertified=1152,productUncertified=0,
    historicalPhaseACertified=1133,FINAL19='PRESERVED_NOT_REOPENED',
    userSmoke=['Axe USER_SMOKE_GREEN semantics preserved','Cauldron USER_SMOKE_GREEN semantics preserved','Deflect Arrow USER_SMOKE_GREEN semantics preserved','save/reload/rejoin preserved'],
    proof='Fresh 82 retained release gates plus byte-identical production classes/resources except BuildConfig version; all prior evidence hashes preserved. No new native certification claim.'))
manifest=dict(schemaVersion=1,task='AUTHOR_IDENTITY_AND_OWNERSHIP_PASS',status='PRE_26_2_AUTHOR_IDENTITY_BUILD_0_1_5_3_READY',
    acceptance='PENDING_USER_SMOKE_AND_ACCEPTANCE',date='2026-10-01',currentAuthor='Glower4ek',
    rightsTransfer='Full project rights transfer explicitly stated by user.',
    copyrightBefore='Copyright (c) 2024 diskree',copyrightAfter='Copyright (c) 2026 Glower4ek',mitBodyUnchanged=True,
    verifiedRemotes=dict(origin='https://github.com/Glower4ek/AchieveToDo.git',upstream='https://github.com/AchieveToDo/mod.git'),
    currentContact=metadata['contact'],authors=metadata['authors'],contributors=None,
    javaNamespace='com.diskree',projectVersion='mc26.2+0.1.5.3',canonicalVersionSource='gradle.properties:modVersion',
    categoryLegend=category_names,
    derivedCurrentMetadataChanges=[dict(category='A',field='fabric.mod.json:authors',before=['diskree'],after=['Glower4ek']),
        dict(category='C',field='fabric.mod.json:contact.sources',before='https://github.com/diskree/AchieveToDo',after='https://github.com/Glower4ek/AchieveToDo'),
        dict(category='D',field='LICENSE_achievetodo',before='Copyright (c) 2024 diskree',after='Copyright (c) 2026 Glower4ek')],
    artifact=dict(path=str(new_path),filename=new_path.name,bytes=new_path.stat().st_size,sha256=sha(new_path.read_bytes()),internalVersion=metadata['version']),
    audit=dict(scope='All repository files, ignored/untracked included, plus decompressed local ZIP/JAR entries. Infrastructure .git, .gradle, .gradle-user-home and .idea excluded; build output audited separately in final JAR and generated metadata. New report namespace excluded from baseline counts to prevent self-counting.',
        contentOccurrences=len(rows),archiveContentOccurrences=len(archives),totalContentOccurrences=len(rows)+len(archives),pathOccurrences=len(paths),
        categoryCounts={k:counts[k] for k in category_names},pathCategoryCounts={k:path_counts[k] for k in category_names},totalOccurrencesIncludingPaths=len(rows)+len(archives)+len(paths),
        changedOccurrences=sum(r['decision']=='CHANGE' for r in rows+archives),
        retainedTechnical=counts['E']+path_counts['E'],retainedHistoricalEvidenceProvenance=counts['F']+counts['G']+path_counts['F']+path_counts['G'],
        finalJarContentOccurrences=len(jar_matches),finalJarPathOccurrences=len(jar_path_matches),
        finalJarCategories=dict(collections.Counter(r['category'] for r in jar_matches)),unexplained=0),
    changedFiles=changed,tests=dict(baseline=baseline,post=post,compileJava='GREEN',compileTestJava='GREEN',compileGametestJava='GREEN',
        normalBuild='GREEN: build -x test -x runGameTest after authoritative 86-test gates; preserves accepted release routing without restarting closed native campaigns.'),
    certification=dict(productCertified=1152,total=1152,uncertified=0,historicalPhaseACertified=1133,FINAL19='PRESERVED_NOT_REOPENED'),
    jarDelta=delta,gitSafety='No Git mutation, branch change, cleanup or Phase B.',
    evidenceFiles={p.name:sha(p.read_bytes()) for p in OUT.iterdir() if p.is_file() and p.name not in ['author_identity_manifest.json','author_identity_report.md','durable_hashes.json']})
save('author_identity_manifest.json',manifest)
report=f'''# Author identity candidate 0.1.5.3

Status: PRE_26_2_AUTHOR_IDENTITY_BUILD_0_1_5_3_READY. Pending user smoke/acceptance.

The user states a full project rights transfer. Current author/maintainer: Glower4ek.
Copyright changed from `Copyright (c) 2024 diskree` to `Copyright (c) 2026 Glower4ek`; MIT grant/body is byte-identical.
Verified origin: https://github.com/Glower4ek/AchieveToDo.git. Packaged contact sources: https://github.com/Glower4ek/AchieveToDo.
Authors: ["Glower4ek"]. No contributors field. Technical namespace/group: com.diskree, unchanged.

## Occurrence ledger

{len(rows)+len(archives)} baseline content occurrences: {len(rows)} in physical repository files and {len(archives)} in decompressed archive entries; {len(paths)} separately counted path/entry-name occurrences.
Total including path/entry-name matches: {len(rows)+len(archives)+len(paths)}. Changed: {manifest['audit']['changedOccurrences']}; retained technical including paths: {manifest['audit']['retainedTechnical']}; retained historical evidence/provenance: {manifest['audit']['retainedHistoricalEvidenceProvenance']}; third-party attribution: {counts['H']}.
All A-J decisions, precise file/entry byte offsets, context and reasons are recorded in repository_occurrences_before.json, archive_occurrences_before.json and path_occurrences_before.json.
Scope and infrastructure exclusions are explicit in the manifest. Existing scratch/upstream snapshots are provenance, never current metadata; no cleanup performed.
The two changed baseline literals are the canonical author property (A) and current copyright notice (D). Generated author (A), source URL (C) and packaged copyright (D) update through the normal build; no historical artifact is rewritten. README now names the current owner and maintainer. No present-owner claim was found in historical/planning prose outside the retained release snapshots. No current-owner contributors, UI/about, localization or source-header notice required replacement.

| Category | Meaning | Content count | Path count | Decision |
| --- | --- | ---: | ---: | --- |
'''+''.join(f'| {k} | {v} | {counts[k]} | {path_counts[k]} | '+('CHANGE' if k in ['A','D'] and counts[k] else 'KEEP' if counts[k]+path_counts[k] else 'No baseline literal')+' |\n' for k,v in category_names.items())+f'''

## Artifact and preservation

`{new_path}` — {new_path.stat().st_size} bytes; SHA-256 `{manifest['artifact']['sha256']}`; internal version 0.1.5.3; Gradle version mc26.2+0.1.5.3.
Compared with the retained 0.1.5.2 archive, identical entry names and {len(names)-len(delta)} byte-identical entries. Only fabric.mod.json, LICENSE_achievetodo and BuildConfig.class differ.
All production semantics, BUG-01 through BUG-04, mixins, package paths, ability/localization/data resources and prior accepted native evidence are preserved.
FINAL19 is not reopened. 1152/1152 product-certified, 0 uncertified; historical Phase A remains 1133/1152.
Prior Axe, Cauldron, Deflect Arrow USER_SMOKE_GREEN semantics and save/reload/rejoin are preserved; this candidate awaits its own acceptance.

Final archive case-insensitive search: {len(jar_matches)} content matches and {len(jar_path_matches)} entry-name matches, fully classified in final_jar_occurrences.json.
Every remaining content match is a required technical namespace or the original author provenance of the third-party BACAP Better RU 2.3 resource in LICENSE_bacap-better-ru. That attribution is H, retained intentionally; it does not identify the current AchieveToDo owner.
Every mixin/entrypoint class exists; no duplicate entries or test/GameTest/planning/debug leakage.

## Authoritative verification

Before edits: compileJava, compileTestJava, compileGametestJava GREEN; 82 tests, zero failures/errors/skips.
After edits: those three compile tasks GREEN; 86 tests, zero failures/errors/skips (82 retained plus four focused identity tests).
Normal accepted release build `build -x test -x runGameTest` GREEN after the authoritative test gates; unrelated closed native campaigns are not restarted.
Preservation checks and every changed-file before/after hash are in preservation_audit.json. Existing 0.1.5.2 JAR and prior reports/manifests/evidence remain hash-identical.
No Java/Kotlin production-semantic source edit, Git mutation, branch change, cleanup, or Phase B.

Manifest SHA-256: `{sha((OUT/'author_identity_manifest.json').read_bytes())}`. Both report hashes are recorded in durable_hashes.json.
'''
(OUT/'author_identity_report.md').write_text(report,encoding='utf-8')
save('durable_hashes.json',{name:sha((OUT/name).read_bytes()) for name in ['author_identity_manifest.json','author_identity_report.md']})
print(json.dumps(dict(artifact=manifest['artifact'],audit=manifest['audit'],baseline=baseline['totals'],post=post['totals'],hashes=json.loads((OUT/'durable_hashes.json').read_text())),indent=2))
