org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-download=false

author=Glower4ek
javaNamespace=com.diskree
repoUrl=https://github.com/Glower4ek/AchieveToDo
modName=AchieveToDo
modVersion=0.1.5.5

minJavaVersion=25
minMinecraftVersion=26.2
minLoaderVersion=0.19.5
apiVersion=0.161.0
loomVersion=1.18.2

tomlVersion=0.7.2
junitVersion=6.1.3
