version = 1

[abilities]
vision = 0
eat_salmon = 880
eat_cod = 319
eat_tropical_fish = 418
jump = 8
swim = 14
eat_rotten_flesh = 38
eat_spider_eye = 130
eat_sweet_berries = 114
open_door = 159
eat_glow_berries = 693
interact_inside_village = 132
sleep = 24
eat_poisonous_potato = 425
sneak = 28
sprint = 30
open_inventory = 32
break_blocks = 34
eat_suspicious_stew = 136
use_golden_tools = 476
open_chest = 578
eat_chicken = -1
eat_carrot = 49
open_crafting_table = 54
equip_golden_armor = 510
open_barrel = 295
eat_beetroot = 300
eat_dried_kelp = 844
eat_potato = 352
open_stonecutter = 538
get_into_boat = 44
eat_apple = 2
interact_inside_shipwreck = 810
use_shield = 615
eat_melon_slice = 781
interact_inside_ruined_portal = 2
open_furnace = 670
eat_cookie = 107
interact_inside_buried_treasure = 291
eat_mushroom_stew = 126
eat_beetroot_soup = 541
put_in_bundle = 46
eat_rabbit_stew = 220
open_trapdoor = 372
use_wooden_tools = 61
eat_honey = 313
interact_inside_igloo = 161
use_water_bucket = 153
eat_mutton = 133
throw_snowball = 193
interact_inside_ocean_ruin = 10
equip_leather_armor = 371
eat_pufferfish = 261
open_fence_gate = 688
eat_pumpkin_pie = 72
eat_golden_apple = 732
use_shears = 46
interact_inside_desert_pyramid = 856
break_blocks_in_negative_y = 42
eat_enchanted_golden_apple = 127
interact_inside_mineshaft = 622
throw_egg = 472
use_stone_tools = 584
open_grindstone = 125
shoot_crossbow = 376
eat_rabbit = 767
interact_inside_swamp_hut = 246
equip_chainmail_armor = 325
open_anvil = 598
use_flint_and_steel = 121
ignite_tnt = 74
interact_inside_ancient_city = 522
enter_nether = 396
trade_with_wandering_trader = 192
get_into_minecart = 764
interact_inside_fortress = 464
use_ominous_bottle = 377
use_iron_tools = 399
interact_inside_jungle_pyramid = 151
attack_with_trident = 420
equip_iron_armor = 532
shoot_bow = 198
interact_inside_bastion_remnant = 208
use_jukebox = 474
throw_ender_pearl = 187
use_composter = 519
charge_respawn_anchor = 259
eat_beef = 640
interact_inside_pillager_outpost = 208
trade_with_mason = 290
use_fishing_rod = 217
eat_porkchop = 2
trade_with_cartographer = 257
interact_inside_monument = 269
use_diamond_tools = 368
use_cauldron = 579
interact_inside_monster_room = 2
eat_baked_potato = 2
open_smoker = 752
equip_turtle_helmet = 334
interact_inside_trail_ruins = 76
use_brush = 278
equip_diamond_armor = 362
unlock_vault = 302
open_blast_furnace = 577
interact_inside_stronghold = 0
trade_with_leatherworker = 164
use_spyglass = 489
interact_inside_mansion = 2
open_beacon = 563
throw_wind_charge = 431
enter_end = 272
open_cartography_table = 214
interact_inside_desert_well = 197
eat_cooked_salmon = 48
equip_elytra = 544
trade_with_shepherd = 766
trade_with_butcher = 652
interact_inside_trial_chambers = 298
open_ender_chest = 679
attack_with_mace = 80
interact_inside_end_city = 638
use_ender_eye = 164
teleport_outer_islands = 786
use_netherite_tools = 436
eat_cooked_cod = 22
trade_with_farmer = 2
glide_with_fireworks = 676
trade_with_cleric = 232
equip_netherite_armor = 222
open_brewing_stand = 172
eat_cooked_rabbit = 280
place_end_crystal = 780
trade_with_fisherman = 608
open_smithing_table = 365
eat_cooked_chicken = 67
eat_chorus_fruit = 112
trade_with_fletcher = 155
eat_cooked_mutton = 392
trade_with_armorer = 22
eat_cooked_porkchop = 377
eat_bread = 614
trade_with_weaponsmith = 441
eat_cooked_beef = 828
open_loom = 162
use_campfire = 551
open_shulker_box = 632
eat_golden_carrot = 237
trade_with_toolsmith = 103
trade_with_librarian = 2
open_enchanting_table = 194
