version = 1

[abilities]
vision = 0
eat_salmon = 75
eat_cod = 544
eat_tropical_fish = 141
jump = 8
swim = 14
eat_rotten_flesh = 450
eat_spider_eye = 305
eat_sweet_berries = 353
open_door = 70
eat_glow_berries = 52
interact_inside_village = 280
sleep = 24
eat_poisonous_potato = 134
sneak = 28
sprint = 30
open_inventory = 32
break_blocks = 34
eat_suspicious_stew = 479
use_golden_tools = 737
open_chest = 6
eat_chicken = 2
eat_carrot = 760
open_crafting_table = 54
equip_golden_armor = 50
open_barrel = 136
eat_beetroot = 2
eat_dried_kelp = 537
eat_potato = 78
open_stonecutter = 360
get_into_boat = 44
eat_apple = 636
interact_inside_shipwreck = 408
use_shield = 319
eat_melon_slice = 341
interact_inside_ruined_portal = 536
open_furnace = 435
eat_cookie = 151
interact_inside_buried_treasure = 191
eat_mushroom_stew = 262
eat_beetroot_soup = 701
put_in_bundle = 46
eat_rabbit_stew = 271
open_trapdoor = 99
use_wooden_tools = 191
eat_honey = 149
interact_inside_igloo = 297
use_water_bucket = 239
eat_mutton = 300
throw_snowball = 82
interact_inside_ocean_ruin = 699
equip_leather_armor = 618
eat_pufferfish = 529
open_fence_gate = 284
eat_pumpkin_pie = 749
eat_golden_apple = 511
use_shears = 169
interact_inside_desert_pyramid = 255
break_blocks_in_negative_y = 42
eat_enchanted_golden_apple = 178
interact_inside_mineshaft = 322
throw_egg = 38
use_stone_tools = 103
open_grindstone = 301
shoot_crossbow = 735
eat_rabbit = 793
interact_inside_swamp_hut = 81
equip_chainmail_armor = 73
open_anvil = 177
use_flint_and_steel = 331
ignite_tnt = 496
interact_inside_ancient_city = 70
enter_nether = 200
trade_with_wandering_trader = 460
get_into_minecart = 357
interact_inside_fortress = 223
use_ominous_bottle = 400
use_iron_tools = 405
interact_inside_jungle_pyramid = 842
attack_with_trident = 15
equip_iron_armor = 163
shoot_bow = 62
interact_inside_bastion_remnant = 584
use_jukebox = 509
throw_ender_pearl = 651
use_composter = 288
charge_respawn_anchor = 54
eat_beef = 807
interact_inside_pillager_outpost = 840
trade_with_mason = 898
use_fishing_rod = 221
eat_porkchop = 201
trade_with_cartographer = 141
interact_inside_monument = 794
use_diamond_tools = 34
use_cauldron = 483
interact_inside_monster_room = 609
eat_baked_potato = 175
open_smoker = 590
equip_turtle_helmet = 510
interact_inside_trail_ruins = 204
use_brush = 212
equip_diamond_armor = 369
unlock_vault = 228
open_blast_furnace = 172
interact_inside_stronghold = 461
trade_with_leatherworker = 94
use_spyglass = 674
interact_inside_mansion = 261
open_beacon = 250
throw_wind_charge = 123
enter_end = 409
open_cartography_table = 490
interact_inside_desert_well = 283
eat_cooked_salmon = 37
equip_elytra = 339
trade_with_shepherd = 12
trade_with_butcher = 214
interact_inside_trial_chambers = 422
open_ender_chest = 453
attack_with_mace = 635
interact_inside_end_city = 32
use_ender_eye = 528
teleport_outer_islands = 612
use_netherite_tools = 725
eat_cooked_cod = 56
trade_with_farmer = 594
glide_with_fireworks = 541
trade_with_cleric = 61
equip_netherite_armor = 359
open_brewing_stand = 226
eat_cooked_rabbit = 853
place_end_crystal = 715
trade_with_fisherman = 116
open_smithing_table = 30
eat_cooked_chicken = 175
eat_chorus_fruit = 201
trade_with_fletcher = 2
eat_cooked_mutton = 304
trade_with_armorer = 830
eat_cooked_porkchop = 594
eat_bread = 660
trade_with_weaponsmith = 461
eat_cooked_beef = 261
open_loom = 751
use_campfire = 30
open_shulker_box = 627
eat_golden_carrot = 140
trade_with_toolsmith = 315
trade_with_librarian = 160
open_enchanting_table = 391
