version = 1

[abilities]
vision = 0
eat_salmon = 121
eat_cod = 641
eat_tropical_fish = 188
jump = 8
swim = 14
eat_rotten_flesh = 4
eat_spider_eye = 639
eat_sweet_berries = 613
open_door = 559
eat_glow_berries = 299
interact_inside_village = 418
sleep = 24
eat_poisonous_potato = 8
sneak = 28
sprint = 30
open_inventory = 32
break_blocks = 34
eat_suspicious_stew = 277
use_golden_tools = 308
open_chest = 219
eat_chicken = 513
eat_carrot = 48
open_crafting_table = 54
equip_golden_armor = 107
open_barrel = 0
eat_beetroot = 268
eat_dried_kelp = 367
eat_potato = 167
open_stonecutter = 44
get_into_boat = 44
eat_apple = 133
interact_inside_shipwreck = 167
use_shield = 803
eat_melon_slice = 67
interact_inside_ruined_portal = 557
open_furnace = 342
eat_cookie = -1
interact_inside_buried_treasure = 471
eat_mushroom_stew = 641
eat_beetroot_soup = 83
put_in_bundle = 46
eat_rabbit_stew = 846
open_trapdoor = 142
use_wooden_tools = 406
eat_honey = 563
interact_inside_igloo = 152
use_water_bucket = 5
eat_mutton = 525
throw_snowball = 495
interact_inside_ocean_ruin = 436
equip_leather_armor = 284
eat_pufferfish = 171
open_fence_gate = 267
eat_pumpkin_pie = 172
eat_golden_apple = 594
use_shears = 680
interact_inside_desert_pyramid = 350
break_blocks_in_negative_y = 42
eat_enchanted_golden_apple = 366
interact_inside_mineshaft = 613
throw_egg = 399
use_stone_tools = 121
open_grindstone = 194
shoot_crossbow = 36
eat_rabbit = 66
interact_inside_swamp_hut = 451
equip_chainmail_armor = 258
open_anvil = 71
use_flint_and_steel = 152
ignite_tnt = 104
interact_inside_ancient_city = 36
enter_nether = 269
trade_with_wandering_trader = 10
get_into_minecart = 305
interact_inside_fortress = 306
use_ominous_bottle = 79
use_iron_tools = 288
interact_inside_jungle_pyramid = 869
attack_with_trident = 245
equip_iron_armor = 369
shoot_bow = 377
interact_inside_bastion_remnant = 219
use_jukebox = 482
throw_ender_pearl = 625
use_composter = 80
charge_respawn_anchor = 94
eat_beef = 776
interact_inside_pillager_outpost = 103
trade_with_mason = 59
use_fishing_rod = 182
eat_porkchop = 102
trade_with_cartographer = 317
interact_inside_monument = 721
use_diamond_tools = 70
use_cauldron = 224
interact_inside_monster_room = 105
eat_baked_potato = 595
open_smoker = 746
equip_turtle_helmet = 760
interact_inside_trail_ruins = 478
use_brush = 118
equip_diamond_armor = 809
unlock_vault = 197
open_blast_furnace = 121
interact_inside_stronghold = 539
trade_with_leatherworker = 332
use_spyglass = 227
interact_inside_mansion = 70
open_beacon = 281
throw_wind_charge = 28
enter_end = 494
open_cartography_table = 183
interact_inside_desert_well = 274
eat_cooked_salmon = 31
equip_elytra = 716
trade_with_shepherd = 17
trade_with_butcher = 670
interact_inside_trial_chambers = 716
open_ender_chest = 672
attack_with_mace = 476
interact_inside_end_city = 61
use_ender_eye = 573
teleport_outer_islands = 533
use_netherite_tools = 305
eat_cooked_cod = 203
trade_with_farmer = 38
glide_with_fireworks = 707
trade_with_cleric = 46
equip_netherite_armor = 618
open_brewing_stand = 469
eat_cooked_rabbit = 897
place_end_crystal = 366
trade_with_fisherman = 289
open_smithing_table = 633
eat_cooked_chicken = 219
eat_chorus_fruit = 238
trade_with_fletcher = 444
eat_cooked_mutton = 317
trade_with_armorer = 606
eat_cooked_porkchop = 684
eat_bread = 2
trade_with_weaponsmith = 314
eat_cooked_beef = 797
open_loom = 238
use_campfire = 336
open_shulker_box = 665
eat_golden_carrot = 750
trade_with_toolsmith = 700
trade_with_librarian = 728
open_enchanting_table = 435
