version = 1

[abilities]
vision = 0
eat_salmon = 2
eat_cod = 8
eat_tropical_fish = 12
jump = 0
swim = 4
eat_rotten_flesh = 20
eat_spider_eye = 24
eat_sweet_berries = 16
open_door = 18
eat_glow_berries = 30
interact_inside_village = 152
sleep = 22
eat_poisonous_potato = 34
sneak = 10
sprint = 14
open_inventory = 26
break_blocks = 6
eat_suspicious_stew = 36
use_golden_tools = 38
open_chest = 40
eat_chicken = 44
eat_carrot = 48
open_crafting_table = 46
equip_golden_armor = 50
open_barrel = 52
eat_beetroot = 54
eat_dried_kelp = 62
eat_potato = 58
open_stonecutter = 64
get_into_boat = 42
eat_apple = 72
interact_inside_shipwreck = 70
use_shield = 74
eat_melon_slice = 78
interact_inside_ruined_portal = 76
open_furnace = 82
eat_cookie = 84
interact_inside_buried_treasure = 86
eat_mushroom_stew = 88
eat_beetroot_soup = 92
put_in_bundle = 28
eat_rabbit_stew = 66
open_trapdoor = 94
use_wooden_tools = 60
eat_honey = 98
interact_inside_igloo = 100
use_water_bucket = 102
eat_mutton = 104
throw_snowball = 108
interact_inside_ocean_ruin = 110
equip_leather_armor = 56
eat_pufferfish = 116
open_fence_gate = 120
eat_pumpkin_pie = 144
eat_golden_apple = 124
use_shears = 128
interact_inside_desert_pyramid = 140
break_blocks_in_negative_y = 32
eat_enchanted_golden_apple = 176
interact_inside_mineshaft = 192
throw_egg = 196
use_stone_tools = 90
open_grindstone = 200
shoot_crossbow = 208
eat_rabbit = 212
interact_inside_swamp_hut = 216
equip_chainmail_armor = 80
open_anvil = 180
use_flint_and_steel = 132
ignite_tnt = 136
interact_inside_ancient_city = 258
enter_nether = 172
trade_with_wandering_trader = 96
get_into_minecart = 112
interact_inside_fortress = 240
use_ominous_bottle = 282
use_iron_tools = 106
interact_inside_jungle_pyramid = 300
attack_with_trident = 188
equip_iron_armor = 168
shoot_bow = 270
interact_inside_bastion_remnant = 252
use_jukebox = 220
throw_ender_pearl = 164
use_composter = 236
charge_respawn_anchor = 360
eat_beef = 264
interact_inside_pillager_outpost = 372
trade_with_mason = 156
use_fishing_rod = 148
eat_porkchop = 324
trade_with_cartographer = 224
interact_inside_monument = 390
use_diamond_tools = 318
use_cauldron = 414
interact_inside_monster_room = 420
eat_baked_potato = 384
open_smoker = 426
equip_turtle_helmet = 432
interact_inside_trail_ruins = 438
use_brush = 204
equip_diamond_armor = 288
unlock_vault = 450
open_blast_furnace = 160
interact_inside_stronghold = 408
trade_with_leatherworker = 276
use_spyglass = 244
interact_inside_mansion = 480
open_beacon = 402
throw_wind_charge = 248
enter_end = 378
open_cartography_table = 232
interact_inside_desert_well = 492
eat_cooked_salmon = 366
equip_elytra = 498
trade_with_shepherd = 312
trade_with_butcher = 354
interact_inside_trial_chambers = 528
open_ender_chest = 306
attack_with_mace = 330
interact_inside_end_city = 516
use_ender_eye = 342
teleport_outer_islands = 540
use_netherite_tools = 336
eat_cooked_cod = 486
trade_with_farmer = 396
glide_with_fireworks = 546
trade_with_cleric = 456
equip_netherite_armor = 462
open_brewing_stand = 552
eat_cooked_rabbit = 294
place_end_crystal = 522
trade_with_fisherman = 474
open_smithing_table = 228
eat_cooked_chicken = 444
eat_chorus_fruit = 558
trade_with_fletcher = 510
eat_cooked_mutton = 468
trade_with_armorer = 534
eat_cooked_porkchop = 570
eat_bread = 348
trade_with_weaponsmith = 564
eat_cooked_beef = 576
open_loom = 184
use_campfire = 68
open_shulker_box = 504
eat_golden_carrot = 588
trade_with_toolsmith = 582
trade_with_librarian = 594
open_enchanting_table = 600
