version = 1

[abilities]
vision = 2
eat_salmon = 4
eat_cod = 6
eat_tropical_fish = 10
jump = 8
swim = 14
eat_rotten_flesh = 16
eat_spider_eye = 18
eat_sweet_berries = 12
open_door = 20
eat_glow_berries = 22
interact_inside_village = 246
sleep = 24
eat_poisonous_potato = 26
sneak = 28
sprint = 30
open_inventory = 32
break_blocks = 34
eat_suspicious_stew = 36
use_golden_tools = 38
open_chest = 40
eat_chicken = 50
eat_carrot = 58
open_crafting_table = 54
equip_golden_armor = 62
open_barrel = 66
eat_beetroot = 70
eat_dried_kelp = 86
eat_potato = 78
open_stonecutter = 90
get_into_boat = 44
eat_apple = 106
interact_inside_shipwreck = 102
use_shield = 110
eat_melon_slice = 118
interact_inside_ruined_portal = 114
open_furnace = 126
eat_cookie = 130
interact_inside_buried_treasure = 134
eat_mushroom_stew = 138
eat_beetroot_soup = 146
put_in_bundle = 46
eat_rabbit_stew = 94
open_trapdoor = 150
use_wooden_tools = 82
eat_honey = 158
interact_inside_igloo = 162
use_water_bucket = 166
eat_mutton = 170
throw_snowball = 178
interact_inside_ocean_ruin = 182
equip_leather_armor = 74
eat_pufferfish = 192
open_fence_gate = 198
eat_pumpkin_pie = 234
eat_golden_apple = 204
use_shears = 210
interact_inside_desert_pyramid = 228
break_blocks_in_negative_y = 42
eat_enchanted_golden_apple = 282
interact_inside_mineshaft = 306
throw_egg = 312
use_stone_tools = 142
open_grindstone = 318
shoot_crossbow = 330
eat_rabbit = 336
interact_inside_swamp_hut = 342
equip_chainmail_armor = 122
open_anvil = 288
use_flint_and_steel = 216
ignite_tnt = 222
interact_inside_ancient_city = 404
enter_nether = 276
trade_with_wandering_trader = 154
get_into_minecart = 186
interact_inside_fortress = 378
use_ominous_bottle = 436
use_iron_tools = 174
interact_inside_jungle_pyramid = 460
attack_with_trident = 300
equip_iron_armor = 270
shoot_bow = 420
interact_inside_bastion_remnant = 396
use_jukebox = 348
throw_ender_pearl = 264
use_composter = 372
charge_respawn_anchor = 540
eat_beef = 412
interact_inside_pillager_outpost = 556
trade_with_mason = 252
use_fishing_rod = 240
eat_porkchop = 492
trade_with_cartographer = 354
interact_inside_monument = 580
use_diamond_tools = 484
use_cauldron = 612
interact_inside_monster_room = 620
eat_baked_potato = 572
open_smoker = 628
equip_turtle_helmet = 636
interact_inside_trail_ruins = 644
use_brush = 324
equip_diamond_armor = 444
unlock_vault = 660
open_blast_furnace = 258
interact_inside_stronghold = 604
trade_with_leatherworker = 428
use_spyglass = 384
interact_inside_mansion = 700
open_beacon = 596
throw_wind_charge = 390
enter_end = 564
open_cartography_table = 366
interact_inside_desert_well = 716
eat_cooked_salmon = 548
equip_elytra = 724
trade_with_shepherd = 476
trade_with_butcher = 532
interact_inside_trial_chambers = 764
open_ender_chest = 468
attack_with_mace = 500
interact_inside_end_city = 748
use_ender_eye = 516
teleport_outer_islands = 780
use_netherite_tools = 508
eat_cooked_cod = 708
trade_with_farmer = 588
glide_with_fireworks = 788
trade_with_cleric = 668
equip_netherite_armor = 676
open_brewing_stand = 796
eat_cooked_rabbit = 452
place_end_crystal = 756
trade_with_fisherman = 692
open_smithing_table = 360
eat_cooked_chicken = 652
eat_chorus_fruit = 804
trade_with_fletcher = 740
eat_cooked_mutton = 684
trade_with_armorer = 772
eat_cooked_porkchop = 820
eat_bread = 524
trade_with_weaponsmith = 812
eat_cooked_beef = 828
open_loom = 294
use_campfire = 98
open_shulker_box = 732
eat_golden_carrot = 844
trade_with_toolsmith = 836
trade_with_librarian = 852
open_enchanting_table = 860
