version = 1

[abilities]
vision = 0
eat_salmon = 2
eat_cod = 6
eat_tropical_fish = 8
jump = 4
swim = 10
eat_rotten_flesh = 18
eat_spider_eye = 22
eat_sweet_berries = 14
open_door = 20
eat_glow_berries = 26
interact_inside_village = 199
sleep = 24
eat_poisonous_potato = 28
sneak = 12
sprint = 16
open_inventory = 30
break_blocks = 32
eat_suspicious_stew = 34
use_golden_tools = 40
open_chest = 42
eat_chicken = 47
eat_carrot = 53
open_crafting_table = 50
equip_golden_armor = 56
open_barrel = 59
eat_beetroot = 62
eat_dried_kelp = 74
eat_potato = 68
open_stonecutter = 77
get_into_boat = 44
eat_apple = 89
interact_inside_shipwreck = 86
use_shield = 92
eat_melon_slice = 98
interact_inside_ruined_portal = 95
open_furnace = 104
eat_cookie = 107
interact_inside_buried_treasure = 110
eat_mushroom_stew = 113
eat_beetroot_soup = 119
put_in_bundle = 36
eat_rabbit_stew = 80
open_trapdoor = 122
use_wooden_tools = 71
eat_honey = 128
interact_inside_igloo = 131
use_water_bucket = 134
eat_mutton = 137
throw_snowball = 143
interact_inside_ocean_ruin = 146
equip_leather_armor = 65
eat_pufferfish = 154
open_fence_gate = 159
eat_pumpkin_pie = 189
eat_golden_apple = 164
use_shears = 169
interact_inside_desert_pyramid = 184
break_blocks_in_negative_y = 38
eat_enchanted_golden_apple = 229
interact_inside_mineshaft = 249
throw_egg = 254
use_stone_tools = 116
open_grindstone = 259
shoot_crossbow = 269
eat_rabbit = 274
interact_inside_swamp_hut = 279
equip_chainmail_armor = 101
open_anvil = 234
use_flint_and_steel = 174
ignite_tnt = 179
interact_inside_ancient_city = 331
enter_nether = 224
trade_with_wandering_trader = 125
get_into_minecart = 149
interact_inside_fortress = 309
use_ominous_bottle = 359
use_iron_tools = 140
interact_inside_jungle_pyramid = 380
attack_with_trident = 244
equip_iron_armor = 219
shoot_bow = 345
interact_inside_bastion_remnant = 324
use_jukebox = 284
throw_ender_pearl = 214
use_composter = 304
charge_respawn_anchor = 450
eat_beef = 338
interact_inside_pillager_outpost = 464
trade_with_mason = 204
use_fishing_rod = 194
eat_porkchop = 408
trade_with_cartographer = 289
interact_inside_monument = 485
use_diamond_tools = 401
use_cauldron = 513
interact_inside_monster_room = 520
eat_baked_potato = 478
open_smoker = 527
equip_turtle_helmet = 534
interact_inside_trail_ruins = 541
use_brush = 264
equip_diamond_armor = 366
unlock_vault = 555
open_blast_furnace = 209
interact_inside_stronghold = 506
trade_with_leatherworker = 352
use_spyglass = 314
interact_inside_mansion = 590
open_beacon = 499
throw_wind_charge = 319
enter_end = 471
open_cartography_table = 299
interact_inside_desert_well = 604
eat_cooked_salmon = 457
equip_elytra = 611
trade_with_shepherd = 394
trade_with_butcher = 443
interact_inside_trial_chambers = 646
open_ender_chest = 387
attack_with_mace = 415
interact_inside_end_city = 632
use_ender_eye = 429
teleport_outer_islands = 660
use_netherite_tools = 422
eat_cooked_cod = 597
trade_with_farmer = 492
glide_with_fireworks = 667
trade_with_cleric = 562
equip_netherite_armor = 569
open_brewing_stand = 674
eat_cooked_rabbit = 373
place_end_crystal = 639
trade_with_fisherman = 583
open_smithing_table = 294
eat_cooked_chicken = 548
eat_chorus_fruit = 681
trade_with_fletcher = 625
eat_cooked_mutton = 576
trade_with_armorer = 653
eat_cooked_porkchop = 695
eat_bread = 436
trade_with_weaponsmith = 688
eat_cooked_beef = 702
open_loom = 239
use_campfire = 83
open_shulker_box = 618
eat_golden_carrot = 716
trade_with_toolsmith = 709
trade_with_librarian = 723
open_enchanting_table = 730
