package com.diskree.achievetodo.certification;
import com.google.gson.*;
import org.junit.jupiter.api.Test;
import java.nio.file.*;
import static org.junit.jupiter.api.Assertions.*;
class Final19PreservedInventoryMastersAcceptanceTest {
    static final String FAMILY="INVENTORY_ENCHANTMENT_ITEM_TAG_CONTEXT";static final Path ROOT=Path.of("").toAbsolutePath();
    static Path path(){return Files.exists(ROOT.resolve(Final19FamilyEvidence.persistent(FAMILY)))?Final19FamilyEvidence.persistent(FAMILY):Final19FamilyEvidence.temp(FAMILY);}
    static void independent(JsonObject a)throws Exception{var durable=ROOT.resolve("reference/phase_a_planning/final19/accepted_transactions/inventory_enchantment_item_tag_context/inventory_masters_static.json");var staticProof=Final19WorldgenEvidence.read(Files.exists(durable)?durable:ROOT.resolve("build/tmp/final19_implementation/inventory_masters_static.json"));for(var value:a.getAsJsonArray("entries")){var r=value.getAsJsonObject();assertEquals("ItemEntity.playerTouch -> Inventory.add",r.get("nativeBoundary").getAsString());var tag=staticProof.getAsJsonObject("sourceBackedTags").getAsJsonObject("minecraft:item|"+r.get("checkedItemTag").getAsString().substring(1)).getAsJsonArray("resolvedMembers");assertTrue(tag.asList().contains(r.get("observedItem")));var actual=r.getAsJsonObject("observedEnchantments");assertTrue(actual.size()>0);var missing=r.getAsJsonObject("missingObservedEnchantments");var under=r.getAsJsonObject("underlevelObservedEnchantments");assertEquals(actual.size()-1,missing.size());assertNotEquals(actual,under);boolean lower=false;for(var e:actual.entrySet())if(!under.has(e.getKey())||under.get(e.getKey()).getAsInt()<e.getValue().getAsInt())lower=true;assertTrue(lower);}}
    @Test void allNineActualInventoryGroupsAndLegalNativePickupsPass()throws Exception{var a=Final19PreservedFamilyEvidence.validate(ROOT,FAMILY,path(),true);assertEquals(9,a.getAsJsonArray("entries").size());independent(a);}
    @Test void missingDuplicateStaleIllegalUnderlevelUnsupportedAndFakeNegativeClaimsRejected()throws Exception{var original=Final19WorldgenEvidence.read(ROOT.resolve(path()));Path scratch=Path.of("build/tmp/final19_implementation/inventory_masters_mutated.json");for(int i=0;i<8;i++){var a=original.deepCopy();var entries=a.getAsJsonArray("entries");var r=entries.get(0).getAsJsonObject();switch(i){case 0->entries.remove(0);case 1->entries.add(r.deepCopy());case 2->a.addProperty("fingerprint","stale");case 3->r.addProperty("supportedEnchantments",false);case 4->r.addProperty("compatibleEnchantments",false);case 5->r.getAsJsonObject("observedEnchantments").addProperty("minecraft:protection",1);case 6->r.add("missingObservedEnchantments",r.get("observedEnchantments"));case 7->r.addProperty("observedItem","minecraft:stick");}Final19WorldgenEvidence.write(ROOT.resolve(scratch),a);assertThrows(Throwable.class,()->{independent(a);Final19PreservedFamilyEvidence.validate(ROOT,FAMILY,scratch,true);});}}
}
