package com.diskree.achievetodo.certification;
import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import static com.diskree.achievetodo.certification.Final19StaticContext.require;

/** Promotion and additive new-stage accounting, only after native/static independent gates. */
public final class Final19FamilyPromotion {
    public static void main(String[] args)throws Exception {
        Path root=Path.of(args[0]);String family=args[1],prefix=Final19FamilyEvidence.prefix(family);Path base=root.resolve("reference/phase_a_planning/final19"),scratch=root.resolve("build/tmp/final19_implementation");
        var exact=Final19FamilyEvidence.validate(root,family,Final19FamilyEvidence.temp(family),true);var canary=Final19FamilyEvidence.validate(root,family,Path.of("build/tmp/final19_implementation/"+prefix+"_canary_evidence.json"),false);require(!exact.get("runId").equals(canary.get("runId")),"Reused canary/exact run ID");
        var run=Final19WorldgenEvidence.read(root.resolve(Final19FamilyEvidence.run(family)));require(run.get("stage").getAsString().equals("TEMP_PROMOTABLE"),"Unfinished TEMP");
        for(var mode:List.of("canary","exact")){String name=prefix+"_"+mode;require(Files.readString(scratch.resolve(name+".exit")).trim().equals("0"),"Nonzero native exit");String log=Files.readString(scratch.resolve(name+".gradle.log"));int count=mode.equals("exact")?Final19FamilyEvidence.rows(root,family,true).size():Final19FamilyEvidence.rows(root,family,false).size();require(log.contains("BUILD SUCCESSFUL")&&log.contains("entries="+count)&&log.contains(" (1 tests)"),"Wrong native selector/count/result");int start=log.indexOf("FINAL19_NATIVE_RUN_START family="+family);require(start>=0,"Missing native scope");String nativeLog=log.substring(start);require(!nativeLog.contains("/WARN]")&&!nativeLog.contains("/ERROR]")&&!nativeLog.contains("Failed to handle packet")&&!nativeLog.contains("Leak:"),"Native warning/network debt");JsonObject startup=new JsonObject();JsonArray warnings=new JsonArray();for(String line:log.substring(0,start).split("\\R"))if(line.contains("/WARN]")||line.contains("/ERROR]"))warnings.add(line);startup.addProperty("scope","BEFORE_NATIVE_TEST_INVOCATION_NO_OWNED_ACTORS");startup.add("observedWarnings",warnings);Final19WorldgenEvidence.write(base.resolve(name+"_startup_warning_inventory.json"),startup);}
        require(Files.readString(scratch.resolve(prefix+"_validation.exit")).trim().equals("0")&&Files.readString(scratch.resolve(prefix+"_validation.gradle.log")).contains("BUILD SUCCESSFUL"),"Missing independent JUnit/static validation");
        try(var context=new Final19StaticContext(root,family)){context.validate(family);}
        require(Final19StaticContext.sha(Files.readAllBytes(root.resolve("src/test/resources/phase_a_certification/phase_a_advancement_rollup.json"))).equals("439f2aa1c577ffbee275525765ac9229bf5633f0f5e1da498c0adc5702bd2810"),"Historical Phase A changed");
        Path persistent=root.resolve(Final19FamilyEvidence.persistent(family));if(Files.exists(persistent))require(Files.readString(persistent).equals(Files.readString(root.resolve(Final19FamilyEvidence.temp(family)))),"Different persistent bytes already accepted");else Files.copy(root.resolve(Final19FamilyEvidence.temp(family)),persistent);Final19FamilyEvidence.validate(root,family,Final19FamilyEvidence.persistent(family),true);
        var ledger=Final19WorldgenEvidence.read(base.resolve("product_ledger.json"));Set<String> targets=new TreeSet<>();for(var source:Final19FamilyEvidence.catalog(root,family).getAsJsonArray("sources"))targets.add(source.getAsJsonObject().get("advancementId").getAsString());Set<String> ids=new HashSet<>();int certified=0,gained=0,final19=0;
        for(var value:ledger.getAsJsonArray("entries")){var entry=value.getAsJsonObject();String id=entry.get("id").getAsString();require(ids.add(id),"Duplicate total advancement");if(targets.contains(id)){if(!entry.has("productStatus"))gained++;else require(entry.get("final19Family").getAsString().equals(family),"Target attributed to other family");entry.addProperty("productStatus","FINAL19_CERTIFIED");entry.addProperty("final19Family",family);entry.addProperty("productRequirementsSatisfied",true);}if(entry.has("productStatus")){certified++;final19++;}else if(Set.of("STATIC_CERTIFIED","RUNTIME_CERTIFIED").contains(entry.get("advancementStatus").getAsString()))certified++;}
        require(ids.size()==1152&&certified==ledger.get("productCertified").getAsInt()+gained&&targets.size()>0,"Wrong actual advancement delta");ledger.addProperty("productCertified",certified);ledger.addProperty("productUncertified",1152-certified);var summary=ledger.getAsJsonObject("summary");summary.addProperty("totalCertified",certified);summary.addProperty("uncertified",1152-certified);summary.addProperty("final19Certified",final19);Final19WorldgenEvidence.write(base.resolve("product_ledger.json"),ledger);
        var state=Final19WorldgenEvidence.read(base.resolve("execution_state.json"));require(state.get("activeFamily").getAsString().equals(family),"Wrong active transaction");state.addProperty("productCertified",certified);state.getAsJsonArray("completedFamilies").add(family);JsonArray remaining=new JsonArray();for(var id:state.getAsJsonArray("remainingTargets"))if(!targets.contains(id.getAsString()))remaining.add(id);state.add("remainingTargets",remaining);state.getAsJsonArray("acceptedRunIds").add(exact.get("runId"));
        List<String> order=new ArrayList<>();for(var name:state.getAsJsonArray("familyOrder"))order.add(name.getAsString());String next=order.get(order.indexOf(family)+1);state.addProperty("activeFamily",next);state.addProperty("nextOperationalFamily",next);state.addProperty("transactionStage","PERSISTENT_REGRESSION_AND_CHECKPOINT_PENDING");state.addProperty("firstUnfinishedTransaction",family+": persistent ledger regression + durable checkpoint, then "+next);
        var receipt=new JsonObject();receipt.addProperty("family",family);receipt.addProperty("path",Final19FamilyEvidence.persistent(family).toString());receipt.addProperty("sha256",Final19StaticContext.sha(Files.readAllBytes(persistent)));receipt.add("runId",exact.get("runId"));receipt.addProperty("catalogSha256",Final19StaticContext.sha(Files.readAllBytes(root.resolve(Final19StaticContext.RESOURCES).resolve(family.toLowerCase(Locale.ROOT)+"_catalog.json"))));state.getAsJsonArray("persistentEvidenceInventory").add(receipt);Final19WorldgenEvidence.write(base.resolve("execution_state.json"),state);System.out.println(family+"_FINAL19_GREEN productCertified="+certified+" runId="+exact.get("runId"));
    }
}
