package com.diskree.achievetodo.certification;
import com.google.gson.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.zip.ZipFile;
import static com.diskree.achievetodo.certification.Final19StaticContext.require;

/** Shared envelopes, exact group accounting and independent observed-witness validators. */
public final class Final19FamilyEvidence {
    public static String prefix(String family){return switch(family){case "ENTITY_VARIANT_COMPONENT_CONTEXT"->"variants";case "DUAL_ITEM_BLOCK_TAG_CONTEXT"->"dual_tags";case "INVENTORY_ENCHANTMENT_ITEM_TAG_CONTEXT"->"inventory_masters";case "MIXED_WORLDGEN_PREDICATE_CONTEXT"->"mixed_worldgen";default->throw new IllegalArgumentException(family);};}
    public static String executor(String family){return switch(family){case "ENTITY_VARIANT_COMPONENT_CONTEXT"->"Final19VariantsGameTest";case "DUAL_ITEM_BLOCK_TAG_CONTEXT"->"Final19DualTagsGameTest";case "INVENTORY_ENCHANTMENT_ITEM_TAG_CONTEXT"->"Final19InventoryMastersGameTest";case "MIXED_WORLDGEN_PREDICATE_CONTEXT"->"Final19MixedWorldgenGameTest";default->throw new IllegalArgumentException(family);};}
    public static Path temp(String family){return Path.of("build/tmp/final19_implementation/"+prefix(family)+"_temp.json");}
    public static Path run(String family){return Path.of("build/tmp/final19_implementation/"+prefix(family)+"_run.json");}
    public static Path persistent(String family){return Final19StaticContext.RESOURCES.resolve(family.toLowerCase(Locale.ROOT)+"_evidence.json");}
    public static JsonObject catalog(Path root,String family)throws Exception{return Final19WorldgenEvidence.read(root.resolve(Final19StaticContext.RESOURCES).resolve(family.toLowerCase(Locale.ROOT)+"_catalog.json"));}
    public static List<JsonObject> rows(Path root,String family,boolean exact)throws Exception {
        List<JsonObject> rows=new ArrayList<>();for(var value:catalog(root,family).getAsJsonArray("cases")){var row=value.getAsJsonObject();String id=row.get("advancementId").getAsString(),criterion=row.get("criterion").getAsString();boolean canary=switch(family){case "ENTITY_VARIANT_COMPONENT_CONTEXT"->criterion.equals("minecraft:black")||criterion.equals("minecraft:warm")||criterion.equals("minecraft:pale");case "DUAL_ITEM_BLOCK_TAG_CONTEXT"->id.endsWith("/happy_birthday")||id.endsWith("/wax_off");case "INVENTORY_ENCHANTMENT_ITEM_TAG_CONTEXT"->(id.endsWith("/master_armorer")&&row.get("requirementGroup").getAsInt()==0)||id.endsWith("/master_axeman");case "MIXED_WORLDGEN_PREDICATE_CONTEXT"->true;default->throw new IllegalArgumentException(family);};if(exact||canary)rows.add(row);}return rows;
    }
    public static String fingerprint(Path root,String family)throws Exception {
        StringBuilder data=new StringBuilder(Final19StaticContext.inputFingerprint(root,family));
        for(String path:List.of("tools/final19/java/com/diskree/achievetodo/certification/Final19FamilyEvidence.java","tools/final19/gametest/com/diskree/achievetodo/certification/Final19NativeActors.java","tools/final19/gametest/com/diskree/achievetodo/certification/"+executor(family)+".java","src/test/resources/phase_a_certification/runtime_test_matrix.json"))data.append(path).append(':').append(Final19StaticContext.sha(Files.readAllBytes(root.resolve(path))));
        return Final19StaticContext.sha(data.toString().getBytes(StandardCharsets.UTF_8));
    }
    public static String begin(Path root,String family,boolean exact)throws Exception {
        require(!Files.exists(root.resolve(persistent(family))),"Family already accepted");var gate=Final19WorldgenEvidence.read(root.resolve("build/tmp/final19_implementation/"+prefix(family)+"_static.json"));require(Final19StaticContext.inputFingerprint(root,family).equals(gate.get("inputFingerprint").getAsString()),"Missing/stale typed static gate");
        var catalog=catalog(root,family);
        try(var frozen=new ZipFile(root.resolve("reference/phase_a_preservation/files/final/bacap.zip").toFile());var runtime=new ZipFile(root.resolve("build/run/gameTest/world/datapacks/bacap.zip").toFile())) {
            for(var value:catalog.getAsJsonArray("sources")){var source=value.getAsJsonObject();String path=source.get("sourcePath").getAsString();byte[] bytes;try(var in=frozen.getInputStream(frozen.getEntry(path))){bytes=in.readAllBytes();}require(Final19StaticContext.sha(bytes).equals(source.get("frozenSha256").getAsString()),"Frozen drift");Final19StaticContext.validateExact(source,Final19StaticContext.convert(new String(bytes,StandardCharsets.UTF_8)));try(var in=runtime.getInputStream(runtime.getEntry(path))){Final19StaticContext.validateExact(source,JsonParser.parseString(new String(in.readAllBytes(),StandardCharsets.UTF_8)).getAsJsonObject());}}
        }
        String runId=UUID.randomUUID().toString();JsonObject artifact=new JsonObject();artifact.addProperty("family",family);artifact.addProperty("runId",runId);artifact.addProperty("exact",exact);artifact.addProperty("fingerprint",fingerprint(root,family));artifact.add("entries",new JsonArray());Final19WorldgenEvidence.write(root.resolve(temp(family)),artifact);var state=artifact.deepCopy();state.remove("entries");state.addProperty("expectedEntries",rows(root,family,exact).size());state.addProperty("runtimeCopySha256",Final19StaticContext.sha(Files.readAllBytes(root.resolve("build/run/gameTest/world/datapacks/bacap.zip"))));state.addProperty("stage","RUNNING");Final19WorldgenEvidence.write(root.resolve(run(family)),state);return runId;
    }
    public static void append(Path root,String family,JsonObject receipt)throws Exception{var artifact=Final19WorldgenEvidence.read(root.resolve(temp(family)));require(artifact.get("runId").equals(receipt.get("runId")),"Receipt run mismatch");artifact.getAsJsonArray("entries").add(receipt);Final19WorldgenEvidence.write(root.resolve(temp(family)),artifact);}
    public static JsonObject validate(Path root,String family,Path path,boolean exact)throws Exception {
        var artifact=Final19WorldgenEvidence.read(root.resolve(path));require(artifact.get("family").getAsString().equals(family)&&artifact.get("exact").getAsBoolean()==exact,"Wrong family/mode");require(fingerprint(root,family).equals(artifact.get("fingerprint").getAsString()),"Stale family fingerprint");Map<String,JsonObject> expected=new TreeMap<>();for(var row:rows(root,family,exact))expected.put(key(row),row);Set<String> seen=new TreeSet<>(),players=new HashSet<>();
        for(var value:artifact.getAsJsonArray("entries")){var receipt=value.getAsJsonObject();String key=key(receipt);require(expected.containsKey(key)&&seen.add(key),"Unknown/duplicate exact group");var row=expected.get(key);require(receipt.get("criterion").equals(row.get("criterion")),"Wrong selected criterion");require(receipt.get("runId").equals(artifact.get("runId"))&&players.add(receipt.get("playerUuid").getAsString()),"Wrong run/reused actor");require(!receipt.get("criterionBefore").getAsBoolean()&&receipt.get("criterionAfter").getAsBoolean(),"No native progress transition");require("SURVIVAL".equals(receipt.get("gameMode").getAsString()),"Wrong game mode");for(String field:List.of("joined","connectionRegistered","clientLoaded","finiteMaterials","groupSatisfied","noDirectTrigger","noManualAward"))truth(receipt,field);var clean=receipt.getAsJsonObject("cleanup");for(String field:List.of("playerRemoved","connectionRemoved","channelSettled","fixtureEntitiesRemoved","blocksRestored"))truth(clean,field);
            switch(family){case "ENTITY_VARIANT_COMPONENT_CONTEXT"->variants(row,receipt);case "DUAL_ITEM_BLOCK_TAG_CONTEXT"->dualTags(row,receipt);case "INVENTORY_ENCHANTMENT_ITEM_TAG_CONTEXT"->masters(row,receipt);case "MIXED_WORLDGEN_PREDICATE_CONTEXT"->mixed(row,receipt);default->throw new IllegalArgumentException(family);}
        }
        require(seen.equals(expected.keySet()),"Missing exact requirement groups");if(path.equals(temp(family))){var state=Final19WorldgenEvidence.read(root.resolve(run(family)));require(state.get("runId").equals(artifact.get("runId"))&&state.get("fingerprint").equals(artifact.get("fingerprint"))&&state.get("expectedEntries").getAsInt()==seen.size(),"TEMP/run-state mismatch");}return artifact;
    }
    static void variants(JsonObject row,JsonObject receipt){var components=row.getAsJsonObject("expectedCriterion").getAsJsonObject("conditions").getAsJsonArray("entity").get(0).getAsJsonObject().getAsJsonObject("predicate").getAsJsonObject("components");require(components.size()==1,"Wrong variant dimensions");var component=components.entrySet().iterator().next();require(component.getValue().equals(receipt.get("observedVariant")),"Wrong actual variant");String species=component.getKey().split(":")[1].split("/")[0];require(receipt.get("observedSpecies").getAsString().equals("minecraft:"+species),"Wrong actual species");truth(receipt,"wrongVariantNegative");require(!component.getValue().equals(receipt.get("wrongObservedVariant"))&&receipt.get("negativeResourceConsumed").getAsInt()>0,"Unexecuted wrong-variant control");truth(receipt,"nativeInteraction");require(receipt.get("resourceConsumed").getAsInt()>0&&receipt.get("resourceConsumed").getAsInt()<=64,"Missing finite native consumption");if(species.equals("frog")){require(!receipt.get("leashedBefore").getAsBoolean(),"Pre-leashed fixture");truth(receipt,"leashedToJoinedPlayer");}else{require(!receipt.get("tamedBefore").getAsBoolean(),"Pre-tamed fixture");truth(receipt,"tamedAfter");truth(receipt,"ownedByJoinedPlayer");}}
    static void dualTags(JsonObject row,JsonObject receipt){truth(receipt,"itemTagMember");truth(receipt,"blockTagMember");truth(receipt,"nativeMutation");truth(receipt,"wrongItemNegative");truth(receipt,"noOpNegative");truth(receipt,"productionGateUnlocked");var terms=row.getAsJsonObject("expectedCriterion").getAsJsonObject("conditions").getAsJsonArray("location");String blockTag=null,itemTag=null;for(var term:terms){var t=term.getAsJsonObject();if(t.get("condition").getAsString().equals("minecraft:match_tool"))itemTag=t.getAsJsonObject("predicate").get("items").getAsString();else blockTag=t.getAsJsonObject("predicate").getAsJsonObject("block").get("blocks").getAsString();}require(receipt.get("checkedItemTag").getAsString().equals(itemTag)&&receipt.get("checkedBlockTag").getAsString().equals(blockTag),"Wrong tag dimensions");require(!receipt.get("blockBefore").equals(receipt.get("blockAfter"))||!receipt.get("itemBefore").equals(receipt.get("itemAfter")),"No independently observed state mutation");}
    static void masters(JsonObject row,JsonObject receipt){truth(receipt,"itemTagMember");truth(receipt,"supportedEnchantments");truth(receipt,"compatibleEnchantments");truth(receipt,"nativePickup");truth(receipt,"missingEnchantmentNegative");truth(receipt,"underlevelNegative");var spec=row.getAsJsonObject("expectedCriterion").getAsJsonObject("conditions").getAsJsonArray("items").get(0).getAsJsonObject();require(spec.get("items").equals(receipt.get("checkedItemTag")),"Wrong inventory tag");JsonObject actual=receipt.getAsJsonObject("observedEnchantments");for(var value:spec.getAsJsonObject("predicates").getAsJsonArray("enchantments")){var enchant=value.getAsJsonObject();String id=enchant.getAsJsonArray("enchantments").get(0).getAsString();require(actual.has(id),"Missing actual enchantment");int level=actual.get(id).getAsInt();var levels=enchant.getAsJsonObject("levels");require(level>0&&(levels==null||(!levels.has("min")||level>=levels.get("min").getAsInt())&&(!levels.has("max")||level<=levels.get("max").getAsInt())),"Underlevel actual enchantment");}require(receipt.get("inventoryCount").getAsInt()==1,"Wrong finite pickup count");}
    static void mixed(JsonObject row,JsonObject receipt){truth(receipt,"wrongContextNegative");truth(receipt,"nativeEvent");if(row.get("advancementId").getAsString().endsWith("/boatception")){truth(receipt,"boatTagMember");truth(receipt,"vehicleStructurePresent");truth(receipt,"nativeMount");require(Set.of("minecraft:shipwreck","minecraft:shipwreck_beached").contains(receipt.get("observedStructure").getAsString()),"Wrong vehicle structure");require(receipt.get("observedVehicle").getAsString().contains("boat"),"Wrong vehicle");}else{require(Set.of("minecraft:deep_ocean","minecraft:deep_lukewarm_ocean","minecraft:deep_cold_ocean","minecraft:deep_frozen_ocean").contains(receipt.get("observedBiome").getAsString()),"Wrong deep-ocean biome");require(receipt.get("observedSteppingBlock").getAsString().equals("minecraft:frosted_ice"),"Wrong stepped-on block");truth(receipt,"legalFrostWalkerBoots");truth(receipt,"nativeWaterToFrostedIce");truth(receipt,"wrongBootsNegative");truth(receipt,"wrongIceNegative");truth(receipt,"spectatorNegative");truth(receipt.getAsJsonObject("cleanup"),"biomeRestored");}}
    public static void complete(Path root,String family,boolean exact)throws Exception{validate(root,family,temp(family),exact);var state=Final19WorldgenEvidence.read(root.resolve(run(family)));state.addProperty("stage",exact?"TEMP_PROMOTABLE":"TEMP_DIAGNOSTIC");Final19WorldgenEvidence.write(root.resolve(run(family)),state);}
    public static String key(JsonObject row){return row.get("advancementId").getAsString()+"#"+row.get("requirementGroup").getAsInt();}
    public static void truth(JsonObject object,String field){require(object.has(field)&&object.get(field).getAsBoolean(),"Failed observed witness "+field);}
}
