package com.diskree.achievetodo.certification;
import com.diskree.achievetodo.client.ExternalPack;
import com.diskree.achievetodo.client.ExternalPackCompatibility;
import com.google.gson.*;
import com.mojang.serialization.JsonOps;
import net.minecraft.advancements.predicates.entity.RaiderPredicate;
import org.junit.jupiter.api.Test;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.net.*;
import java.util.*;
import java.util.zip.*;
import java.io.*;
import static org.junit.jupiter.api.Assertions.*;
/** Isolated review-only candidate; never changes production or active runtime packs. */
class Final19RaiderProposalTest {
    static final Path ROOT=Path.of("").toAbsolutePath();static final String CLASS="com.diskree.achievetodo.client.ExternalPackCompatibility";
    static class Candidate implements AutoCloseable{
        final URLClassLoader loader;final Class<?> type;
        Candidate()throws Exception{loader=new URLClassLoader(new URL[]{ROOT.resolve("build/tmp/final19_implementation/raider_proposal_classes").toUri().toURL()},Final19RaiderProposalTest.class.getClassLoader()){@Override protected Class<?> loadClass(String name,boolean resolve)throws ClassNotFoundException{if(name.equals(CLASS)||name.startsWith(CLASS+"$")){synchronized(getClassLoadingLock(name)){Class<?> c=findLoadedClass(name);if(c==null)c=findClass(name);if(resolve)resolveClass(c);return c;}}return super.loadClass(name,resolve);}};type=Class.forName(CLASS,true,loader);assertNotSame(ExternalPackCompatibility.class,type);}
        String convert(String input)throws Exception{return conversion(type,input);}
        boolean compatible(Path path,ExternalPack pack)throws Exception{return (boolean)type.getMethod("isCompatibleWorldCopy",Path.class,ExternalPack.class).invoke(null,path,pack);}
        public void close()throws Exception{loader.close();}
    }
    static String conversion(Class<?> type,String input)throws Exception{var method=type.getDeclaredMethod("convertJson",String.class);method.setAccessible(true);var result=method.invoke(null,input);var text=result.getClass().getDeclaredMethod("text");text.setAccessible(true);return (String)text.invoke(result);}
    static String current(String input)throws Exception{return conversion(ExternalPackCompatibility.class,input);}
    static void find(JsonElement value,String key,List<JsonObject> found){if(value.isJsonObject())for(var e:value.getAsJsonObject().entrySet()){if(e.getKey().equals(key))found.add(e.getValue().getAsJsonObject());else find(e.getValue(),key,found);}else if(value.isJsonArray())for(var e:value.getAsJsonArray())find(e,key,found);}
    static void repairExpected(JsonElement value){List<JsonObject> objects=new ArrayList<>();find(value,"type_specific/raider",objects);for(var object:objects){if(object.has("hasRaid"))object.add("has_raid",object.remove("hasRaid"));if(object.has("isCaptain"))object.add("is_captain",object.remove("isCaptain"));}}
    static RaiderPredicate decode(JsonObject value){return RaiderPredicate.CODEC.parse(JsonOps.INSTANCE,value).result().orElseThrow();}
    @Test void everyCanonicalAndFrozenDefinitionHasExactBoundedOutputDiffAndRealBooleanSemantics()throws Exception{
        PhaseACertification.bootstrapMinecraft();JsonObject output=new JsonObject(),outputs=new JsonObject();Set<String> changed=new TreeSet<>();int all=0,canonical=0,raider=0,changedBooleans=0;var ledger=Final19WorldgenEvidence.read(ROOT.resolve("reference/phase_a_planning/final19/product_ledger.json"));Set<String> canonicalPaths=new HashSet<>();for(var entry:ledger.getAsJsonArray("entries"))canonicalPaths.add(entry.getAsJsonObject().get("sourcePath").getAsString());
        try(var candidate=new Candidate();var zip=new ZipFile(ROOT.resolve("reference/phase_a_preservation/files/final/bacap.zip").toFile())){for(var entry:Collections.list(zip.entries())){String name=entry.getName();if(!name.startsWith("data/")||!name.contains("/advancement/")||!name.endsWith(".json"))continue;String raw;try(var in=zip.getInputStream(entry)){raw=new String(in.readAllBytes(),StandardCharsets.UTF_8);}String before=current(raw),after=candidate.convert(raw);JsonObject beforeJson=JsonParser.parseString(before).getAsJsonObject(),afterJson=JsonParser.parseString(after).getAsJsonObject();if(!before.equals(after))changed.add(name);var expected=beforeJson.deepCopy();repairExpected(expected);assertEquals(expected,afterJson,name);assertEquals(after,candidate.convert(after),"Candidate not idempotent: "+name);List<JsonObject> oldFields=new ArrayList<>(),newFields=new ArrayList<>();find(beforeJson,"type_specific/raider",oldFields);find(afterJson,"type_specific/raider",newFields);assertEquals(oldFields.size(),newFields.size());for(int i=0;i<newFields.size();i++){var proposed=newFields.get(i);var legacy=oldFields.get(i).deepCopy();if(legacy.has("hasRaid"))legacy.add("has_raid",legacy.remove("hasRaid"));if(legacy.has("isCaptain"))legacy.add("is_captain",legacy.remove("isCaptain"));assertEquals(decode(legacy),decode(proposed));if(!decode(oldFields.get(i)).equals(decode(proposed)))changedBooleans++;assertFalse(proposed.has("hasRaid")||proposed.has("isCaptain"));raider++;}JsonObject hashes=new JsonObject();hashes.addProperty("frozenSha256",Final19StaticContext.sha(raw.getBytes(StandardCharsets.UTF_8)));hashes.addProperty("currentOutputSha256",Final19StaticContext.sha(before.getBytes(StandardCharsets.UTF_8)));hashes.addProperty("proposedOutputSha256",Final19StaticContext.sha(after.getBytes(StandardCharsets.UTF_8)));outputs.add(name,hashes);all++;if(canonicalPaths.contains(name))canonical++;}}
        assertEquals(1229,all);assertEquals(1152,canonical);assertEquals(Set.of("data/minecraft/advancement/adventure/voluntary_exile.json","data/blazeandcave/advancement/adventure/feeling_ill.json","data/blazeandcave/advancement/monsters/dungeon_crawler.json"),changed);assertEquals(9,raider);assertEquals(6,changedBooleans);output.addProperty("proposalOnly",true);output.addProperty("certificationGain",0);output.addProperty("canonicalDefinitionsCompared",canonical);output.addProperty("allFrozenDefinitionsCompared",all);output.addProperty("raiderPredicatesCompared",raider);output.addProperty("correctedDecodedBooleanPredicates",changedBooleans);output.add("changedDefinitions",new Gson().toJsonTree(changed));output.add("outputFingerprints",outputs);Final19WorldgenEvidence.write(ROOT.resolve("reference/phase_a_planning/final19/raider_proposal_output_scope.json"),output);
    }
    @Test void omittedFalseTrueAndUnrelatedTypeFieldsRemainPreciselyScoped()throws Exception{PhaseACertification.bootstrapMinecraft();try(var candidate=new Candidate()){for(String fields:List.of("","\"has_raid\":false","\"has_raid\":true","\"is_captain\":false","\"is_captain\":true","\"has_raid\":true,\"is_captain\":true")){String raw="{\"criteria\":{\"x\":{\"trigger\":\"minecraft:player_killed_entity\",\"conditions\":{\"entity\":{\"type_specific\":{\"type\":\"raider\""+(fields.isEmpty()?"":","+fields)+"}}}}}}";var converted=JsonParser.parseString(candidate.convert(raw));List<JsonObject> objects=new ArrayList<>();find(converted,"type_specific/raider",objects);assertEquals(1,objects.size());var expected=JsonParser.parseString("{"+fields+"}").getAsJsonObject();assertEquals(decode(expected),decode(objects.getFirst()));assertEquals(candidate.convert(raw),candidate.convert(candidate.convert(raw)));}for(String raw:List.of("{\"has_raid\":true,\"is_captain\":true}","{\"criteria\":{\"x\":{\"trigger\":\"minecraft:location\",\"conditions\":{\"player\":{\"type_specific\":{\"type\":\"minecraft:player\",\"gamemode\":\"survival\"}}}}}}"))assertEquals(current(raw),candidate.convert(raw));}}
    static Properties marker(ExternalPack pack)throws Exception{var result=new Properties();result.setProperty("version","compat_26_2_r15");result.setProperty("fileName",pack.getFileName());result.setProperty("sourceSha1",pack.getSha1());var method=ExternalPackCompatibility.class.getDeclaredMethod("currentRootOverrideSha1");method.setAccessible(true);result.setProperty("rootOverrideSha1",(String)method.invoke(null));result.setProperty("llamaCarpetNbtMapping","equipment.body");return result;}
    static Path markerPack(String name,Properties properties)throws Exception{Path path=ROOT.resolve("build/tmp/final19_implementation/raider_proposal_"+name+".zip");try(var zip=new ZipOutputStream(Files.newOutputStream(path))){zip.putNextEntry(new ZipEntry("achievetodo_compatibility/compat_26_2.properties"));var bytes=new ByteArrayOutputStream();properties.store(bytes,null);zip.write(bytes.toByteArray());zip.closeEntry();}return path;}
    @Test void candidateRejectsPreFixR15AndRetainsSourceRootAndLlamaFreshnessGuards()throws Exception{try(var candidate=new Candidate()){var legacy=marker(ExternalPack.BACAP);Path old=markerPack("legacy",legacy);assertTrue(ExternalPackCompatibility.isCompatibleWorldCopy(old,ExternalPack.BACAP));assertFalse(candidate.compatible(old,ExternalPack.BACAP));var fresh=marker(ExternalPack.BACAP);fresh.setProperty("raiderPredicateKeys","snake_case");assertTrue(candidate.compatible(markerPack("fresh",fresh),ExternalPack.BACAP));for(String property:List.of("raiderPredicateKeys","sourceSha1","rootOverrideSha1","llamaCarpetNbtMapping","version","fileName")){var wrong=new Properties();wrong.putAll(fresh);wrong.setProperty(property,"wrong");assertFalse(candidate.compatible(markerPack("wrong_"+property,wrong),ExternalPack.BACAP));}var other=marker(ExternalPack.BACAP_HARDCORE);Path otherPath=markerPack("other",other);assertEquals(ExternalPackCompatibility.isCompatibleWorldCopy(otherPath,ExternalPack.BACAP_HARDCORE),candidate.compatible(otherPath,ExternalPack.BACAP_HARDCORE));}}
    @Test void proposedWriterEmitsExactBacapFreshnessPropertyWithoutChangingOtherMarkers()throws Exception{try(var candidate=new Candidate()){var method=candidate.type.getDeclaredMethod("writeCompatibilityMarker",ZipOutputStream.class,ExternalPack.class);method.setAccessible(true);for(var pack:List.of(ExternalPack.BACAP,ExternalPack.BACAP_HARDCORE)){var output=new ByteArrayOutputStream();try(var zip=new ZipOutputStream(output)){method.invoke(null,zip,pack);}var properties=new Properties();try(var zip=new ZipInputStream(new ByteArrayInputStream(output.toByteArray()))){assertEquals("achievetodo_compatibility/compat_26_2.properties",zip.getNextEntry().getName());properties.load(zip);}assertEquals("compat_26_2_r15",properties.getProperty("version"));assertEquals(pack.getFileName(),properties.getProperty("fileName"));assertEquals(pack.getSha1(),properties.getProperty("sourceSha1"));assertEquals(marker(pack).getProperty("rootOverrideSha1"),properties.getProperty("rootOverrideSha1"));if(pack==ExternalPack.BACAP){assertEquals("equipment.body",properties.getProperty("llamaCarpetNbtMapping"));assertEquals("snake_case",properties.getProperty("raiderPredicateKeys"));}else assertNull(properties.getProperty("raiderPredicateKeys"));}}}
    @Test void productionBytesAndAppliedCauldronAxeAuthorizationsRemainUntouched()throws Exception{assertEquals("dffeb7c2cf6685c5f689cf2a205b435b81da5b524971103804de3e3a6ae1dc11",Final19StaticContext.sha(Files.readAllBytes(ROOT.resolve("src/main/java/com/diskree/achievetodo/client/ExternalPackCompatibility.java"))));for(var e:Final19CauldronGateRegressionAcceptanceTest.HASHES.entrySet())assertEquals(e.getValue(),Final19StaticContext.sha(Files.readAllBytes(ROOT.resolve(e.getKey()))));}
}
