package com.diskree.achievetodo.certification;
import com.google.gson.*;
import org.junit.jupiter.api.Test;
import java.nio.file.*;
import static org.junit.jupiter.api.Assertions.*;
class Final19MixedWorldgenAcceptanceTest {
    static final String FAMILY="MIXED_WORLDGEN_PREDICATE_CONTEXT";static final Path ROOT=Path.of("").toAbsolutePath();
    static Path path(){return Files.exists(ROOT.resolve(Final19FamilyEvidence.persistent(FAMILY)))?Final19FamilyEvidence.persistent(FAMILY):Final19FamilyEvidence.temp(FAMILY);}
    static void independent(JsonObject a){for(var value:a.getAsJsonArray("entries")){var r=value.getAsJsonObject();assertTrue(r.getAsJsonObject("cleanup").get("structureRestored").getAsBoolean());if(r.get("criterion").getAsString().equals("boatception")){assertEquals("minecraft:spruce_boat",r.get("observedVehicle").getAsString());assertEquals("minecraft:shipwreck",r.get("observedStructure").getAsString());assertEquals("OWNED_REGISTERED_STRUCTURE_START_PIECE_AND_REFERENCE",r.get("structureFixtureSource").getAsString());assertTrue(r.get("nativeBoundary").getAsString().startsWith("ServerboundInteractPacket.handle"));}else{assertTrue(r.get("nativeBoundary").getAsString().startsWith("ServerboundMovePlayerPacket.handle"));assertEquals("minecraft:leather_boots",r.get("observedBoots").getAsString());assertEquals(2,r.get("observedFrostWalkerLevel").getAsInt());assertEquals("Block{minecraft:water}[level=0]",r.get("waterBefore").getAsString());assertTrue(r.get("iceAfter").getAsString().startsWith("Block{minecraft:frosted_ice}"));assertTrue(r.getAsJsonObject("cleanup").get("biomeRestored").getAsBoolean());var controls=r.getAsJsonObject("negativeObservations");assertEquals(java.util.Set.of("wrongBiome","wrongBoots","wrongIce","spectator"),controls.keySet());for(var control:controls.entrySet()){var observed=control.getValue().getAsJsonObject();assertFalse(observed.get("criterion").getAsBoolean());assertEquals(25,observed.get("observedTicks").getAsInt());}assertEquals("minecraft:the_void",controls.getAsJsonObject("wrongBiome").get("biome").getAsString());assertTrue(controls.getAsJsonObject("wrongBoots").get("bootsEmpty").getAsBoolean());assertEquals("minecraft:ice",controls.getAsJsonObject("wrongIce").get("steppingBlock").getAsString());assertEquals("SPECTATOR",controls.getAsJsonObject("spectator").get("gameMode").getAsString());}}}
    @Test void bothActualNativeWorldgenCombinationGroupsPass()throws Exception{var a=Final19FamilyEvidence.validate(ROOT,FAMILY,path(),true);assertEquals(2,a.getAsJsonArray("entries").size());independent(a);}
    @Test void missingDuplicateStaleFalseStructureIllegalBootsMissingNativeFreezeAndNegativesAreRejected()throws Exception{var original=Final19WorldgenEvidence.read(ROOT.resolve(path()));Path scratch=Path.of("build/tmp/final19_implementation/mixed_worldgen_mutated.json");for(int i=0;i<9;i++){var a=original.deepCopy();var entries=a.getAsJsonArray("entries");var boat=entries.get(0).getAsJsonObject();var frost=entries.get(1).getAsJsonObject();switch(i){case 0->entries.remove(0);case 1->entries.add(boat.deepCopy());case 2->a.addProperty("fingerprint","stale");case 3->boat.addProperty("vehicleStructurePresent",false);case 4->frost.addProperty("observedFrostWalkerLevel",10);case 5->frost.addProperty("waterBefore","Block{minecraft:frosted_ice}[age=0]");case 6->frost.addProperty("spectatorNegative",false);case 7->frost.getAsJsonObject("cleanup").addProperty("biomeRestored",false);case 8->boat.getAsJsonObject("cleanup").addProperty("structureRestored",false);}Final19WorldgenEvidence.write(ROOT.resolve(scratch),a);assertThrows(Throwable.class,()->{independent(a);Final19FamilyEvidence.validate(ROOT,FAMILY,scratch,true);});}}
}
