package com.diskree.achievetodo.certification;
import com.google.gson.*;
import org.junit.jupiter.api.Test;
import net.minecraft.core.*;
import net.minecraft.core.registries.*;
import net.minecraft.data.registries.VanillaRegistries;
import net.minecraft.resources.*;
import net.minecraft.world.item.*;
import net.minecraft.world.item.enchantment.Enchantment;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
class Final19InventoryMastersStaticTest {
    static final String FAMILY="INVENTORY_ENCHANTMENT_ITEM_TAG_CONTEXT";final Path root=Path.of("").toAbsolutePath();
    @Test void all35FrozenBranchesHaveTypedTagContextAndLegalSupportedCompatibleWitnesses()throws Exception{try(var context=new Final19StaticContext(root,FAMILY)){var result=context.validate(FAMILY);assertEquals(35,result.get("criteriaCount").getAsInt());assertEquals(9,result.get("requirementGroupCount").getAsInt());var registry=VanillaRegistries.createLookup().lookupOrThrow(Registries.ENCHANTMENT);int witnesses=0;for(var source:context.catalog(FAMILY).getAsJsonArray("sources"))for(var criterion:source.getAsJsonObject().getAsJsonObject("auditedConvertedDefinition").getAsJsonObject("criteria").entrySet()){var spec=criterion.getValue().getAsJsonObject().getAsJsonObject("conditions").getAsJsonArray("items").get(0).getAsJsonObject();var members=result.getAsJsonObject("sourceBackedTags").getAsJsonObject("minecraft:item|"+spec.get("items").getAsString().substring(1)).getAsJsonArray("resolvedMembers");boolean legal=false;for(var member:members){var item=BuiltInRegistries.ITEM.getValue(Identifier.parse(member.getAsString())).builtInRegistryHolder();List<Holder<Enchantment>> holders=new ArrayList<>();boolean valid=true;for(var value:spec.getAsJsonObject("predicates").getAsJsonArray("enchantments")){var e=value.getAsJsonObject();var holder=registry.getOrThrow(ResourceKey.create(Registries.ENCHANTMENT,Identifier.parse(e.getAsJsonArray("enchantments").get(0).getAsString())));int level=e.getAsJsonObject("levels").get("min").getAsInt();valid&=sourceContains(root,"item",sourceDefinition(root,idOf(holder)).get("supported_items").getAsString(),member.getAsString())&&level>0&&level<=holder.value().getMaxLevel();for(var previous:holders)valid&=!sourceContains(root,"enchantment",sourceDefinition(root,idOf(holder)).get("exclusive_set"),idOf(previous))&&!sourceContains(root,"enchantment",sourceDefinition(root,idOf(previous)).get("exclusive_set"),idOf(holder));holders.add(holder);}legal|=valid;}assertTrue(legal,criterion.getKey());witnesses++;}assertEquals(35,witnesses);result.addProperty("legalBranchWitnesses",witnesses);result.addProperty("inputFingerprint",Final19StaticContext.inputFingerprint(root,FAMILY));Final19WorldgenEvidence.write(root.resolve("build/tmp/final19_implementation/inventory_masters_static.json"),result);}}
    static String idOf(Holder<Enchantment> holder){return holder.unwrapKey().orElseThrow().identifier().toString();}
    static JsonObject sourceDefinition(Path root,String id)throws Exception{try(var zip=new java.util.zip.ZipFile(root.resolve(".gradle-user-home/caches/fabric-loom/minecraftMaven/net/minecraft/minecraft-merged-deobf/26.2/minecraft-merged-deobf-26.2.jar").toFile())){var key=Identifier.parse(id);try(var in=zip.getInputStream(zip.getEntry("data/"+key.getNamespace()+"/enchantment/"+key.getPath()+".json"))){return JsonParser.parseString(new String(in.readAllBytes(),java.nio.charset.StandardCharsets.UTF_8)).getAsJsonObject();}}}
    static boolean sourceContains(Path root,String registry,JsonElement selector,String id)throws Exception{if(selector==null||selector.isJsonNull())return false;if(selector.isJsonArray()){for(var value:selector.getAsJsonArray())if(sourceContains(root,registry,value,id))return true;return false;}return sourceContains(root,registry,selector.getAsString(),id);}
    static boolean sourceContains(Path root,String registry,String selector,String id)throws Exception{if(!selector.startsWith("#"))return selector.equals(id);var key=Identifier.parse(selector.substring(1));try(var zip=new java.util.zip.ZipFile(root.resolve(".gradle-user-home/caches/fabric-loom/minecraftMaven/net/minecraft/minecraft-merged-deobf/26.2/minecraft-merged-deobf-26.2.jar").toFile())){try(var in=zip.getInputStream(zip.getEntry("data/"+key.getNamespace()+"/tags/"+registry+"/"+key.getPath()+".json"))){var tag=JsonParser.parseString(new String(in.readAllBytes(),java.nio.charset.StandardCharsets.UTF_8)).getAsJsonObject();for(var value:tag.getAsJsonArray("values"))if(sourceContains(root,registry,value.isJsonObject()?value.getAsJsonObject().get("id").getAsString():value.getAsString(),id))return true;return false;}}}
    @Test void deletedTagsConjunctionAndOrderedGroupsRemainRejected()throws Exception{try(var context=new Final19StaticContext(root,FAMILY)){for(var value:context.catalog(FAMILY).getAsJsonArray("sources")){var source=value.getAsJsonObject();for(int mutation=0;mutation<3;mutation++){var bad=source.getAsJsonObject("auditedConvertedDefinition").deepCopy();var spec=bad.getAsJsonObject("criteria").entrySet().iterator().next().getValue().getAsJsonObject().getAsJsonObject("conditions").getAsJsonArray("items").get(0).getAsJsonObject();if(mutation==0){spec.addProperty("items","#minecraft:no_such_master_tag");assertThrows(RuntimeException.class,()->context.parse(bad));}if(mutation==1)spec.getAsJsonObject("predicates").getAsJsonArray("enchantments").remove(0);if(mutation==2)bad.add("requirements",new JsonArray());assertThrows(RuntimeException.class,()->Final19StaticContext.validateExact(source,bad));}}}}
}
