package com.diskree.achievetodo.certification;
import com.diskree.achievetodo.client.*;
import com.google.gson.*;
import org.junit.jupiter.api.Test;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.net.*;
import java.util.*;
import java.util.zip.*;
import java.io.*;
import static org.junit.jupiter.api.Assertions.*;
/** Real authorized production converter and normal copy pipeline. Old classes are comparison only. */
class Final19RaiderProductionTest {
 static final Path ROOT=Path.of("").toAbsolutePath();
 static final String PRE="dffeb7c2cf6685c5f689cf2a205b435b81da5b524971103804de3e3a6ae1dc11",POST="1bea3ba9caf22963d1ef26de69b19534a4b16d1eab85a39c5e1fc17750227a31";
 static URLClassLoader oldLoader()throws Exception{return new URLClassLoader(new URL[]{ROOT.resolve("build/tmp/final19_implementation/raider_pre_fix_classes").toUri().toURL()},Final19RaiderProductionTest.class.getClassLoader()){@Override protected Class<?> loadClass(String n,boolean r)throws ClassNotFoundException{if(n.equals(Final19RaiderProposalTest.CLASS)||n.startsWith(Final19RaiderProposalTest.CLASS+"$")){synchronized(getClassLoadingLock(n)){Class<?> c=findLoadedClass(n);if(c==null)c=findClass(n);if(r)resolveClass(c);return c;}}return super.loadClass(n,r);}};}
 @Test void realProductionExhaustiveScopeAndCodecSemantics()throws Exception{
  PhaseACertification.bootstrapMinecraft();assertEquals(POST,Final19StaticContext.sha(Files.readAllBytes(ROOT.resolve("src/main/java/com/diskree/achievetodo/client/ExternalPackCompatibility.java"))));assertEquals(PRE,Final19StaticContext.sha(Files.readAllBytes(ROOT.resolve("reference/phase_a_planning/final19/raider_pre_fix_sources/src/main/java/com/diskree/achievetodo/client/ExternalPackCompatibility.java"))));
  var proposal=Final19WorldgenEvidence.read(ROOT.resolve("reference/phase_a_planning/final19/raider_proposal_output_scope.json"));JsonObject proof=new JsonObject(),outputs=new JsonObject();Set<String> changed=new TreeSet<>(),canonicalPaths=new HashSet<>();for(var e:Final19WorldgenEvidence.read(ROOT.resolve("reference/phase_a_planning/final19/product_ledger.json")).getAsJsonArray("entries"))canonicalPaths.add(e.getAsJsonObject().get("sourcePath").getAsString());int all=0,canonical=0,predicates=0,corrected=0;
  try(var loader=oldLoader();var zip=new ZipFile(ROOT.resolve("reference/phase_a_preservation/files/final/bacap.zip").toFile())){var old=Class.forName(Final19RaiderProposalTest.CLASS,true,loader);assertNotSame(old,ExternalPackCompatibility.class);for(var e:Collections.list(zip.entries())){String path=e.getName();if(!path.startsWith("data/")||!path.contains("/advancement/")||!path.endsWith(".json"))continue;String raw;try(var in=zip.getInputStream(e)){raw=new String(in.readAllBytes(),StandardCharsets.UTF_8);}String before=Final19RaiderProposalTest.conversion(old,raw),after=Final19RaiderProposalTest.current(raw);var expected=JsonParser.parseString(before);Final19RaiderProposalTest.repairExpected(expected);assertEquals(expected,JsonParser.parseString(after),path);assertEquals(after,Final19RaiderProposalTest.current(after),path);var reviewed=proposal.getAsJsonObject("outputFingerprints").getAsJsonObject(path);String b=Final19StaticContext.sha(before.getBytes(StandardCharsets.UTF_8)),a=Final19StaticContext.sha(after.getBytes(StandardCharsets.UTF_8));assertEquals(reviewed.get("currentOutputSha256").getAsString(),b);assertEquals(reviewed.get("proposedOutputSha256").getAsString(),a);if(!before.equals(after))changed.add(path);List<JsonObject> olds=new ArrayList<>(),news=new ArrayList<>();Final19RaiderProposalTest.find(JsonParser.parseString(before),"type_specific/raider",olds);Final19RaiderProposalTest.find(JsonParser.parseString(after),"type_specific/raider",news);for(int i=0;i<news.size();i++){var n=news.get(i);assertFalse(n.has("hasRaid")||n.has("isCaptain"));var decoded=Final19RaiderProposalTest.decode(n);if(!decoded.equals(Final19RaiderProposalTest.decode(olds.get(i))))corrected++;if(path.contains("feeling_ill")){assertTrue(decoded.hasRaid());assertFalse(decoded.isCaptain());}if(path.contains("dungeon_crawler")){assertFalse(decoded.hasRaid());assertFalse(decoded.isCaptain());assertTrue(n.has("has_raid"));}if(path.contains("voluntary_exile")){assertTrue(decoded.isCaptain());assertFalse(decoded.hasRaid());assertFalse(n.has("has_raid"));}predicates++;}JsonObject row=new JsonObject();row.addProperty("preFixOutputSha256",b);row.addProperty("productionOutputSha256",a);outputs.add(path,row);all++;if(canonicalPaths.contains(path))canonical++;}}
  assertEquals(1229,all);assertEquals(1152,canonical);assertEquals(9,predicates);assertEquals(6,corrected);assertEquals(Set.of("data/minecraft/advancement/adventure/voluntary_exile.json","data/blazeandcave/advancement/adventure/feeling_ill.json","data/blazeandcave/advancement/monsters/dungeon_crawler.json"),changed);
  proof.addProperty("productionConverterSha256",POST);proof.addProperty("preFixConverterSha256",PRE);proof.addProperty("definitions",all);proof.addProperty("canonicalDefinitions",canonical);proof.addProperty("decodedPredicates",predicates);proof.addProperty("correctedPredicates",corrected);proof.addProperty("allIdempotent",true);proof.addProperty("familiesOneThroughFiveOutputUnchanged",true);proof.addProperty("certificationGain",0);proof.add("changedDefinitions",new Gson().toJsonTree(changed));proof.add("outputFingerprints",outputs);Final19WorldgenEvidence.write(ROOT.resolve("reference/phase_a_planning/final19/raider_production_output_scope.json"),proof);
 }
 @Test void normalPipelineFreshCopyAndStrictFreshnessGuards()throws Exception{
  Path old=ROOT.resolve("reference/phase_a_planning/final19/raider_pre_fix_runtime_copy.zip");var props=readMarker(old);assertNull(props.getProperty("raiderPredicateKeys"));var expected=Final19RaiderProposalTest.marker(ExternalPack.BACAP);for(String k:expected.stringPropertyNames())assertEquals(expected.getProperty(k),props.getProperty(k));assertFalse(ExternalPackCompatibility.isCompatibleWorldCopy(old,ExternalPack.BACAP));
  Path fresh=ROOT.resolve("build/tmp/final19_implementation/raider_fresh_pipeline_bacap.zip");ExternalPackCompatibility.copyForWorld(ROOT.resolve("reference/phase_a_preservation/files/final/bacap.zip"),fresh,ExternalPack.BACAP);assertTrue(ExternalPackCompatibility.isCompatibleWorldCopy(fresh,ExternalPack.BACAP));var marker=readMarker(fresh);for(String k:expected.stringPropertyNames())assertEquals(expected.getProperty(k),marker.getProperty(k));assertEquals("snake_case",marker.getProperty("raiderPredicateKeys"));for(String k:List.of("raiderPredicateKeys","sourceSha1","rootOverrideSha1","llamaCarpetNbtMapping","version","fileName")){var wrong=new Properties();wrong.putAll(marker);wrong.setProperty(k,"wrong");assertFalse(ExternalPackCompatibility.isCompatibleWorldCopy(Final19RaiderProposalTest.markerPack("production_wrong_"+k,wrong),ExternalPack.BACAP));}
  try(var loader=oldLoader()){var oracle=Class.forName(Final19RaiderProposalTest.CLASS,true,loader);for(var otherPack:ExternalPack.values()){if(otherPack==ExternalPack.BACAP)continue;var other=Final19RaiderProposalTest.markerPack("production_other_"+otherPack.name(),Final19RaiderProposalTest.marker(otherPack));assertEquals((boolean)oracle.getMethod("isCompatibleWorldCopy",Path.class,ExternalPack.class).invoke(null,other,otherPack),ExternalPackCompatibility.isCompatibleWorldCopy(other,otherPack));var writer=ExternalPackCompatibility.class.getDeclaredMethod("writeCompatibilityMarker",ZipOutputStream.class,ExternalPack.class);writer.setAccessible(true);var bytes=new ByteArrayOutputStream();try(var out=new ZipOutputStream(bytes)){writer.invoke(null,out,otherPack);}var actual=new Properties();try(var in=new ZipInputStream(new ByteArrayInputStream(bytes.toByteArray()))){in.getNextEntry();actual.load(in);}assertNull(actual.getProperty("raiderPredicateKeys"));assertEquals(otherPack.getFileName(),actual.getProperty("fileName"));assertEquals(otherPack.getSha1(),actual.getProperty("sourceSha1"));assertEquals("compat_26_2_r15",actual.getProperty("version"));}}
  JsonObject evidence=new JsonObject();evidence.addProperty("productionConverterSha256",POST);evidence.addProperty("oldCopySha256",Final19StaticContext.sha(Files.readAllBytes(old)));evidence.addProperty("oldRejectedForMissingRaiderKeys",true);evidence.addProperty("freshCopySha256",Final19StaticContext.sha(Files.readAllBytes(fresh)));evidence.addProperty("normalProductionPipeline",true);evidence.add("marker",new Gson().toJsonTree(marker));evidence.addProperty("allSixStaleGuardsRejected",true);Final19WorldgenEvidence.write(ROOT.resolve("reference/phase_a_planning/final19/raider_runtime_freshness.json"),evidence);
  // Only the already generated production pipeline output is installed into this owned test world.
  Files.copy(fresh,ROOT.resolve("build/run/gameTest/world/datapacks/bacap.zip"),StandardCopyOption.REPLACE_EXISTING);
 }
 static Properties readMarker(Path p)throws Exception{Properties r=new Properties();try(var z=new ZipFile(p.toFile());var in=z.getInputStream(z.getEntry("achievetodo_compatibility/compat_26_2.properties"))){r.load(in);}return r;}
}
