package com.diskree.achievetodo.certification;
import org.junit.jupiter.api.Test;
import java.nio.file.*;
import static org.junit.jupiter.api.Assertions.*;
class Final19CombatAcceptanceTest {
 static Path artifact(String prefix){String family=prefix.equals("raider")?"raider_predicate_key_migration":"skeleton_projectile_block_runtime_proof";var p=Final19CombatEvidence.root().resolve("src/test/resources/final19_certification/"+family+"_evidence.json");return Files.exists(p)?p:Final19CombatEvidence.root().resolve(Final19CombatEvidence.file(prefix,"temp"));}
 static void validate(String prefix)throws Exception{var a=Final19CombatEvidence.validate(artifact(prefix),prefix,true);assertEquals(5,a.getAsJsonArray("entries").size());for(var e:a.getAsJsonArray("entries")){var r=e.getAsJsonObject();if(r.get("criterionAfter").getAsBoolean())assertTrue(r.get("advancementDone").getAsBoolean());}var evidence=new com.google.gson.JsonObject();evidence.addProperty("runId",a.get("runId").getAsString());evidence.addProperty("evidenceSha256",Final19StaticContext.sha(Files.readAllBytes(artifact(prefix))));evidence.addProperty("independentAcceptance","GREEN");Final19WorldgenEvidence.write(Final19CombatEvidence.root().resolve(Final19CombatEvidence.file(prefix,"acceptance")),evidence);}
 static void reject(String prefix)throws Exception{var original=Final19WorldgenEvidence.read(artifact(prefix));var path=Final19CombatEvidence.root().resolve(Final19CombatEvidence.file(prefix,"mutated"));for(int m=0;m<12;m++){var a=original.deepCopy();var entries=a.getAsJsonArray("entries");var r=entries.get(0).getAsJsonObject();switch(m){case 0->entries.remove(0);case 1->entries.add(r.deepCopy());case 2->a.addProperty("fingerprint","stale");case 3->a.addProperty("productionConverterSha256","stale");case 4->r.addProperty("criterionBefore",true);case 5->r.addProperty("criterionAfter",!r.get("criterionAfter").getAsBoolean());case 6->r.addProperty("nativeAction",false);case 7->r.getAsJsonObject("cleanup").addProperty("channelSettled",false);case 8->entries.get(1).getAsJsonObject().add("playerUuid",r.get("playerUuid"));case 9->r.addProperty("noManualAward",false);case 10->{if(prefix.equals("shield"))r.getAsJsonObject("damageWitness").addProperty("liveProjectileOwnerObserved",false);else r.getAsJsonObject("raiderWitness").addProperty("isCaptain",!r.getAsJsonObject("raiderWitness").get("isCaptain").getAsBoolean());}case 11->{if(prefix.equals("shield"))r.getAsJsonObject("damageWitness").addProperty("nativeAiShotObserved",false);else r.getAsJsonObject("decodedPredicate").addProperty("isCaptain",false);}}Final19WorldgenEvidence.write(path,a);assertThrows(Exception.class,()->Final19CombatEvidence.validate(path,prefix,true));}}
 @Test void freshRaiderExactHasCaptainKillAndAllFourNativeNegativeControls()throws Exception{validate("raider");}
 @Test void fakeRaiderControlsAndStaleReceiptsAreRejected()throws Exception{reject("raider");}
}
