package com.diskree.achievetodo.certification;
import org.junit.jupiter.api.Test;
import java.nio.file.*;
import static org.junit.jupiter.api.Assertions.*;
class Final19RaiderIntegrityAcceptanceTest {
 static final Path PERSISTENT=Path.of("src/test/resources/final19_certification/raider_integrity_regression.json");
 @Test void allFiveTrueBranchesAndThreeFalseBranchesHaveNativeRaidAndNonraidControls()throws Exception{Path root=Final19CombatEvidence.root();Path p=Files.exists(root.resolve(PERSISTENT))?root.resolve(PERSISTENT):root.resolve(Final19CombatEvidence.file("raider_integrity","temp"));var a=Final19CombatEvidence.validate(p,"raider_integrity",true);assertEquals(0,a.get("certificationGain").getAsInt());assertEquals(16,a.getAsJsonArray("entries").size());}
 @Test void incompleteStaleFabricatedOrUnrestoredRegressionCannotBeAccepted()throws Exception{Path root=Final19CombatEvidence.root();Path p=Files.exists(root.resolve(PERSISTENT))?root.resolve(PERSISTENT):root.resolve(Final19CombatEvidence.file("raider_integrity","temp"));var a=Final19WorldgenEvidence.read(p);Path bad=root.resolve("build/tmp/final19_implementation/raider_integrity_mutated.json");for(int i=0;i<10;i++){var m=a.deepCopy();var entries=m.getAsJsonArray("entries");var r=entries.get(0).getAsJsonObject();switch(i){case 0->entries.remove(0);case 1->entries.add(r.deepCopy());case 2->m.addProperty("fingerprint","stale");case 3->m.addProperty("productionConverterSha256","stale");case 4->r.addProperty("criterionBefore",true);case 5->r.addProperty("criterionAfter",!r.get("criterionAfter").getAsBoolean());case 6->r.getAsJsonObject("decodedPredicate").addProperty("hasRaid",true);case 7->r.getAsJsonObject("raiderWitness").addProperty("nativeKillCredit",false);case 8->r.getAsJsonObject("cleanup").addProperty("blocksRestored",false);case 9->entries.get(1).getAsJsonObject().add("playerUuid",r.get("playerUuid"));}Final19WorldgenEvidence.write(bad,m);assertThrows(Exception.class,()->Final19CombatEvidence.validate(bad,"raider_integrity",true));}}
}
