package com.diskree.achievetodo.certification;
import com.google.gson.JsonObject;
import com.diskree.achievetodo.AchieveToDoMod;
import com.diskree.achievetodo.ability.AbilityType;
import com.diskree.achievetodo.injection.extension.main.LevelInfoExtension;
import com.mojang.authlib.GameProfile;
import io.netty.channel.embedded.EmbeddedChannel;
import io.netty.util.ReferenceCountUtil;
import net.fabricmc.fabric.api.gametest.v1.*;
import net.minecraft.advancements.AdvancementHolder;
import net.minecraft.core.*;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.*;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.network.Connection;
import net.minecraft.network.chat.Component;
import net.minecraft.network.protocol.PacketFlow;
import net.minecraft.network.protocol.game.*;
import net.minecraft.resources.Identifier;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.*;
import net.minecraft.server.network.CommonListenerCookie;
import net.minecraft.tags.*;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.projectile.Projectile;
import net.minecraft.world.entity.projectile.FishingHook;
import net.minecraft.world.item.*;
import net.minecraft.world.item.alchemy.*;
import net.minecraft.world.item.component.*;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.*;
import java.lang.reflect.Method;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;
/** All weapon groups cross ordinary finite player packet and native collision boundaries. */
public final class PhaseAMixedWeaponryMulticlassedGameTest implements CustomTestMethodInvoker{
    @GameTest(maxTicks=5000)public void mixedWeaponryMulticlassedCanary(GameTestHelper h){run(h,false);}
    @GameTest(maxTicks=5000)public void mixedWeaponryMulticlassedExact17(GameTestHelper h){run(h,true);}
    private static void run(GameTestHelper h,boolean exact){try{String run=PhaseAMixedWeaponryMulticlassedExecutionEvidence.begin(PhaseAMixedWeaponryMulticlassedExecutionEvidence.root(),exact);next(h,PhaseAMixedWeaponryMulticlassedExecutionEvidence.selected(),0,run,exact);}catch(Throwable e){h.fail("Multiclassed start: "+e);}}
    private static void next(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact){
        if(i==rows.size()){try{PhaseAMixedWeaponryMulticlassedEvidenceValidation.load(PhaseAMixedWeaponryMulticlassedExecutionEvidence.root(),PhaseAMixedWeaponryMulticlassedEvidenceValidation.TEMP,exact,true);System.out.println((exact?"TEMP_PROMOTABLE":"TEMP_DIAGNOSTIC")+"=PASS family=MIXED_WEAPONRY_MULTICLASSED runId="+run+" entries="+rows.size());h.succeed();}catch(Throwable e){h.fail("Multiclassed audit: "+e);}return;}
        Context c=new Context(rows.get(i));try{
            var pos=h.absolutePos(new BlockPos(5,2,5));c.area=new AABB(pos).inflate(12);for(var e:h.getLevel().getEntitiesOfClass(Entity.class,c.area))c.baseline.add(e.getUUID());
            for(int x=-4;x<=4;x++)for(int z=-4;z<=6;z++){h.getLevel().setBlockAndUpdate(pos.offset(x,-1,z),Blocks.STONE.defaultBlockState());for(int y=0;y<5;y++)h.getLevel().setBlockAndUpdate(pos.offset(x,y,z),Blocks.AIR.defaultBlockState());}
            c.joined=join(h);var p=c.joined.player();p.setGameMode(GameType.SURVIVAL);new ServerboundPlayerLoadedPacket().handle(p.connection);require(p.connection.hasClientLoaded()&&!p.hasInfiniteMaterials()&&!p.isSpectator(),"Finite joined lifecycle missing");p.teleportTo(pos.getX()+.5,pos.getY(),pos.getZ()+.5);acknowledge(c.joined);p.getInventory().clearContent();
            c.target=(Mob)BuiltInRegistries.ENTITY_TYPE.getValue(Identifier.parse(c.row.get("selectedEntity").getAsString())).create(h.getLevel(),EntitySpawnReason.COMMAND);require(c.target!=null,"Native target missing");c.target.setNoAi(true);c.target.setNoGravity(true);double distance=c.action().equals("MELEE")?2:3;c.target.teleportTo(p.getX(),p.getY(),p.getZ()+distance);require(h.getLevel().addFreshEntity(c.target),"Native target spawn failed");c.health=c.target.getHealth();
            c.tool=new ItemStack(BuiltInRegistries.ITEM.getValue(Identifier.parse(c.row.get("selectedItem").getAsString())));if(c.criterion().endsWith("potion"))c.tool.set(DataComponents.POTION_CONTENTS,new PotionContents(Potions.HARMING));p.setItemInHand(InteractionHand.MAIN_HAND,c.tool);c.damageBefore=c.tool.getDamageValue();
            if(Set.of("BOW","CROSSBOW").contains(c.action())){ItemStack ammo=new ItemStack(c.criterion().equals("firework_rocket")?Items.FIREWORK_ROCKET:Items.ARROW);if(ammo.is(Items.FIREWORK_ROCKET))ammo.set(DataComponents.FIREWORKS,new Fireworks(0,List.of(FireworkExplosion.DEFAULT)));c.ammo=ammo.getItem();p.setItemInHand(InteractionHand.OFF_HAND,ammo);}
            c.advancement=h.getLevel().getServer().getAdvancements().get(Identifier.parse(c.row.get("advancementId").getAsString()));require(c.advancement!=null&&!done(c),"Criterion pre-completed");c.gate=unlock(h,c);h.runAfterDelay(2,()->act(h,rows,i,run,exact,c,2));
        }catch(Throwable e){fail(h,c,"setup",e);}
    }
    private static JsonObject unlock(GameTestHelper h,Context c){var p=c.joined.player();var server=h.getLevel().getServer();var board=server.getScoreboard();var score=board.getObjective("bac_advancements");var settings=board.getObjective("bac_settings");require(score!=null&&settings!=null,"Production scoreboards missing");board.getOrCreatePlayerScore(net.minecraft.world.scores.ScoreHolder.forNameOnly("reward"),settings).set(0);board.getOrCreatePlayerScore(p,score).set(0);var config=((LevelInfoExtension)server.getWorldData().getLevelSettings()).achievetodo$getAbilitiesConfiguration(server.overworld().getSeed());JsonObject gate=new JsonObject(),abilities=new JsonObject();gate.addProperty("thresholdSource","LIVE_OVERWORLD_SEED_CONFIGURATION");gate.addProperty("scoreBefore",board.getPlayerScoreInfo(p,score).value());int value=0;String required=c.row.get("requiredAbility").getAsString();if(!required.equals("NONE")){var a=AbilityType.valueOf(required);value=config.get(a);require(value>0&&AchieveToDoMod.isAbilityLocked(p,a,true),"Initial ability gate missing");var g=new JsonObject();g.addProperty("threshold",value);g.addProperty("lockedBefore",true);board.getOrCreatePlayerScore(p,score).set(value);boolean locked=AchieveToDoMod.isAbilityLocked(p,a,true);require(!locked,"Ability stayed locked");g.addProperty("lockedAfter",locked);abilities.add(required,g);}gate.addProperty("scoreAfter",board.getPlayerScoreInfo(p,score).value());gate.add("abilities",abilities);return gate;}
    private static void aim(Context c){var p=c.joined.player();var delta=c.target.getBoundingBox().getCenter().subtract(p.getEyePosition());float yaw=(float)Math.toDegrees(Math.atan2(-delta.x,delta.z)),pitch=(float)Math.toDegrees(Math.atan2(-delta.y,Math.sqrt(delta.x*delta.x+delta.z*delta.z)));p.absSnapRotationTo(yaw,pitch);}
    private static void use(Context c,int sequence){var p=c.joined.player();new ServerboundUseItemPacket(InteractionHand.MAIN_HAND,sequence,p.getYRot(),p.getXRot()).handle(p.connection);c.packet=true;observeProjectiles(c);}
    private static void observeProjectiles(Context c){for(var e:c.joined.player().level().getEntitiesOfClass(Projectile.class,c.area))if(e.getOwner()==c.joined.player())c.projectiles.add(e.getUUID());}
    private static void act(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c,int ticks){try{
        var p=c.joined.player();require(!done(c)&&c.target.isAlive()&&c.target.getHealth()==c.health,"Pre-action witness changed");
        if(c.action().equals("MELEE")){if(p.getAttackStrengthScale(.5F)<.95F){require(ticks<40,"Natural melee cooldown missing");h.runAfterDelay(1,()->act(h,rows,i,run,exact,c,ticks+1));return;}new ServerboundAttackPacket(c.target.getId()).handle(p.connection);c.packet=true;h.runAfterDelay(1,()->poll(h,rows,i,run,exact,c,ticks+1));return;}
        aim(c);c.ammoBefore=c.ammo==null?0:ammoCount(p,c.ammo);use(c,0);
        if(Set.of("BOW","CROSSBOW").contains(c.action())){require(p.isUsingItem(),"Native launcher use rejected");int charge=c.action().equals("BOW")?20:CrossbowItem.getChargeDuration(c.tool,p)+4;h.runAfterDelay(charge,()->release(h,rows,i,run,exact,c,ticks+charge));}
        else if(c.action().equals("FISHING")){c.hook=p.fishing;require(c.hook!=null&&c.hook.getPlayerOwner()==p,"Native fishing cast missing");h.runAfterDelay(1,()->reel(h,rows,i,run,exact,c,ticks+1));}
        else h.runAfterDelay(1,()->poll(h,rows,i,run,exact,c,ticks+1));
    }catch(Throwable e){fail(h,c,"native action",e);}}
    private static void release(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c,int ticks){try{var p=c.joined.player();if(c.action().equals("CROSSBOW")){require(CrossbowItem.isCharged(c.tool),"Normal ticks did not charge crossbow");c.charged=true;var loaded=c.tool.get(DataComponents.CHARGED_PROJECTILES);require(loaded!=null&&loaded.itemCopies().size()==1&&loaded.itemCopies().getFirst().is(c.ammo),"Native loaded ammunition mismatch");}
        new ServerboundPlayerActionPacket(ServerboundPlayerActionPacket.Action.RELEASE_USE_ITEM,BlockPos.ZERO,Direction.DOWN,1).handle(p.connection);if(c.action().equals("CROSSBOW"))use(c,2);observeProjectiles(c);h.runAfterDelay(1,()->poll(h,rows,i,run,exact,c,ticks+1));
    }catch(Throwable e){fail(h,c,"release",e);}}
    private static void reel(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c,int ticks){try{if(c.hook.getHookedIn()==c.target){c.attached=true;require(!done(c),"Fishing criterion completed before reel");use(c,1);c.reeled=c.joined.player().fishing==null&&!c.hook.isAlive();h.runAfterDelay(1,()->poll(h,rows,i,run,exact,c,ticks+1));return;}require(ticks<80,"Native fishing collision timed out");h.runAfterDelay(1,()->reel(h,rows,i,run,exact,c,ticks+1));}catch(Throwable e){fail(h,c,"fishing",e);}}
    private static void poll(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c,int ticks){try{observeProjectiles(c);if(done(c)){finish(h,rows,i,run,exact,c,ticks);return;}require(ticks<180,"Native criterion timed out health="+c.target.getHealth()+" source="+c.target.getLastDamageSource());h.runAfterDelay(1,()->poll(h,rows,i,run,exact,c,ticks+1));}catch(Throwable e){fail(h,c,"collision",e);}}
    private static void finish(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c,int ticks)throws Exception{
        var p=c.joined.player();JsonObject r=new JsonObject();for(String key:new String[]{"advancementId","criterion","requirementGroup","trigger","boundary","selectedItem","action"})r.add(key,c.row.get(key).deepCopy());r.addProperty("family",PhaseAMixedWeaponryMulticlassedCertification.FAMILY);r.addProperty("source",PhaseAMixedWeaponryMulticlassedCertification.SOURCE);r.addProperty("runId",run);r.addProperty("catalogFingerprint",PhaseAMixedWeaponryMulticlassedEvidenceValidation.fingerprint(PhaseAMixedWeaponryMulticlassedExecutionEvidence.root()));r.addProperty("result","GREEN");r.addProperty("gameMode",p.gameMode().name());r.addProperty("playerUuid",p.getUUID().toString());r.addProperty("targetUuid",c.target.getUUID().toString());r.addProperty("joined",h.getLevel().getServer().getPlayerList().getPlayer(p.getUUID())==p);r.addProperty("connectionRegistered",h.getLevel().getServer().getConnection().getConnections().contains(c.joined.connection()));r.addProperty("clientLoaded",p.connection.hasClientLoaded());r.addProperty("finiteMaterials",!p.hasInfiniteMaterials());r.addProperty("notSpectator",!p.isSpectator());r.addProperty("criterionBefore",false);r.addProperty("criterionAfter",done(c));r.addProperty("nativePacketSent",c.packet);r.addProperty("ticksToComplete",ticks);r.addProperty("noDirectCriterionTrigger",true);r.addProperty("noManualAward",true);r.addProperty("itemCountBefore",1);r.addProperty("itemCountAfter",p.getMainHandItem().getCount());r.addProperty("ammoBefore",c.ammoBefore);r.addProperty("ammoAfter",c.ammo==null?0:ammoCount(p,c.ammo));r.addProperty("projectileSpawned",!c.projectiles.isEmpty());r.addProperty("chargedByNativeTicks",c.charged);r.addProperty("hookAttachedBeforeReel",c.attached);r.addProperty("hookRemovedAfterReel",c.reeled);r.addProperty("toolDamageBefore",c.damageBefore);r.addProperty("toolDamageAfter",c.tool.getDamageValue());r.add("productionGateWitness",c.gate);
        r.addProperty("itemCountAfter",ammoCount(p,BuiltInRegistries.ITEM.getValue(Identifier.parse(c.row.get("selectedItem").getAsString()))));
        r.addProperty("mainhandItemAfter",BuiltInRegistries.ITEM.getKey(p.getMainHandItem().getItem()).toString());
        if(c.row.get("trigger").getAsString().equals("minecraft:player_hurt_entity")){DamageSource source=c.target.getLastDamageSource();require(source!=null&&source.getEntity()==p&&source.getDirectEntity()!=null,"Native damage source owner missing");var d=new JsonObject();d.addProperty("sourceUuid",source.getEntity().getUUID().toString());d.addProperty("directUuid",source.getDirectEntity().getUUID().toString());d.addProperty("directType",BuiltInRegistries.ENTITY_TYPE.getKey(source.getDirectEntity().getType()).toString());d.addProperty("damageType",source.typeHolder().unwrapKey().orElseThrow().identifier().toString());d.addProperty("isProjectile",source.is(DamageTypeTags.IS_PROJECTILE));d.addProperty("healthBefore",c.health);d.addProperty("healthAfter",c.target.getHealth());d.addProperty("distance",p.distanceTo(c.target));String held=BuiltInRegistries.ITEM.getKey(p.getMainHandItem().getItem()).toString();d.addProperty("mainhandItem",held);boolean match=true;var conditions=c.row.getAsJsonObject("frozenConditions");var spec=conditions.getAsJsonObject("damage").getAsJsonObject("type");if(spec.has("source_entity")){var s=spec.getAsJsonObject("source_entity").getAsJsonObject("equipment").getAsJsonObject("mainhand").get("items");String id=s.isJsonArray()?s.getAsJsonArray().get(0).getAsString():s.getAsString();match=id.startsWith("#")?p.getMainHandItem().is(TagKey.create(Registries.ITEM,Identifier.parse(id.substring(1)))):held.equals(id);}d.addProperty("mainhandSelectorMatched",match);r.add("damageWitness",d);}
        boolean removed=removeFixtures(h,c);var clean=cleanup(c.joined);JsonObject cleanup=new JsonObject();cleanup.addProperty("fixtureEntitiesRemoved",removed);cleanup.addProperty("playerRemoved",clean.playerRemoved());cleanup.addProperty("connectionRemoved",clean.connectionRemoved());cleanup.addProperty("channelSettled",clean.channelSettled());cleanup.addProperty("warningCount",0);cleanup.addProperty("settlementMessages",clean.messages());r.add("cleanup",cleanup);PhaseAMixedWeaponryMulticlassedExecutionEvidence.append(PhaseAMixedWeaponryMulticlassedExecutionEvidence.root(),r);h.runAfterDelay(1,()->next(h,rows,i+1,run,exact));
    }
    private static int ammoCount(ServerPlayer p,Item item){int count=0;for(int i=0;i<p.getInventory().getContainerSize();i++){var s=p.getInventory().getItem(i);if(s.is(item))count+=s.getCount();}return count;}
    private static boolean done(Context c){var progress=c.joined.player().getAdvancements().getOrStartProgress(c.advancement).getCriterion(c.criterion());require(progress!=null,"Criterion missing");return progress.isDone();}
    private static boolean removeFixtures(GameTestHelper h,Context c){if(c.area==null)return true;for(var e:h.getLevel().getEntitiesOfClass(Entity.class,c.area))if(!c.baseline.contains(e.getUUID())&&(c.joined==null||e!=c.joined.player()))e.discard();return h.getLevel().getEntitiesOfClass(Entity.class,c.area).stream().allMatch(e->c.baseline.contains(e.getUUID())||(c.joined!=null&&e==c.joined.player()));}
    private static void fail(GameTestHelper h,Context c,String stage,Throwable e){removeFixtures(h,c);if(c.joined!=null)cleanup(c.joined);h.fail("Multiclassed "+c.criterion()+" "+stage+": "+e);}
    private static void acknowledge(Joined joined){var channel=joined.channel();channel.runPendingTasks();channel.runScheduledPendingTasks();channel.flushOutbound();Integer id=null;Object packet;while((packet=channel.readOutbound())!=null){if(packet instanceof ClientboundPlayerPositionPacket position)id=position.id();ReferenceCountUtil.release(packet);}require(id!=null,"missing teleport acknowledgement");new ServerboundAcceptTeleportationPacket(id).handle(joined.player().connection);}
    private static Joined join(GameTestHelper h){MinecraftServer server=h.getLevel().getServer();UUID id=UUID.randomUUID();GameProfile profile=new GameProfile(id,"weap"+id.toString().substring(0,8));ServerPlayer player=new ServerPlayer(server,h.getLevel(),profile,ClientInformation.createDefault());Connection connection=new Connection(PacketFlow.SERVERBOUND);EmbeddedChannel channel=new EmbeddedChannel(connection);server.getConnection().getConnections().add(connection);server.getPlayerList().placeNewPlayer(connection,player,CommonListenerCookie.createInitial(profile,false));return new Joined(player,connection,channel,new AtomicBoolean());}
    private static Cleanup cleanup(Joined joined){if(!joined.cleaned().compareAndSet(false,true))return new Cleanup(true,true,true,0);MinecraftServer server=joined.player().level().getServer();if(joined.player().containerMenu!=joined.player().inventoryMenu)joined.player().closeContainer();server.getPlayerList().remove(joined.player());boolean playerRemoved=server.getPlayerList().getPlayer(joined.player().getUUID())!=joined.player();server.getConnection().getConnections().remove(joined.connection());boolean connectionRemoved=!server.getConnection().getConnections().contains(joined.connection());int messages=settle(joined.channel());joined.connection().disconnect(Component.literal("multiclassed cleanup"));return new Cleanup(playerRemoved,connectionRemoved,true,messages);}
    private static int settle(EmbeddedChannel channel){if(!channel.isOpen())return 0;int released=0;for(int pass=0;pass<32;pass++){channel.runPendingTasks();channel.runScheduledPendingTasks();channel.flushOutbound();int current=0;Object outbound;while((outbound=channel.readOutbound())!=null){ReferenceCountUtil.release(outbound);current++;if(++released>4096)throw new IllegalStateException("channel cleanup message bound");}if(current==0&&!channel.hasPendingTasks())return released;}throw new IllegalStateException("channel did not quiesce");}
    private static void require(boolean yes,String why){if(!yes)throw new IllegalStateException(why);}
    private static final class Context{final JsonObject row;Joined joined;Mob target;AdvancementHolder advancement;ItemStack tool;Item ammo;FishingHook hook;float health;int damageBefore,ammoBefore;boolean packet,charged,attached,reeled;JsonObject gate;AABB area;Set<UUID> baseline=new HashSet<>(),projectiles=new HashSet<>();Context(JsonObject row){this.row=row;}String action(){return row.get("action").getAsString();}String criterion(){return row.get("criterion").getAsString();}}
    private record Joined(ServerPlayer player,Connection connection,EmbeddedChannel channel,AtomicBoolean cleaned){}
    private record Cleanup(boolean playerRemoved,boolean connectionRemoved,boolean channelSettled,int messages){}
    @Override public void invokeTestMethod(GameTestHelper h,Method method)throws ReflectiveOperationException{h.setBlock(0,0,0,Blocks.AIR);method.invoke(this,h);}
}
