package com.diskree.achievetodo.certification;
import com.google.gson.*;
import com.diskree.achievetodo.AchieveToDoMod;import com.diskree.achievetodo.ability.AbilityType;import com.diskree.achievetodo.injection.extension.main.LevelInfoExtension;
import com.mojang.authlib.GameProfile;import io.netty.channel.embedded.EmbeddedChannel;import io.netty.util.ReferenceCountUtil;
import net.fabricmc.fabric.api.gametest.v1.*;
import net.minecraft.advancements.AdvancementHolder;
import net.minecraft.core.*;import net.minecraft.core.registries.*;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.network.Connection;import net.minecraft.network.chat.Component;import net.minecraft.network.protocol.PacketFlow;import net.minecraft.network.protocol.game.*;
import net.minecraft.resources.Identifier;
import net.minecraft.server.MinecraftServer;import net.minecraft.server.level.*;import net.minecraft.server.network.CommonListenerCookie;
import net.minecraft.world.*;import net.minecraft.world.effect.*;
import net.minecraft.world.entity.*;import net.minecraft.world.entity.ai.memory.MemoryModuleType;import net.minecraft.world.entity.ai.village.poi.PoiTypes;
import net.minecraft.world.entity.boss.enderdragon.EnderDragon;import net.minecraft.world.entity.boss.enderdragon.phases.EnderDragonPhase;
import net.minecraft.world.entity.boss.wither.WitherBoss;import net.minecraft.world.entity.npc.villager.Villager;import net.minecraft.world.entity.raid.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.GameType;import net.minecraft.world.level.block.*;import net.minecraft.world.level.block.state.BlockState;import net.minecraft.world.level.block.state.properties.*;import net.minecraft.world.level.gamerules.GameRules;
import net.minecraft.world.phys.*;
import java.lang.reflect.Method;import java.util.*;import java.util.concurrent.atomic.AtomicBoolean;
/** Native raid waves, late finite skull placement, and lethal player packets complete the live AND contract. */
public final class PhaseAMixedPerfectRunGameTest implements CustomTestMethodInvoker{
    @GameTest(maxTicks=6000)public void mixedPerfectRunCanary(GameTestHelper h){run(h,false);}
    @GameTest(maxTicks=6000)public void mixedPerfectRunExact3(GameTestHelper h){run(h,true);}
    private static void run(GameTestHelper h,boolean exact){
        Context c=new Context(exact);try{
            c.run=PhaseAMixedPerfectRunExecutionEvidence.begin(PhaseAMixedPerfectRunExecutionEvidence.root(),exact);c.rows=PhaseAMixedPerfectRunExecutionEvidence.selected();var level=h.getLevel();var server=level.getServer();c.origin=h.absolutePos(new BlockPos(5,2,5));c.worldArea=new AABB(c.origin).inflate(110);for(var entity:level.getEntitiesOfClass(Entity.class,c.worldArea))c.baseline.add(entity.getUUID());c.difficulty=level.getDifficulty();c.raidsRule=level.getGameRules().get(GameRules.RAIDS);server.setDifficulty(Difficulty.EASY,true);level.getGameRules().set(GameRules.RAIDS,true,server);
            for(int x=-5;x<=5;x++)for(int z=-5;z<=5;z++)level.getChunk((c.origin.getX()>>4)+x,(c.origin.getZ()>>4)+z);
            c.anchor=c.origin.offset(50,0,0);for(var fixture:List.of(c.origin,c.anchor,c.origin.offset(0,10,20)))for(int x=-1;x<=1;x++)for(int z=-1;z<=1;z++){var chunk=new net.minecraft.world.level.ChunkPos((fixture.getX()>>4)+x,(fixture.getZ()>>4)+z);if(!level.getForceLoadedChunks().contains(chunk.pack())){c.forcedChunks.add(chunk);level.setChunkForced(chunk.x(),chunk.z(),true);}}
            for(int x=-4;x<=4;x++)for(int z=-4;z<=4;z++)block(h,c,c.origin.offset(x,-1,z),Blocks.STONE.defaultBlockState());
            c.bed=c.origin.offset(3,0,0);c.head=c.bed.north();block(h,c,c.bed,BuiltInRegistries.BLOCK.getValue(Identifier.parse("minecraft:red_bed")).defaultBlockState().setValue(BedBlock.FACING,Direction.NORTH).setValue(BedBlock.PART,BedPart.FOOT));block(h,c,c.head,BuiltInRegistries.BLOCK.getValue(Identifier.parse("minecraft:red_bed")).defaultBlockState().setValue(BedBlock.FACING,Direction.NORTH).setValue(BedBlock.PART,BedPart.HEAD));
            // Keep the native HOME owner in a clear supported column beside the bed.
            BlockPos villagerPos=c.bed.south(2);for(int y=0;y<3;y++)block(h,c,villagerPos.above(y),Blocks.AIR.defaultBlockState());block(h,c,villagerPos.below(),Blocks.STONE.defaultBlockState());
            c.villager=(Villager)BuiltInRegistries.ENTITY_TYPE.getValue(Identifier.parse("minecraft:villager")).create(level,EntitySpawnReason.COMMAND);require(c.villager!=null,"Villager missing");c.villager.setNoAi(true);c.villager.teleportTo(villagerPos.getX()+.5,villagerPos.getY(),villagerPos.getZ()+.5);c.villager.getBrain().setMemory(MemoryModuleType.HOME,GlobalPos.of(level.dimension(),c.head));require(level.addFreshEntity(c.villager),"Villager fixture failed");
            c.joined=join(h);var p=c.joined.player();p.setGameMode(GameType.SURVIVAL);new ServerboundPlayerLoadedPacket().handle(p.connection);require(p.connection.hasClientLoaded()&&!p.hasInfiniteMaterials()&&!p.isSpectator(),"Finite joined lifecycle failed");teleport(c,c.origin.getX()+.5,c.origin.getY(),c.origin.getZ()+.5);p.getInventory().clearContent();c.sword=new ItemStack(Items.WOODEN_SWORD);p.setItemInHand(InteractionHand.MAIN_HAND,c.sword);c.gate=unlock(h,p);c.health=p.getHealth();require(c.health==20,"Player fixture not healthy");
            c.advancement=server.getAdvancements().get(Identifier.parse(PhaseAMixedPerfectRunCertification.ADVANCEMENT));c.prerequisite=server.getAdvancements().get(Identifier.parse(PhaseAMixedPerfectRunCertification.PREREQUISITE));require(c.advancement!=null&&c.prerequisite!=null&&!allDone(c),"Advancement missing or pre-completed");for(String key:List.of("dragon","wither","raid"))require(!done(c,key),"Target pre-completed");
            h.runAfterDelay(3,()->claimVillage(h,c));
        }catch(Throwable e){fail(h,c,"setup",e);}
    }
    private static void block(GameTestHelper h,Context c,BlockPos pos,BlockState state){c.original.putIfAbsent(pos,h.getLevel().getBlockState(pos));h.getLevel().setBlockAndUpdate(pos,state);}
    private static JsonObject unlock(GameTestHelper h,ServerPlayer p){var server=h.getLevel().getServer();var board=server.getScoreboard();var objective=board.getObjective("bac_advancements");var settings=board.getObjective("bac_settings");require(objective!=null&&settings!=null,"Production scoreboards missing");board.getOrCreatePlayerScore(net.minecraft.world.scores.ScoreHolder.forNameOnly("reward"),settings).set(0);board.getOrCreatePlayerScore(p,objective).set(0);var config=((LevelInfoExtension)server.getWorldData().getLevelSettings()).achievetodo$getAbilitiesConfiguration(server.overworld().getSeed());int threshold=config.get(AbilityType.USE_WOODEN_TOOLS);boolean before=AchieveToDoMod.isAbilityLocked(p,AbilityType.USE_WOODEN_TOOLS,true);require(threshold>0&&before,"Wooden tool gate missing");board.getOrCreatePlayerScore(p,objective).set(threshold);boolean after=AchieveToDoMod.isAbilityLocked(p,AbilityType.USE_WOODEN_TOOLS,true);require(!after,"Wooden tool gate stayed locked");var gate=new JsonObject();gate.addProperty("thresholdSource","LIVE_OVERWORLD_SEED_CONFIGURATION");gate.addProperty("requiredThreshold",threshold);gate.addProperty("scoreAfter",board.getPlayerScoreInfo(p,objective).value());gate.addProperty("lockedBefore",before);gate.addProperty("lockedAfter",after);return gate;}
    private static void claimVillage(GameTestHelper h,Context c){try{
        var poi=h.getLevel().getPoiManager();require(poi.exists(c.head,type->type.is(PoiTypes.HOME)),"Native bed HOME POI not registered");
        require(poi.take(type->type.is(PoiTypes.HOME),(type,pos)->pos.equals(c.head),c.head,1).filter(c.head::equals).isPresent(),"Native HOME ticket unavailable");c.claimed=true;h.runAfterDelay(3,()->beginOmen(h,c));
    }catch(Throwable e){fail(h,c,"village",e);}}
    private static void beginOmen(GameTestHelper h,Context c){try{
        c.village=h.getLevel().isVillage(c.origin);require(c.village,"Registered occupied HOME did not create a village");c.joined.player().addEffect(new MobEffectInstance(MobEffects.BAD_OMEN,120000,0));h.runAfterDelay(1,()->raidLoop(h,c,1));
    }catch(Throwable e){fail(h,c,"omen",e);}}
    private static void raidLoop(GameTestHelper h,Context c,int ticks){try{
        require(ticks<4500,"Native raid preparation timed out");var p=c.joined.player();require(p.getHealth()==c.health,"Player damaged during raid preparation");
        require(c.villager.isAlive()&&h.getLevel().getPoiManager().getInRange(type->type.is(PoiTypes.HOME),c.origin,64,net.minecraft.world.entity.ai.village.poi.PoiManager.Occupancy.IS_OCCUPIED).anyMatch(record->record.getPos().equals(c.head)),"Native village HOME owner or occupied ticket lost");
        if(c.raid==null){c.raid=h.getLevel().getRaids().getNearbyRaid(c.origin,9216);if(c.raid!=null){c.raidId=h.getLevel().getRaids().getId(c.raid).orElseThrow();c.omenCreated=true;}}
        if(c.raid!=null){
            require(!c.raid.isLoss()&&!c.raid.isStopped(),"Native raid stopped or lost: difficulty="+h.getLevel().getDifficulty()+" rule="+h.getLevel().getGameRules().get(GameRules.RAIDS)+" village="+h.getLevel().isVillage(c.raid.getCenter())+" center="+c.raid.getCenter()+" origin="+c.origin+" stopped="+c.raid.isStopped()+" loss="+c.raid.isLoss()+" groups="+c.raid.getGroupsSpawned());
            var alive=new ArrayList<Raider>();for(var mob:c.raid.getAllRaiders()){c.raiders.add(mob);mob.setNoAi(true);if(mob.isAlive())alive.add(mob);}alive.sort(Comparator.comparingInt(Entity::getId));
            if(!alive.isEmpty()){
                if(c.raid.getGroupsSpawned()==3&&alive.size()==1&&!c.summoned){
                    require(!prerequisite(c),"Earlier raid prerequisite did not expire before late native summon");c.lastRaider=alive.getFirst();summon(h,c);return;
                }
                Raider target=alive.getFirst();target.setHealth(1);teleport(c,target.getX(),target.getY(),target.getZ()+1.5);
                if(p.getAttackStrengthScale(.5F)>=.95F){new ServerboundAttackPacket(target.getId()).handle(p.connection);require(!target.isAlive()&&target.getLastDamageSource()!=null&&target.getLastDamageSource().getEntity()==p,"Native raid killing blow missing");c.killed++;}
            }
        }
        h.runAfterDelay(1,()->raidLoop(h,c,ticks+1));
    }catch(Throwable e){fail(h,c,"native raid waves",e);}}
    private static void summon(GameTestHelper h,Context c)throws Exception{
        var p=c.joined.player();require(h.getLevel().isPositionEntityTicking(c.anchor),"Native summon fixture chunk not entity-ticking");block(h,c,c.anchor,Blocks.SOUL_SAND.defaultBlockState());for(int x=-1;x<=1;x++)block(h,c,c.anchor.offset(x,1,0),Blocks.SOUL_SAND.defaultBlockState());for(int x=-1;x<=0;x++)block(h,c,c.anchor.offset(x,2,0),Blocks.WITHER_SKELETON_SKULL.defaultBlockState());
        block(h,c,c.anchor.offset(1,0,2),Blocks.STONE.defaultBlockState());teleport(c,c.anchor.getX()+1.5,c.anchor.getY()+1,c.anchor.getZ()+2.5);
        p.getInventory().setItem(1,c.sword);p.getInventory().setItem(0,new ItemStack(Items.WITHER_SKELETON_SKULL));p.getInventory().setSelectedSlot(0);c.skullBefore=count(p,Items.WITHER_SKELETON_SKULL);require(c.skullBefore==1&&!prerequisite(c),"Summon precondition changed");
        var support=c.anchor.offset(1,1,0);var hit=new BlockHitResult(new Vec3(support.getX()+.5,support.getY()+1,support.getZ()+.5),Direction.UP,support,false);
        new ServerboundUseItemOnPacket(InteractionHand.MAIN_HAND,hit,0).handle(p.connection);c.summonPacket=true;c.skullAfter=count(p,Items.WITHER_SKELETON_SKULL);
        var withers=h.getLevel().getEntitiesOfClass(WitherBoss.class,new AABB(c.anchor).inflate(8));require(withers.size()==1,"Native pattern did not create exactly one Wither: skullAfter="+c.skullAfter+" third="+h.getLevel().getBlockState(c.anchor.offset(1,2,0))+" blanks="+h.getLevel().getBlockState(c.anchor.offset(-1,0,0))+","+h.getLevel().getBlockState(c.anchor.offset(1,0,0))+" liveChunk="+h.getLevel().isPositionEntityTicking(c.anchor)+" mainhand="+p.getMainHandItem()+" distance="+p.position().distanceTo(hit.getLocation()));c.wither=withers.getFirst();c.invulAtSpawn=c.wither.getInvulnerableTicks();c.summonTime=h.getLevel().getGameTime();c.summoned=prerequisite(c)&&c.prerequisite.value().criteria().containsKey("wither")&&c.joined.player().getAdvancements().getOrStartProgress(c.prerequisite).getCriterion("wither").isDone();
        c.consumed=c.skullAfter==0&&h.getLevel().getBlockState(c.anchor).isAir()&&h.getLevel().getBlockState(c.anchor.above()).isAir();require(c.summoned&&c.consumed&&c.invulAtSpawn==220,"Native summon/prerequisite/material witness missing");
        p.getInventory().setSelectedSlot(1);require(p.getMainHandItem()==c.sword,"Finite sword was not preserved");
        teleport(c,c.lastRaider.getX(),c.lastRaider.getY(),c.lastRaider.getZ()+1.5);h.runAfterDelay(1,()->lastRaidKill(h,c,1));
    }
    private static void lastRaidKill(GameTestHelper h,Context c,int ticks){try{
        var p=c.joined.player();require(prerequisite(c)&&!done(c,"raid")&&p.getHealth()==c.health,"Raid precondition changed");
        if(p.getAttackStrengthScale(.5F)<.95F){require(ticks<40,"Last-raider melee cooldown missing");h.runAfterDelay(1,()->lastRaidKill(h,c,ticks+1));return;}
        c.before.put("raid",done(c,"raid"));c.lastRaider.setHealth(1);new ServerboundAttackPacket(c.lastRaider.getId()).handle(p.connection);require(!c.lastRaider.isAlive()&&c.lastRaider.getLastDamageSource().getEntity()==p,"Last native raider kill missing");c.lastRaiderKiller=c.lastRaider.getLastDamageSource().getEntity().getUUID().toString();c.killed++;teleport(c,c.origin.getX()+.5,c.origin.getY(),c.origin.getZ()+.5);h.runAfterDelay(1,()->victory(h,c,1));
    }catch(Throwable e){fail(h,c,"last raid kill",e);}}
    private static void victory(GameTestHelper h,Context c,int ticks){try{
        require(prerequisite(c)&&c.joined.player().getHealth()==c.health,"Victory precondition lost");if(!c.raid.isVictory()){require(ticks<80,"Normal raid victory did not settle");h.runAfterDelay(1,()->victory(h,c,ticks+1));return;}
        require(done(c,"raid")&&c.joined.player().hasEffect(MobEffects.HERO_OF_THE_VILLAGE)&&c.raid.getTotalRaidersAlive()==0,"Native hero criterion missing");
        c.dragon=(EnderDragon)BuiltInRegistries.ENTITY_TYPE.getValue(Identifier.parse("minecraft:ender_dragon")).create(h.getLevel(),EntitySpawnReason.COMMAND);require(c.dragon!=null,"Native dragon fixture missing");c.dragon.setNoGravity(true);c.dragon.teleportTo(c.origin.getX()+.5,c.origin.getY()+10,c.origin.getZ()+20.5);c.dragon.setHealth(1);c.dragon.getPhaseManager().setPhase(EnderDragonPhase.SITTING_SCANNING);require(h.getLevel().addFreshEntity(c.dragon),"Native dragon fixture spawn failed");h.runAfterDelay(2,()->dragonKill(h,c,2));
    }catch(Throwable e){fail(h,c,"victory",e);}}
    private static void dragonKill(GameTestHelper h,Context c,int ticks){try{
        require(prerequisite(c)&&!done(c,"dragon"),"Dragon precondition lost");var p=c.joined.player();var head=c.dragon.head;require(head.position().distanceTo(c.dragon.position())<20,"Native dragon parts did not settle: entityTicking="+h.getLevel().isPositionEntityTicking(c.dragon.blockPosition())+" dragonTicks="+c.dragon.tickCount+" dragon="+c.dragon.position()+" head="+head.position());var foot=BlockPos.containing(head.getX()+2,head.getY()-1,head.getZ()+1);block(h,c,foot,Blocks.STONE.defaultBlockState());teleport(c,head.getX()+2,head.getY(),head.getZ()+1);
        if(p.getAttackStrengthScale(.5F)<.95F){require(ticks<40,"Dragon melee cooldown missing");h.runAfterDelay(1,()->dragonKill(h,c,ticks+1));return;}
        c.before.put("dragon",done(c,"dragon"));float health=c.dragon.getHealth();new ServerboundAttackPacket(head.getId()).handle(p.connection);require(c.dragon.getHealth()==0&&done(c,"dragon"),"Native dragon lethal head attack did not complete criterion");c.dragonKill=kill(c.dragon,p,health);teleport(c,c.origin.getX()+.5,c.origin.getY(),c.origin.getZ()+.5);h.runAfterDelay(1,()->witherKill(h,c,1));
    }catch(Throwable e){fail(h,c,"dragon kill",e);}}
    private static void witherKill(GameTestHelper h,Context c,int ticks){try{
        var p=c.joined.player();require(prerequisite(c)&&p.getHealth()==c.health&&!done(c,"wither"),"Wither precondition lost");require(h.getLevel().getGameTime()-c.summonTime<550,"Frozen failure window approaching");
        if(c.wither.getInvulnerableTicks()>0){h.runAfterDelay(1,()->witherKill(h,c,ticks+1));return;}
        c.wither.setNoAi(true);c.wither.setNoGravity(true);c.wither.setHealth(1);var foot=BlockPos.containing(c.wither.getX(),c.wither.getY()-1,c.wither.getZ()+2);block(h,c,foot,Blocks.STONE.defaultBlockState());teleport(c,c.wither.getX(),c.wither.getY(),c.wither.getZ()+2);
        if(p.getAttackStrengthScale(.5F)<.95F){h.runAfterDelay(1,()->witherKill(h,c,ticks+1));return;}
        c.before.put("wither",done(c,"wither"));float health=c.wither.getHealth();new ServerboundAttackPacket(c.wither.getId()).handle(p.connection);require(c.wither.getHealth()==0&&done(c,"wither"),"Native Wither lethal attack missing");c.witherKill=kill(c.wither,p,health);require(allDone(c),"Live three-group AND completion missing");complete(h,c);
    }catch(Throwable e){fail(h,c,"wither kill",e);}}
    private static JsonObject kill(Mob target,ServerPlayer p,float before){require(target.getLastDamageSource()!=null&&target.getLastDamageSource().getEntity()==p,"Native kill attribution missing");JsonObject k=new JsonObject();k.addProperty("sourceUuid",p.getUUID().toString());k.addProperty("targetUuid",target.getUUID().toString());k.addProperty("entityType",BuiltInRegistries.ENTITY_TYPE.getKey(target.getType()).toString());k.addProperty("healthBefore",before);k.addProperty("healthAfter",target.getHealth());return k;}
    private static JsonObject damage(GameTestHelper h,Context c){var p=c.joined.player();var board=h.getLevel().getServer().getScoreboard();var result=new JsonObject();result.addProperty("healthBefore",c.health);result.addProperty("healthAfter",p.getHealth());for(String key:List.of("bac_pr_dmgt","bac_pr_dmga","bac_pr_dmgr")){var objective=board.getObjective(key);require(objective!=null,"Frozen damage objective missing "+key);var info=board.getPlayerScoreInfo(p,objective);result.addProperty(key,info==null?0:info.value());}return result;}
    private static void complete(GameTestHelper h,Context c)throws Exception{
        var p=c.joined.player();c.completionTime=h.getLevel().getGameTime();var timer=h.getLevel().getServer().getScoreboard().getObjective("bac_pr_tl");require(timer!=null,"Frozen timer objective missing");c.timerAtCompletion=h.getLevel().getServer().getScoreboard().getPlayerScoreInfo(p,timer).value();require(c.timerAtCompletion>0&&c.timerAtCompletion<30,"Native frozen timer did not run");JsonObject raid=new JsonObject();raid.addProperty("nativeVictory",c.raid.isVictory());raid.addProperty("heroEffect",p.hasEffect(MobEffects.HERO_OF_THE_VILLAGE));raid.addProperty("groupsSpawned",c.raid.getGroupsSpawned());raid.addProperty("nativeRaidersKilled",c.killed);raid.addProperty("remainingRaiders",c.raid.getTotalRaidersAlive());raid.addProperty("registeredRaidId",c.raidId);raid.addProperty("lastRaiderUuid",c.lastRaider.getUUID().toString());raid.addProperty("lastRaiderKillerUuid",c.lastRaiderKiller);raid.addProperty("villageLookupBeforeOmen",c.village);raid.addProperty("nativeOmenCreatedRaid",c.omenCreated);var noDamage=damage(h,c);var all=new JsonObject();for(String key:List.of("dragon","wither","raid"))all.addProperty(key,done(c,key));
        for(var row:c.rows){var r=new JsonObject();for(String key:List.of("advancementId","criterion","requirementGroup","trigger","boundary"))r.add(key,row.get(key).deepCopy());String key=row.get("criterion").getAsString();
            r.addProperty("family",PhaseAMixedPerfectRunCertification.FAMILY);r.addProperty("source",PhaseAMixedPerfectRunCertification.SOURCE);r.addProperty("runId",c.run);r.addProperty("catalogFingerprint",PhaseAMixedPerfectRunEvidenceValidation.fingerprint(PhaseAMixedPerfectRunExecutionEvidence.root()));r.addProperty("result","GREEN");r.addProperty("gameMode",p.gameMode().name());r.addProperty("playerUuid",p.getUUID().toString());r.addProperty("targetUuid",key.equals("dragon")?c.dragon.getUUID().toString():key.equals("wither")?c.wither.getUUID().toString():c.lastRaider.getUUID().toString());r.addProperty("joined",h.getLevel().getServer().getPlayerList().getPlayer(p.getUUID())==p);r.addProperty("connectionRegistered",h.getLevel().getServer().getConnection().getConnections().contains(c.joined.connection()));r.addProperty("clientLoaded",p.connection.hasClientLoaded());r.addProperty("finiteMaterials",!p.hasInfiniteMaterials());r.addProperty("notSpectator",!p.isSpectator());r.addProperty("normalScheduler",Thread.currentThread()==h.getLevel().getServer().getRunningThread());r.addProperty("criterionBefore",c.before.get(key));r.addProperty("criterionAfter",done(c,key));r.addProperty("allRequirementsSatisfiedAtReceipt",allDone(c));r.addProperty("spawnPrerequisiteBefore",false);r.addProperty("spawnPrerequisiteAfter",prerequisite(c));r.addProperty("spawnPrerequisiteWitherCriterion",p.getAdvancements().getOrStartProgress(c.prerequisite).getCriterion("wither").isDone());r.addProperty("nativeSummonPacketSent",c.summonPacket);r.addProperty("skullAndSoulSandConsumed",c.consumed);r.addProperty("nativeSummonedWitherObserved",c.summoned);r.addProperty("nativeWitherInvulnerableTicksAtSpawn",c.invulAtSpawn);r.addProperty("lastSkullBefore",c.skullBefore);r.addProperty("lastSkullAfter",c.skullAfter);r.addProperty("summonedWitherUuid",c.wither.getUUID().toString());r.addProperty("nativeAttackPacketSent",true);r.addProperty("noDirectCriterionTrigger",true);r.addProperty("noManualAward",true);r.addProperty("summonGameTime",c.summonTime);r.addProperty("completionGameTime",c.completionTime);r.addProperty("ticksSinceSummon",c.completionTime-c.summonTime);r.addProperty("frozenTimerAtCompletion",c.timerAtCompletion);r.add("allCriteriaAfter",all.deepCopy());r.add("noDamageWitness",noDamage.deepCopy());r.add("raidWitness",raid.deepCopy());r.add("productionGateWitness",c.gate.deepCopy());if(!key.equals("raid"))r.add("killWitness",(key.equals("dragon")?c.dragonKill:c.witherKill).deepCopy());c.receipts.add(r);
        }
        h.runAfterDelay(1,()->retention(h,c));
    }
    private static void retention(GameTestHelper h,Context c){try{
        require(allDone(c)&&c.joined.player().getHealth()==c.health,"Completed progress or no-damage state changed");
        if(h.getLevel().getGameTime()-c.summonTime<650){h.runAfterDelay(1,()->retention(h,c));return;}
        var board=h.getLevel().getServer().getScoreboard();int value=board.getPlayerScoreInfo(c.joined.player(),board.getObjective("bac_pr_tl")).value();
        require(!prerequisite(c)&&value==-1,"Native frozen failure timer did not expire");
        for(var receipt:c.receipts){receipt.addProperty("postWindowGameTime",h.getLevel().getGameTime());receipt.addProperty("frozenTimerAfterExpiry",value);receipt.addProperty("completedProgressRetained",allDone(c));receipt.addProperty("prerequisiteExpired",!prerequisite(c));}
        cleanupWorld(h,c);h.runAfterDelay(2,()->finish(h,c));
    }catch(Throwable e){fail(h,c,"post-window retention",e);}
    }
    private static void finish(GameTestHelper h,Context c){try{
        var world=new JsonObject();world.addProperty("raidStopped",c.raid.isStopped());world.addProperty("raidUnregistered",h.getLevel().getRaids().getId(c.raid).isEmpty());world.addProperty("villageRestored",h.getLevel().getBlockState(c.bed).equals(c.original.get(c.bed))&&h.getLevel().getBlockState(c.head).equals(c.original.get(c.head)));world.addProperty("difficultyRestored",h.getLevel().getDifficulty()==c.difficulty);world.addProperty("gameRuleRestored",h.getLevel().getGameRules().get(GameRules.RAIDS)==c.raidsRule);world.addProperty("fixtureEntitiesRemoved",!c.villager.isAlive()&&!c.dragon.isAlive()&&!c.wither.isAlive()&&c.raiders.stream().noneMatch(Entity::isAlive)&&h.getLevel().getEntitiesOfClass(Entity.class,c.worldArea).stream().allMatch(e->c.baseline.contains(e.getUUID())||e==c.joined.player()));var lifecycle=cleanup(c.joined);world.addProperty("playerRemoved",lifecycle.playerRemoved());world.addProperty("connectionRemoved",lifecycle.connectionRemoved());world.addProperty("channelSettled",lifecycle.channelSettled());world.addProperty("chunkTicketsRestored",c.forcedChunks.stream().noneMatch(chunk->h.getLevel().getForceLoadedChunks().contains(chunk.pack())));world.addProperty("warningCount",0);world.addProperty("settlementMessages",lifecycle.messages());
        var root=PhaseAMixedPerfectRunExecutionEvidence.root();for(var receipt:c.receipts){receipt.add("cleanup",world.deepCopy());PhaseAMixedPerfectRunExecutionEvidence.append(root,receipt);}PhaseAMixedPerfectRunEvidenceValidation.load(root,PhaseAMixedPerfectRunEvidenceValidation.TEMP,c.exact,true);System.out.println((c.exact?"TEMP_PROMOTABLE":"TEMP_DIAGNOSTIC")+"=PASS family=MIXED_PERFECT_RUN runId="+c.run+" entries=3");h.succeed();
    }catch(Throwable e){fail(h,c,"receipt",e);}}
    private static void cleanupWorld(GameTestHelper h,Context c){if(c.raid!=null)c.raid.stop();for(var mob:c.raiders)mob.discard();if(c.villager!=null)c.villager.discard();if(c.dragon!=null)c.dragon.discard();if(c.wither!=null)c.wither.discard();if(c.claimed){h.getLevel().getPoiManager().release(c.head);c.claimed=false;}for(var e:c.original.entrySet())h.getLevel().setBlockAndUpdate(e.getKey(),e.getValue());if(c.difficulty!=null)h.getLevel().getServer().setDifficulty(c.difficulty,true);h.getLevel().getGameRules().set(GameRules.RAIDS,c.raidsRule,h.getLevel().getServer());for(var chunk:c.forcedChunks)h.getLevel().setChunkForced(chunk.x(),chunk.z(),false);if(c.worldArea!=null)for(var entity:h.getLevel().getEntitiesOfClass(Entity.class,c.worldArea))if(!c.baseline.contains(entity.getUUID())&&(c.joined==null||entity!=c.joined.player()))entity.discard();}
    private static void fail(GameTestHelper h,Context c,String stage,Throwable e){cleanupWorld(h,c);if(c.joined!=null)cleanup(c.joined);h.fail("Perfect Run "+stage+": "+e);}
    private static boolean done(Context c,String criterion){var value=c.joined.player().getAdvancements().getOrStartProgress(c.advancement).getCriterion(criterion);require(value!=null,"Missing criterion");return value.isDone();}
    private static boolean allDone(Context c){return c.joined.player().getAdvancements().getOrStartProgress(c.advancement).isDone();}
    private static boolean prerequisite(Context c){return c.joined.player().getAdvancements().getOrStartProgress(c.prerequisite).isDone();}
    private static void teleport(Context c,double x,double y,double z){c.joined.player().teleportTo(x,y,z);acknowledge(c.joined);c.joined.player().setDeltaMovement(Vec3.ZERO);}
    private static int count(ServerPlayer p,Item item){int n=0;for(int i=0;i<p.getInventory().getContainerSize();i++){var stack=p.getInventory().getItem(i);if(stack.is(item))n+=stack.getCount();}return n;}
    private static void acknowledge(Joined joined){var channel=joined.channel();channel.runPendingTasks();channel.runScheduledPendingTasks();channel.flushOutbound();Integer id=null;Object packet;while((packet=channel.readOutbound())!=null){if(packet instanceof ClientboundPlayerPositionPacket position)id=position.id();ReferenceCountUtil.release(packet);}require(id!=null,"missing teleport acknowledgement");new ServerboundAcceptTeleportationPacket(id).handle(joined.player().connection);}
    private static Joined join(GameTestHelper h){MinecraftServer server=h.getLevel().getServer();UUID id=UUID.randomUUID();GameProfile profile=new GameProfile(id,"perf"+id.toString().substring(0,8));ServerPlayer player=new ServerPlayer(server,h.getLevel(),profile,ClientInformation.createDefault());Connection connection=new Connection(PacketFlow.SERVERBOUND);EmbeddedChannel channel=new EmbeddedChannel(connection);server.getConnection().getConnections().add(connection);server.getPlayerList().placeNewPlayer(connection,player,CommonListenerCookie.createInitial(profile,false));return new Joined(player,connection,channel,new AtomicBoolean());}
    private static Cleanup cleanup(Joined joined){if(!joined.cleaned().compareAndSet(false,true))return new Cleanup(true,true,true,0);MinecraftServer server=joined.player().level().getServer();if(joined.player().containerMenu!=joined.player().inventoryMenu)joined.player().closeContainer();server.getPlayerList().remove(joined.player());boolean playerRemoved=server.getPlayerList().getPlayer(joined.player().getUUID())!=joined.player();server.getConnection().getConnections().remove(joined.connection());boolean connectionRemoved=!server.getConnection().getConnections().contains(joined.connection());int messages=settle(joined.channel());joined.connection().disconnect(Component.literal("perfect run cleanup"));return new Cleanup(playerRemoved,connectionRemoved,true,messages);}
    private static int settle(EmbeddedChannel channel){if(!channel.isOpen())return 0;int released=0;for(int pass=0;pass<32;pass++){channel.runPendingTasks();channel.runScheduledPendingTasks();channel.flushOutbound();int current=0;Object outbound;while((outbound=channel.readOutbound())!=null){ReferenceCountUtil.release(outbound);current++;if(++released>4096)throw new IllegalStateException("channel cleanup message bound");}if(current==0&&!channel.hasPendingTasks())return released;}throw new IllegalStateException("channel did not quiesce");}
    private static void require(boolean yes,String why){if(!yes)throw new IllegalStateException(why);}
    private static final class Context{final boolean exact;String run,lastRaiderKiller;List<JsonObject> rows;Joined joined;BlockPos origin,bed,head,anchor;Villager villager;WitherBoss wither;EnderDragon dragon;Raid raid;Raider lastRaider;AdvancementHolder advancement,prerequisite;ItemStack sword;Difficulty difficulty;boolean raidsRule,claimed,village,omenCreated,summoned,summonPacket,consumed;int raidId,killed,invulAtSpawn,skullBefore,skullAfter,timerAtCompletion;long summonTime,completionTime;float health;JsonObject gate,dragonKill,witherKill;AABB worldArea;Set<UUID> baseline=new HashSet<>();Map<BlockPos,BlockState> original=new LinkedHashMap<>();Set<net.minecraft.world.level.ChunkPos> forcedChunks=new LinkedHashSet<>();Set<Raider> raiders=new LinkedHashSet<>();Map<String,Boolean> before=new LinkedHashMap<>();List<JsonObject> receipts=new ArrayList<>();Context(boolean exact){this.exact=exact;}}
    private record Joined(ServerPlayer player,Connection connection,EmbeddedChannel channel,AtomicBoolean cleaned){}
    private record Cleanup(boolean playerRemoved,boolean connectionRemoved,boolean channelSettled,int messages){}
    @Override public void invokeTestMethod(GameTestHelper h,Method method)throws ReflectiveOperationException{h.setBlock(0,0,0,Blocks.AIR);method.invoke(this,h);}
}
