package com.diskree.achievetodo.certification;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import static com.diskree.achievetodo.certification.Final19StaticContext.require;
/** Reconstruct original receipt provenance only after the exact authorized output equivalence bridge. */
final class Final19PreservedSemanticBridge {
 static final String CONVERTER="src/main/java/com/diskree/achievetodo/client/ExternalPackCompatibility.java";
 static String originalInputSha(Path root,String path)throws Exception{if(!path.equals(CONVERTER))return Pre26SmokeAcceptedSources.sha(root,path);require(Pre26SmokeAcceptedSources.sha(root,path).equals(Final19RaiderProductionTest.POST),"Unauthorized converter drift");require(Final19StaticContext.sha(Files.readAllBytes(root.resolve("reference/phase_a_planning/final19/raider_production_fix_proposal.patch"))).equals("518ebaae8587b6276610e02473fac985c12cd9431cf3c344bd31c08f48ddbdbe"),"Stale patch");var auth=Final19WorldgenEvidence.read(root.resolve("reference/phase_a_planning/final19/raider_authorized_application.json"));require(auth.get("id").getAsString().equals("AUTHORIZED_FINAL19_RAIDER_PRODUCTION_FIX")&&auth.get("patchApplied").getAsBoolean(),"Missing explicit authorization");require(auth.getAsJsonObject("productionSemanticBridge").get("sha256").getAsString().equals("e2b0ad1e98b119f4bfb78758f9497f3247dc0916b2fbcbbf559cf225f0c881a4")&&Final19StaticContext.sha(Files.readAllBytes(root.resolve("reference/phase_a_planning/final19/raider_production_output_scope.json"))).equals("e2b0ad1e98b119f4bfb78758f9497f3247dc0916b2fbcbbf559cf225f0c881a4"),"Stale authorized semantic bridge");var scope=Final19WorldgenEvidence.read(root.resolve("reference/phase_a_planning/final19/raider_production_output_scope.json"));require(scope.get("productionConverterSha256").getAsString().equals(Final19RaiderProductionTest.POST)&&scope.get("preFixConverterSha256").getAsString().equals(Final19RaiderProductionTest.PRE)&&scope.get("definitions").getAsInt()==1229&&scope.get("canonicalDefinitions").getAsInt()==1152&&scope.get("allIdempotent").getAsBoolean(),"Invalid real converter semantic bridge");Set<String>changed=new TreeSet<>();for(var e:scope.getAsJsonObject("outputFingerprints").entrySet()){var r=e.getValue().getAsJsonObject();if(!r.get("preFixOutputSha256").equals(r.get("productionOutputSha256")))changed.add(e.getKey());}require(changed.equals(Set.of("data/minecraft/advancement/adventure/voluntary_exile.json","data/blazeandcave/advancement/adventure/feeling_ill.json","data/blazeandcave/advancement/monsters/dungeon_crawler.json")),"FINAL19_RAIDER_SCOPE_INVALIDATED");return Final19RaiderProductionTest.PRE;}
 static String inputFingerprint(Path root,String family)throws Exception{StringBuilder s=new StringBuilder();for(String path:List.of("reference/phase_a_preservation/files/final/bacap.zip",CONVERTER,"tools/final19/java/com/diskree/achievetodo/certification/Final19StaticContext.java","src/test/resources/final19_certification/"+family.toLowerCase(Locale.ROOT)+"_catalog.json"))s.append(path).append(':').append(originalInputSha(root,path)).append('\n');return Final19StaticContext.sha(s.toString().getBytes(StandardCharsets.UTF_8));}
}
