package com.diskree.achievetodo.certification;
import com.diskree.achievetodo.client.*;
import com.google.gson.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.zip.*;
import static com.diskree.achievetodo.certification.Final19StaticContext.require;
/** Separate final combat transactions; earlier accepted evidence and provenance stay immutable. */
public final class Final19CombatEvidence {
 public static Path root(){return Final19WorldgenEvidence.root();}
 public static Path file(String prefix,String suffix){return Path.of("build/tmp/final19_implementation/"+prefix+"_"+suffix+".json");}
 public static String fingerprint(Path root,String prefix)throws Exception{StringBuilder s=new StringBuilder();for(String p:List.of("reference/phase_a_preservation/files/final/bacap.zip","src/main/java/com/diskree/achievetodo/client/ExternalPackCompatibility.java","src/main/resources/achievetodo.mixins.json","tools/final19/java/com/diskree/achievetodo/certification/Final19CombatStaticContext.java","tools/final19/java/com/diskree/achievetodo/certification/Final19CombatEvidence.java","tools/final19/gametest/com/diskree/achievetodo/certification/Final19NativeActors.java","tools/final19/gametest/com/diskree/achievetodo/certification/Final19"+(prefix.equals("shield")?"Shield":"Raider")+"GameTest.java","src/test/resources/phase_a_certification/runtime_test_matrix.json"))s.append(p).append(':').append(Pre26SmokeAcceptedSources.sha(root,p)).append('\n');if(prefix.equals("shield"))for(String p:List.of("tools/final19/gametest/com/diskree/achievetodo/certification/Final19ShieldProbe.java","tools/final19/gametest/com/diskree/achievetodo/certification/probe/Final19ShieldDamageMixin.java","tools/final19/gametest/com/diskree/achievetodo/certification/probe/Final19NativeAiShotMixin.java"))s.append(p).append(':').append(Pre26SmokeAcceptedSources.sha(root,p)).append('\n');return Final19StaticContext.sha(s.toString().getBytes(StandardCharsets.UTF_8));}
 public static JsonObject definition(String id)throws Exception{String path="data/"+id.replace(":","/advancement/")+".json";try(var frozen=new ZipFile(root().resolve("reference/phase_a_preservation/files/final/bacap.zip").toFile());var runtime=new ZipFile(root().resolve("build/run/gameTest/world/datapacks/bacap.zip").toFile())){byte[] raw;try(var in=frozen.getInputStream(frozen.getEntry(path))){raw=in.readAllBytes();}var expected=Final19StaticContext.convert(new String(raw,StandardCharsets.UTF_8));JsonObject actual;try(var in=runtime.getInputStream(runtime.getEntry(path))){actual=JsonParser.parseString(new String(in.readAllBytes(),StandardCharsets.UTF_8)).getAsJsonObject();}require(actual.equals(expected),"Fresh runtime/frozen production conversion mismatch "+id);return actual;}}
 public static String begin(String prefix,boolean exact)throws Exception{Path root=root();var pack=root.resolve("build/run/gameTest/world/datapacks/bacap.zip");require(ExternalPackCompatibility.isCompatibleWorldCopy(pack,ExternalPack.BACAP),"Stale runtime pack");String id=UUID.randomUUID().toString();JsonObject a=new JsonObject();a.addProperty("runId",id);a.addProperty("prefix",prefix);a.addProperty("exact",exact);a.addProperty("fingerprint",fingerprint(root,prefix));a.addProperty("runtimeCopySha256",Final19StaticContext.sha(Files.readAllBytes(pack)));a.addProperty("productionConverterSha256","1bea3ba9caf22963d1ef26de69b19534a4b16d1eab85a39c5e1fc17750227a31");a.addProperty("certificationGain",prefix.equals("raider_integrity")?0:1);a.add("entries",new JsonArray());Final19WorldgenEvidence.write(root.resolve(file(prefix,"temp")),a);var r=a.deepCopy();r.remove("entries");r.addProperty("stage","RUNNING");Final19WorldgenEvidence.write(root.resolve(file(prefix,"run")),r);return id;}
 public static void append(String prefix,JsonObject receipt)throws Exception{Path p=root().resolve(file(prefix,"temp"));var a=Final19WorldgenEvidence.read(p);require(a.get("runId").equals(receipt.get("runId")),"Wrong receipt run");a.getAsJsonArray("entries").add(receipt);Final19WorldgenEvidence.write(p,a);}
 public static Set<String> cases(String prefix,boolean exact){if(prefix.equals("raider_integrity")){Set<String>s=new TreeSet<>();for(String type:List.of("vindicator","pillager","ravager","witch","evoker"))for(String mode:List.of("raid","nonraid"))s.add("feeling_ill/"+type+"/"+mode);for(String type:List.of("pillager","vindicator","evoker"))for(String mode:List.of("raid","nonraid"))s.add("dungeon_crawler/"+type+"/"+mode);return s;}if(prefix.equals("raider"))return exact?Set.of("ordinary","banner_only","raid_captain","outsider","captain"):Set.of("ordinary","captain");return Set.of("inactive_shield","melee_skeleton","other_owner","locked_shield","blocked_skeleton");}
 public static JsonObject validate(Path path,String prefix,boolean exact)throws Exception{var a=Final19WorldgenEvidence.read(path);require(a.get("prefix").getAsString().equals(prefix)&&a.get("exact").getAsBoolean()==exact,"Wrong combat mode");require(a.get("fingerprint").getAsString().equals(fingerprint(root(),prefix)),"Stale combat fingerprint");require(a.get("productionConverterSha256").getAsString().equals("1bea3ba9caf22963d1ef26de69b19534a4b16d1eab85a39c5e1fc17750227a31"),"Stale production source");Path copy=root().resolve("reference/phase_a_planning/final19/combat_runtime_copies/"+a.get("runtimeCopySha256").getAsString()+".zip");if(!Files.exists(copy))copy=root().resolve("build/run/gameTest/world/datapacks/bacap.zip");require(Final19StaticContext.sha(Files.readAllBytes(copy)).equals(a.get("runtimeCopySha256").getAsString())&&Pre26SmokeAcceptedSources.retainedCopy(copy),"Stale runtime fingerprint/marker");Set<String>seen=new TreeSet<>(),actors=new HashSet<>(),entities=new HashSet<>();for(var e:a.getAsJsonArray("entries")){var r=e.getAsJsonObject();String key=r.get("case").getAsString();require(cases(prefix,exact).contains(key)&&seen.add(key),"Unexpected/duplicate control");require(r.get("runId").equals(a.get("runId"))&&actors.add(r.get("playerUuid").getAsString())&&entities.add(r.get("targetUuid").getAsString()),"Reused actor/entity or run");for(String f:List.of("joined","connectionRegistered","clientLoaded","finiteMaterials","noDirectTrigger","noManualAward","nativeAction"))Final19FamilyEvidence.truth(r,f);require(r.get("gameMode").getAsString().equals("SURVIVAL")&&!r.get("criterionBefore").getAsBoolean(),"Wrong lifecycle/precompleted");boolean expected=prefix.equals("raider_integrity")?key.startsWith("feeling_ill")?key.endsWith("/raid"):key.endsWith("/nonraid"):key.equals(prefix.equals("raider")?"captain":"blocked_skeleton");require(r.get("criterionAfter").getAsBoolean()==expected,"False criterion witness "+key);for(String f:List.of("playerRemoved","connectionRemoved","channelSettled","fixtureEntitiesRemoved","blocksRestored"))Final19FamilyEvidence.truth(r.getAsJsonObject("cleanup"),f);
  if(!prefix.equals("shield")){var w=r.getAsJsonObject("raiderWitness");boolean raid=key.endsWith("/raid")||key.equals("raid_captain"),captain=key.equals("captain")||key.equals("raid_captain");require(w.get("hasRaid").getAsBoolean()==raid&&w.get("isCaptain").getAsBoolean()==captain,"Wrong live raider state");require(w.get("patrolLeader").getAsBoolean()==captain,"Wrong patrol state");require(w.get("nativeKillCredit").getAsBoolean(),"Missing native kill credit");if(captain)Final19FamilyEvidence.truth(w,"exactOminousBanner");if(raid){Final19FamilyEvidence.truth(w,"registeredLiveRaid");Final19FamilyEvidence.truth(r.getAsJsonObject("cleanup"),"raidStoppedAndUnregistered");}var decoded=r.getAsJsonObject("decodedPredicate");require(decoded.get("hasRaid").getAsBoolean()==(key.startsWith("feeling_ill"))&&decoded.get("isCaptain").getAsBoolean()==prefix.equals("raider"),"Incorrect codec semantics");}
  else{var w=r.getAsJsonObject("damageWitness");Final19FamilyEvidence.truth(w,"nativeHurtObserved");boolean projectile=!key.equals("melee_skeleton"),skeleton=!key.equals("other_owner"),blocked=key.equals("blocked_skeleton")||key.equals("other_owner");require(w.get("isProjectile").getAsBoolean()==projectile&&w.get("skeletonSource").getAsBoolean()==skeleton&&w.get("blocked").getAsBoolean()==blocked,"Wrong damage/source/block state");if(projectile){Final19FamilyEvidence.truth(w,"liveProjectileOwnerObserved");Final19FamilyEvidence.truth(w,"nativeAiShotObserved");}var gate=r.getAsJsonObject("shieldGate");require(gate.get("lockedAfter").getAsBoolean()==key.equals("locked_shield"),"Wrong production shield gate");if(blocked){require(r.get("shieldDamageAfter").getAsInt()>r.get("shieldDamageBefore").getAsInt(),"No native shield cost");require(r.get("blockingTicks").getAsInt()>=5,"Native shield delay missing");}}
 }require(seen.equals(cases(prefix,exact)),"Missing exact controls");if(path.equals(root().resolve(file(prefix,"temp")))){var r=Final19WorldgenEvidence.read(root().resolve(file(prefix,"run")));require(r.get("runId").equals(a.get("runId"))&&r.get("fingerprint").equals(a.get("fingerprint")),"Actual TEMP/run mismatch");}return a;}
 public static void complete(String prefix,boolean exact)throws Exception{var a=validate(root().resolve(file(prefix,"temp")),prefix,exact);var r=Final19WorldgenEvidence.read(root().resolve(file(prefix,"run")));r.addProperty("expectedEntries",a.getAsJsonArray("entries").size());r.addProperty("stage",exact?"TEMP_PROMOTABLE":"TEMP_DIAGNOSTIC");Final19WorldgenEvidence.write(root().resolve(file(prefix,"run")),r);}
}
