package com.diskree.achievetodo.certification;
import com.diskree.achievetodo.client.*;
import com.google.gson.*;
import org.junit.jupiter.api.Test;
import java.nio.file.*;
import java.util.*;
import java.util.zip.*;
import java.nio.charset.StandardCharsets;
import static org.junit.jupiter.api.Assertions.*;
class Pre26SmokeTerminalAcceptanceTest {
 final Path root=Path.of("").toAbsolutePath();
 @Test void independentlyDerivedTerminalCountsAndExactFrozenRequirementGroupsReconcile()throws Exception{
  var state=Final19WorldgenEvidence.read(root.resolve("reference/phase_a_planning/final19/execution_state.json"));var ledger=Final19WorldgenEvidence.read(root.resolve("reference/phase_a_planning/final19/product_ledger.json"));var audit=Final19WorldgenEvidence.read(root.resolve("reference/phase_a_planning/final19/pre26_2_final19_audit.json"));Set<String>original=new TreeSet<>(),resolved=new TreeSet<>(),all=new TreeSet<>();for(var e:audit.getAsJsonArray("entries"))original.add(e.getAsJsonObject().get("advancementId").getAsString());for(var e:ledger.getAsJsonArray("entries")){var o=e.getAsJsonObject();assertTrue(all.add(o.get("id").getAsString()));if(o.has("productStatus")){assertEquals("FINAL19_CERTIFIED",o.get("productStatus").getAsString());assertTrue(o.get("productRequirementsSatisfied").getAsBoolean());resolved.add(o.get("id").getAsString());}}assertEquals(1152,all.size());assertEquals(original,resolved);assertEquals(19,resolved.size());assertEquals(1133+resolved.size(),ledger.get("productCertified").getAsInt());assertEquals(1152,state.get("productCertified").getAsInt());assertEquals(0,ledger.get("productUncertified").getAsInt());assertEquals(7,state.getAsJsonArray("completedFamilies").size());assertEquals(0,state.getAsJsonArray("remainingTargets").size());int groups=0,criteria=0;
  for(var family:state.getAsJsonArray("completedFamilies")){var cat=Final19WorldgenEvidence.read(root.resolve("src/test/resources/final19_certification/"+family.getAsString().toLowerCase(Locale.ROOT)+"_catalog.json"));groups+=cat.getAsJsonArray("cases").size();for(var s:cat.getAsJsonArray("sources"))criteria+=s.getAsJsonObject().getAsJsonObject("auditedConvertedDefinition").getAsJsonObject("criteria").size();}assertEquals(79,groups);assertEquals(108,criteria);assertEquals("439f2aa1c577ffbee275525765ac9229bf5633f0f5e1da498c0adc5702bd2810",Final19StaticContext.sha(Files.readAllBytes(root.resolve("src/test/resources/phase_a_certification/phase_a_advancement_rollup.json"))));
 }
 @Test void acceptedSevenFamiliesAndZeroGainArtifactsRemainExactAndHashBound()throws Exception{var state=Final19WorldgenEvidence.read(root.resolve("reference/phase_a_planning/final19/execution_state.json"));Set<String>runs=new HashSet<>();for(var v:state.getAsJsonArray("persistentEvidenceInventory")){var e=v.getAsJsonObject();assertTrue(runs.add(e.get("runId").getAsString()));assertEquals(e.get("sha256").getAsString(),Final19StaticContext.sha(Files.readAllBytes(root.resolve(e.get("path").getAsString()))));}assertEquals(7,runs.size());for(var v:state.getAsJsonArray("auxiliaryRegressionEvidence")){var e=v.getAsJsonObject();assertEquals(0,e.get("certificationGain").getAsInt());assertEquals(e.get("sha256").getAsString(),Final19StaticContext.sha(Files.readAllBytes(root.resolve(e.get("path").getAsString()))));}assertEquals(3,state.getAsJsonArray("auxiliaryRegressionEvidence").size());for(var v:state.getAsJsonObject("zeroGainRegressionDebt").entrySet())assertTrue(v.getValue().getAsString().endsWith("GREEN"));}
 @Test void currentProductionAndFreshRuntimeCopyMatchAll1229SemanticBridgeOutputs()throws Exception{assertEquals(Final19RaiderProductionTest.POST,Pre26SmokeAcceptedSources.sha(root,Final19PreservedSemanticBridge.CONVERTER));var pack=root.resolve("build/run/pre26Smoke01/world/datapacks/bacap.zip");assertTrue(ExternalPackCompatibility.isCompatibleWorldCopy(pack,ExternalPack.BACAP));assertEquals("snake_case",Final19RaiderProductionTest.readMarker(pack).getProperty("raiderPredicateKeys"));var outputs=Final19WorldgenEvidence.read(root.resolve("reference/phase_a_planning/final19/raider_production_output_scope.json")).getAsJsonObject("outputFingerprints");assertEquals(1229,outputs.size());try(var zip=new ZipFile(pack.toFile())){for(var e:outputs.entrySet()){byte[] bytes;try(var in=zip.getInputStream(zip.getEntry(e.getKey()))){bytes=in.readAllBytes();}assertEquals(e.getValue().getAsJsonObject().get("productionOutputSha256").getAsString(),Final19StaticContext.sha(bytes),e.getKey());}}assertEquals("8c72314535c5df7b4416bf0f38310371ec8aec537fde1445bdc820a3c9aada70",Final19StaticContext.sha(Files.readAllBytes(root.resolve("reference/phase_a_preservation/files/final/bacap.zip"))));}
}
