package com.diskree.achievetodo.certification;
import com.google.gson.*;
import org.junit.jupiter.api.Test;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
class Pre26SmokeCauldronGateAcceptanceTest {
    static final Path ROOT=Path.of("").toAbsolutePath();
    static final String PATCH="ec33a350ef1ae9185ac99e1c2425a1cec38ca0d64244819058c3cc610a5a07fe";
    static final Map<String,String> HASHES=Map.of(
        "src/main/resources/achievetodo.mixins.json","56fcb41d75273382681cbeede45882a876de68babcd6580ae63d5c20c0ac211f",
        "src/main/java/com/diskree/achievetodo/injection/mixin/main/AbstractCauldronBlockAccessor.java","63c46d242eeecabe946be353a8a2353a5ef6555d93982f8e0f8c6846ca4dfd2e",
        "src/main/java/com/diskree/achievetodo/injection/mixin/main/ServerPlayerGameModeCauldronGateMixin.java","3f21c817198c59fd650c6384e5cc73bcda2b743ef252003b00ec8278d5193e78",
        "src/main/java/com/diskree/achievetodo/injection/mixin/main/AbstractCauldronBlockMixin.java","c9473d4918c8d31c7215dcb98a388f3a24660b36940940a598861e9d90985394",
        "src/main/java/com/diskree/achievetodo/injection/mixin/main/AxeItemMixin.java","4247ef44ce7e331f43820d889ecef541f8cbb0a200a31ede2764c8ecbdd46a13");
    static Path evidence(){var p=ROOT.resolve("src/test/resources/final19_certification/cauldron_gate_postfix_regression.json");return Files.exists(p)?p:ROOT.resolve("build/tmp/final19_implementation/cauldron_gate_regression.json");}
    static boolean b(JsonObject r,String k){return r.get(k).getAsBoolean();}static String s(JsonObject r,String k){return r.get(k).getAsString();}static int n(JsonObject r,String k){return r.get(k).getAsInt();}
    @Test void all24FreshNativeControlsAndExactProductionBytesPass()throws Exception{
        for(var e:HASHES.entrySet())assertEquals(e.getValue(),Pre26SmokeAcceptedSources.sha(ROOT,e.getKey()));assertEquals(PATCH,Final19StaticContext.sha(Files.readAllBytes(ROOT.resolve("reference/phase_a_planning/final19/cauldron_gate_production_fix_proposal.patch"))));
        validate(Final19WorldgenEvidence.read(evidence()));var persistent=ROOT.resolve("reference/phase_a_planning/final19/authorized_production_fixes/cauldron_gate");Path gates=Files.exists(persistent.resolve("cauldron_gate_regression.exit"))?persistent:ROOT.resolve("build/tmp/final19_implementation");String log=Files.readString(gates.resolve("cauldron_gate_regression.gradle.log"));assertEquals("0",Files.readString(gates.resolve("cauldron_gate_regression.exit")).trim());assertTrue(log.contains("BUILD SUCCESSFUL")&&log.contains(" (1 tests)")&&log.contains("entries=24"));int start=log.indexOf("FINAL19_CAULDRON_GATE_REGRESSION_START");assertTrue(start>=0);for(String forbidden:List.of("/WARN]","/ERROR]","Failed to handle packet","Leak:"))assertFalse(log.substring(start).contains(forbidden));
    }
    static void validate(JsonObject a){
        UUID.fromString(s(a,"runId"));assertFalse(Set.of("30c8e9d9-4710-476a-852f-30e3f4baa96f","62c46b0a-8e9f-4f26-be99-6299336d8ac3","5c40ea07-d9ad-45c6-b1ad-c267fe43740d").contains(s(a,"runId")));assertEquals(0,n(a,"certificationGain"));assertEquals("POST_FIX_REGRESSION_GREEN",s(a,"stage"));assertEquals(PATCH,s(a,"patchSha256"));assertEquals(HASHES.keySet(),a.getAsJsonObject("productionHashes").keySet());for(var e:HASHES.entrySet())assertEquals(e.getValue(),s(a.getAsJsonObject("productionHashes"),e.getKey()));
        Set<String> expected=new HashSet<>();for(String mode:List.of("LOCKED_MATERIAL","UNLOCKED_MATERIAL","LOCKED_LANDMARK","OUTSIDE_LOCKED_LANDMARK"))for(String path:List.of("LEATHER","BANNER","SHULKER"))expected.add(mode+"|"+path);
        for(String mode:List.of("WRONG_ITEM","EMPTY_HAND","NO_OP_LEATHER","NO_OP_BANNER","NO_OP_SHULKER","FALLBACK_BANNER","FALLBACK_SHULKER","SECONDARY_LEATHER","SECONDARY_PLACEMENT","NON_CAULDRON","DEFAULT_PLACEMENT","REGISTERED_BUCKET"))expected.add(mode+"|"+(mode.endsWith("BANNER")?"BANNER":mode.endsWith("SHULKER")?"SHULKER":"LEATHER"));
        Set<String> seen=new HashSet<>(),players=new HashSet<>();for(var value:a.getAsJsonArray("entries")){var r=value.getAsJsonObject();String mode=s(r,"mode"),path=s(r,"path");assertTrue(expected.contains(mode+"|"+path)&&seen.add(mode+"|"+path));UUID.fromString(s(r,"playerUuid"));assertTrue(players.add(s(r,"playerUuid")));assertEquals("SURVIVAL",s(r,"gameMode"));assertEquals("ServerboundUseItemOnPacket.handle",s(r,"nativeBoundary"));assertEquals("ONE_ORIGINAL_CALL_UNMODIFIED_RETURN",s(r,"resultProbe"));for(String flag:List.of("joined","connectionRegistered","clientLoaded","finiteMaterials"))assertTrue(b(r,flag));for(String flag:List.of("playerRemoved","connectionRemoved","channelSettled","blocksRestored","ownedLandmarkRemoved","fixtureEntitiesRemoved"))assertTrue(b(r.getAsJsonObject("cleanup"),flag));
            boolean core=mode.endsWith("MATERIAL")||mode.contains("LANDMARK"),success=mode.equals("UNLOCKED_MATERIAL")||mode.equals("OUTSIDE_LOCKED_LANDMARK"),placement=Set.of("SECONDARY_PLACEMENT","NON_CAULDRON","DEFAULT_PLACEMENT").contains(mode),bucket=mode.equals("REGISTERED_BUCKET");boolean unlocked=success||mode.equals("LOCKED_LANDMARK")||mode.startsWith("NO_OP")||bucket;
            assertEquals(!unlocked,b(r,"lockedBefore"));assertEquals(!unlocked,b(r,"lockedAfter"));assertEquals(mode.equals("LOCKED_LANDMARK"),b(r,"landmarkBefore"));assertEquals(b(r,"landmarkBefore"),b(r,"landmarkAfter"));assertTrue(n(r,"liveThreshold")>0);if(!success&&!placement&&!bucket)assertEquals(n(r,"scoreBefore"),n(r,"scoreAfter"));else assertTrue(n(r,"scoreAfter")>=n(r,"scoreBefore"));assertEquals(unlocked,n(r,"scoreBefore")>=n(r,"liveThreshold"));assertEquals(mode.startsWith("SECONDARY"),b(r,"secondaryUse"));if(mode.contains("LANDMARK"))assertTrue(n(r,"landmarkThreshold")>n(r,"scoreBefore"));
            String dispatcher=mode.equals("NON_CAULDRON")?"NON_CAULDRON":Set.of("WRONG_ITEM","EMPTY_HAND","NO_OP_SHULKER","SECONDARY_PLACEMENT","DEFAULT_PLACEMENT").contains(mode)?"DEFAULT":"REGISTERED";assertEquals(dispatcher,s(r,"dispatcherClassification"));assertEquals(!mode.equals("NON_CAULDRON"),b(r,"blockTagMember"));assertEquals("minecraft:cauldrons",s(r,"checkedBlockTag"));assertEquals(path.equals("LEATHER")?"minecraft:leather_armor":path.equals("BANNER")?"minecraft:banners":"minecraft:shulker_boxes",s(r,"checkedItemTag"));assertEquals(core||mode.startsWith("NO_OP")||mode.startsWith("FALLBACK")||mode.equals("SECONDARY_LEATHER"),b(r,"itemTagMember"));
            var before=r.getAsJsonObject("before");var after=r.getAsJsonObject("after");assertFalse(b(before,"criterion"));assertEquals(success,b(after,"criterion"));assertEquals(0,n(before,"damage"));assertEquals(0,n(after,"damage"));
            String expectedItem=placement?"minecraft:cobblestone":bucket?"minecraft:water_bucket":mode.equals("WRONG_ITEM")?"minecraft:stick":path.equals("LEATHER")?"minecraft:leather_chestplate":path.equals("BANNER")?"minecraft:white_banner":mode.equals("NO_OP_SHULKER")?"minecraft:shulker_box":"minecraft:red_shulker_box";
            if(mode.equals("EMPTY_HAND")){assertEquals("EMPTY",s(before,"item"));assertEquals(0,n(before,"count"));}else{JsonObject expectedBytes=new JsonObject();expectedBytes.addProperty("id",expectedItem);expectedBytes.addProperty("count",1);boolean dirty=core||mode.startsWith("FALLBACK")||mode.equals("SECONDARY_LEATHER");if(dirty&&path.equals("LEATHER")){var components=new JsonObject();components.addProperty("minecraft:dyed_color",11141120);expectedBytes.add("components",components);}if(dirty&&path.equals("BANNER"))expectedBytes.add("components",JsonParser.parseString("{\"minecraft:banner_patterns\":[{\"pattern\":\"minecraft:cross\",\"color\":\"red\"}]}"));assertEquals(expectedBytes,JsonParser.parseString(s(before,"item")));assertEquals(expectedItem,s(before,"itemId"));assertEquals(1,n(before,"count"));}
            int initialWater=mode.equals("NO_OP_SHULKER")||bucket||mode.equals("NON_CAULDRON")?0:3;assertEquals(initialWater,n(before,"waterLevel"));assertEquals(mode.equals("NON_CAULDRON")?"Block{minecraft:stone}":initialWater==0?"Block{minecraft:cauldron}":"Block{minecraft:water_cauldron}[level=3]",s(before,"block"));assertEquals(mode.startsWith("NO_OP")?"Block{minecraft:stone}":"Block{minecraft:air}",s(before,"above"));
            if(success){assertEquals(3,n(before,"waterLevel"));assertEquals(2,n(after,"waterLevel"));assertEquals("Success",s(r,"resultClass"));assertTrue(b(r,"consumesAction"));assertEquals(before.get("above"),after.get("above"));assertEquals(1,n(before,"count"));assertEquals(1,n(after,"count"));assertNotEquals(before.get("item"),after.get("item"));JsonObject item=JsonParser.parseString(s(after,"item")).getAsJsonObject();JsonObject components=item.has("components")?item.getAsJsonObject("components"):new JsonObject();if(path.equals("LEATHER"))assertFalse(components.has("minecraft:dyed_color"));if(path.equals("BANNER"))assertTrue(!components.has("minecraft:banner_patterns")||components.getAsJsonArray("minecraft:banner_patterns").isEmpty());if(path.equals("SHULKER"))assertEquals("minecraft:shulker_box",s(after,"itemId"));}
            else if(placement){assertEquals("Success",s(r,"resultClass"));assertTrue(b(r,"consumesAction"));assertEquals(before.get("block"),after.get("block"));assertEquals(before.get("waterLevel"),after.get("waterLevel"));assertEquals("Block{minecraft:cobblestone}",s(after,"above"));assertEquals(0,n(after,"count"));}
            else if(bucket){assertEquals("Success",s(r,"resultClass"));assertTrue(b(r,"consumesAction"));assertEquals(0,n(before,"waterLevel"));assertEquals(3,n(after,"waterLevel"));assertEquals("minecraft:water_bucket",s(before,"itemId"));assertEquals("minecraft:bucket",s(after,"itemId"));}
            else{assertEquals(before,after,"Actual negative snapshots differ: "+mode);assertFalse(b(r,"consumesAction"));assertEquals(core||mode.startsWith("FALLBACK")||mode.equals("NO_OP_BANNER")||mode.equals("NO_OP_SHULKER")?"Fail":"Pass",s(r,"resultClass"));}
        }assertEquals(expected,seen);
    }
    @Test void malformedMissingReusedStaleFalseAwardFalseStateDispatcherCleanupAndFallbackClaimsAreRejected()throws Exception{
        var original=Final19WorldgenEvidence.read(evidence());for(int mutation=0;mutation<13;mutation++){var bad=original.deepCopy();var entries=bad.getAsJsonArray("entries");var first=entries.get(0).getAsJsonObject();switch(mutation){case 0->entries.remove(0);case 1->entries.get(1).getAsJsonObject().add("playerUuid",first.get("playerUuid"));case 2->bad.getAsJsonObject("productionHashes").addProperty("src/main/resources/achievetodo.mixins.json","stale");case 3->bad.getAsJsonObject("productionHashes").addProperty("src/main/java/com/diskree/achievetodo/injection/mixin/main/ServerPlayerGameModeCauldronGateMixin.java","stale");case 4->bad.addProperty("patchSha256","stale");case 5->first.getAsJsonObject("after").addProperty("criterion",true);case 6->first.getAsJsonObject("after").addProperty("item","fake changed bytes");case 7->first.addProperty("dispatcherClassification","DEFAULT");case 8->first.getAsJsonObject("cleanup").addProperty("blocksRestored",false);case 9->entries.get(6).getAsJsonObject().getAsJsonObject("cleanup").addProperty("ownedLandmarkRemoved",false);case 10->entries.get(17).getAsJsonObject().getAsJsonObject("after").addProperty("above","Block{minecraft:white_banner}");case 11->entries.get(19).getAsJsonObject().addProperty("secondaryUse",false);case 12->bad.addProperty("certificationGain",1);}assertThrows(AssertionError.class,()->validate(bad),"mutation "+mutation);}
    }
}
