package com.diskree.achievetodo.certification;
import com.diskree.achievetodo.AchieveToDoMod;
import com.diskree.achievetodo.ability.AbilityType;
import com.diskree.achievetodo.injection.extension.main.LevelInfoExtension;
import com.google.gson.*;
import net.fabricmc.fabric.api.gametest.v1.*;
import net.minecraft.advancements.AdvancementHolder;
import net.minecraft.core.*;
import net.minecraft.core.registries.*;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.network.protocol.game.*;
import net.minecraft.resources.Identifier;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.projectile.Projectile;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.AABB;
import java.lang.reflect.Method;
import java.util.*;
import static com.diskree.achievetodo.certification.Final19StaticContext.require;
/** Real AI shots and melee; native shield use and native hurt observation, no synthesized damage. */
public final class Final19ShieldGameTest implements CustomTestMethodInvoker {
 @GameTest(maxTicks=5000) public void shieldCanary5(GameTestHelper h){run(h,false);}
 @GameTest(maxTicks=5000) public void shieldExact5(GameTestHelper h){run(h,true);}
 static void run(GameTestHelper h,boolean exact){try{System.out.println("FINAL19_DIAGNOSTIC_WARMUP_START");var warm=Final19NativeActors.join(h.getLevel(),h.absolutePos(new BlockPos(5,1,3)));Final19NativeActors.unlock(warm,AbilityType.USE_SHIELD);var clean=Final19NativeActors.close(warm);for(String k:List.of("playerRemoved","connectionRemoved","channelSettled"))require(clean.get(k).getAsBoolean(),"Warmup cleanup failed");System.out.println("FINAL19_DIAGNOSTIC_WARMUP_COMPLETE cleanup="+clean);h.runAfterDelay(40,()->begin(h,exact));}catch(Throwable e){h.fail("FINAL19 warmup: "+e);}}
 static void begin(GameTestHelper h,boolean exact){try{System.out.println("FINAL19_NATIVE_RUN_START family=shield");Final19CombatEvidence.definition("minecraft:story/deflect_arrow");String run=Final19CombatEvidence.begin("shield",exact);next(h,new ArrayList<>(new TreeSet<>(Final19CombatEvidence.cases("shield",exact))),0,run,exact);}catch(Throwable e){h.fail("FINAL19 shield begin: "+e);}}
 static void next(GameTestHelper h,List<String>cases,int i,String run,boolean exact){if(i==cases.size()){try{Final19CombatEvidence.complete("shield",exact);System.out.println((exact?"TEMP_PROMOTABLE":"TEMP_DIAGNOSTIC")+"=PASS family=shield runId="+run+" entries="+cases.size());h.succeed();}catch(Throwable e){h.fail("FINAL19 shield audit: "+e);}return;}Context c=new Context(cases.get(i));try{
  c.pos=h.absolutePos(new BlockPos(5,1,3));c.area=new AABB(c.pos).inflate(24);for(var e:h.getLevel().getEntitiesOfClass(Entity.class,c.area))c.baseline.add(e.getUUID());for(int x=-6;x<=6;x++)for(int z=-3;z<=12;z++)for(int y=-1;y<=3;y++){var p=c.pos.offset(x,y,z);c.blocks.put(p,h.getLevel().getBlockState(p));h.getLevel().setBlockAndUpdate(p,y==-1||y==3?Blocks.STONE.defaultBlockState():Blocks.AIR.defaultBlockState());}
  c.actor=Final19NativeActors.join(h.getLevel(),c.pos);c.adv=h.getLevel().getServer().getAdvancements().get(Identifier.parse("minecraft:story/deflect_arrow"));require(c.adv!=null&&!done(c),"Missing/precompleted shield target");c.actor.player().getInventory().setItem(c.actor.player().getInventory().getSelectedSlot(),new ItemStack(Items.SHIELD));
  var p=c.actor.player();if(c.key.equals("locked_shield")){var server=h.getLevel().getServer();var board=server.getScoreboard();var objective=board.getObjective("bac_advancements");require(objective!=null,"Missing live score");board.getOrCreatePlayerScore(p,objective).set(0);int threshold=((LevelInfoExtension)server.getWorldData().getLevelSettings()).achievetodo$getAbilitiesConfiguration(server.overworld().getSeed()).get(AbilityType.USE_SHIELD);c.gate.addProperty("threshold",threshold);c.gate.addProperty("scoreAfter",board.getPlayerScoreInfo(p,objective).value());c.gate.addProperty("lockedBefore",AchieveToDoMod.isAbilityLocked(p,AbilityType.USE_SHIELD,true));require(threshold>0&&c.gate.get("lockedBefore").getAsBoolean(),"Locked shield fixture missing");}else{var unlock=Final19NativeActors.unlock(c.actor,AbilityType.USE_SHIELD);c.gate=unlock.getAsJsonObject("abilities").getAsJsonObject("USE_SHIELD").deepCopy();c.gate.addProperty("scoreAfter",unlock.get("scoreAfter").getAsInt());}
  c.beforeDamage=p.getMainHandItem().getDamageValue();boolean use=c.key.equals("blocked_skeleton")||c.key.equals("other_owner")||c.key.equals("locked_shield");if(use)new ServerboundUseItemPacket(InteractionHand.MAIN_HAND,1,0,0).handle(p.connection);c.useTick=h.getLevel().getGameTime();require(p.isUsingItem()==(use&&!c.key.equals("locked_shield")),"Native shield activation/gate mismatch");c.mob=(Mob)BuiltInRegistries.ENTITY_TYPE.getValue(Identifier.parse(c.key.equals("other_owner")?"pillager":"skeleton")).create(h.getLevel(),EntitySpawnReason.COMMAND);require(c.mob!=null,"Mob fixture failed");c.mob.setPersistenceRequired();c.mob.setItemSlot(EquipmentSlot.MAINHAND,new ItemStack(c.key.equals("melee_skeleton")?Items.WOODEN_SWORD:c.key.equals("other_owner")?Items.CROSSBOW:Items.BOW));c.mob.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.LEATHER_HELMET));c.mob.teleportTo(c.pos.getX()+.5,c.pos.getY(),c.pos.getZ()+(c.key.equals("melee_skeleton")?2:7.5));require(h.getLevel().addFreshEntity(c.mob)&&!c.mob.isNoAi(),"Real AI entity missing");Final19ShieldProbe.arm(p);h.runAfterDelay(10,()->start(h,cases,i,run,exact,c));
 }catch(Throwable e){fail(h,c,e);}}
 static void start(GameTestHelper h,List<String>cases,int i,String run,boolean exact,Context c){try{c.mob.setTarget(c.actor.player());poll(h,cases,i,run,exact,c,0);}catch(Throwable e){fail(h,c,e);}}
 static void poll(GameTestHelper h,List<String>cases,int i,String run,boolean exact,Context c,int ticks){try{var p=c.actor.player();float yaw=(float)Math.toDegrees(Math.atan2(-(c.mob.getX()-p.getX()),c.mob.getZ()-p.getZ()));new ServerboundMovePlayerPacket.Rot(yaw,0,true,false).handle(p.connection);var witness=Final19ShieldProbe.peek(p);if(witness!=null){boolean blocked=c.key.equals("blocked_skeleton")||c.key.equals("other_owner");require(witness.get("blocked").getAsBoolean()==blocked,"Native shield failed to block expected hit: "+witness);require(done(c)==c.key.equals("blocked_skeleton"),"Native shield criterion violated frozen predicate");JsonObject r=new JsonObject();r.addProperty("case",c.key);r.addProperty("runId",run);r.addProperty("advancementId",c.adv.id().toString());r.addProperty("criterion","deflected_skeleton");r.addProperty("requirementGroup",0);r.addProperty("playerUuid",p.getUUID().toString());r.addProperty("targetUuid",c.mob.getUUID().toString());r.addProperty("gameMode",p.gameMode().name());r.addProperty("joined",h.getLevel().getServer().getPlayerList().getPlayer(p.getUUID())==p);r.addProperty("connectionRegistered",h.getLevel().getServer().getConnection().getConnections().contains(c.actor.connection()));r.addProperty("clientLoaded",p.connection.hasClientLoaded());r.addProperty("finiteMaterials",!p.hasInfiniteMaterials());r.addProperty("criterionBefore",false);r.addProperty("criterionAfter",done(c));r.addProperty("advancementDone",p.getAdvancements().getOrStartProgress(c.adv).isDone());r.addProperty("nativeAction",witness.get("nativeHurtObserved").getAsBoolean());r.addProperty("noDirectTrigger",true);r.addProperty("noManualAward",true);r.addProperty("shieldDamageBefore",c.beforeDamage);r.addProperty("shieldDamageAfter",p.getMainHandItem().getDamageValue());r.addProperty("blockingTicks",h.getLevel().getGameTime()-c.useTick);r.addProperty("shieldActiveAtReceipt",p.isUsingItem());r.addProperty("healthAfter",p.getHealth());r.add("damageWitness",witness.deepCopy());c.gate.addProperty("lockedAfter",AchieveToDoMod.isAbilityLocked(p,AbilityType.USE_SHIELD,true));r.add("shieldGate",c.gate);r.add("cleanup",cleanup(h,c));Final19CombatEvidence.append("shield",r);h.runAfterDelay(2,()->next(h,cases,i+1,run,exact));return;}require(ticks<700,"Native AI hit timed out: mob="+c.mob.position()+" player="+p.position()+" target="+c.mob.getTarget()+" shield="+p.isUsingItem());require(p.isAlive(),"Owned player died");h.runAfterDelay(1,()->poll(h,cases,i,run,exact,c,ticks+1));}catch(Throwable e){fail(h,c,e);}}
 static boolean done(Context c){return Final19NativeActors.done(c.actor,c.adv,"deflected_skeleton");}
 static JsonObject cleanup(GameTestHelper h,Context c){if(c.actor!=null){Final19ShieldProbe.close(c.actor.player(),c.mob);c.actor.player().stopUsingItem();}if(c.mob!=null)c.mob.discard();if(c.area!=null)for(var e:h.getLevel().getEntitiesOfClass(Entity.class,c.area))if(!c.baseline.contains(e.getUUID())&&e!=c.actor.player()&&(e instanceof Projectile||e==c.mob))e.discard();boolean restored=true;for(var e:c.blocks.entrySet()){h.getLevel().setBlockAndUpdate(e.getKey(),e.getValue());restored&=h.getLevel().getBlockState(e.getKey()).equals(e.getValue());}c.blocks.clear();var clean=c.actor==null?new JsonObject():Final19NativeActors.close(c.actor);clean.addProperty("fixtureEntitiesRemoved",c.mob==null||!c.mob.isAlive());clean.addProperty("blocksRestored",restored);return clean;}
 static void fail(GameTestHelper h,Context c,Throwable e){try{cleanup(h,c);}catch(Throwable t){e.addSuppressed(t);}h.fail("FINAL19 shield "+c.key+": "+e);}
 static class Context{final String key;Context(String k){key=k;}BlockPos pos;AABB area;Set<UUID>baseline=new HashSet<>();Final19NativeActors.Actor actor;AdvancementHolder adv;Mob mob;JsonObject gate=new JsonObject();int beforeDamage;long useTick;Map<BlockPos,BlockState>blocks=new LinkedHashMap<>();}
 @Override public void invokeTestMethod(GameTestHelper h,Method m)throws ReflectiveOperationException{h.setBlock(0,0,0,Blocks.AIR);m.invoke(this,h);}
}
