package com.diskree.achievetodo.certification;
import com.diskree.achievetodo.ability.AbilityType;
import com.google.gson.*;
import net.fabricmc.fabric.api.gametest.v1.*;
import net.minecraft.advancements.AdvancementHolder;
import net.minecraft.core.*;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.*;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.network.protocol.game.*;
import net.minecraft.resources.*;
import net.minecraft.server.commands.FillBiomeCommand;
import net.minecraft.tags.TagKey;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.entity.*;
import net.minecraft.world.item.*;
import net.minecraft.world.item.enchantment.ItemEnchantments;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.levelgen.structure.Structure;
import net.minecraft.world.phys.Vec3;
import java.lang.reflect.Method;
import java.util.*;
import static com.diskree.achievetodo.certification.Final19StaticContext.require;
/** Registered world fixtures and normal packets/ticks, without lookup replacement. */
public final class Final19MixedWorldgenGameTest implements CustomTestMethodInvoker {
    static final String FAMILY="MIXED_WORLDGEN_PREDICATE_CONTEXT";
    @GameTest(maxTicks=1600) public void mixedWorldgenCanary2(GameTestHelper h){run(h,false);}
    @GameTest(maxTicks=1600) public void mixedWorldgenExact2(GameTestHelper h){run(h,true);}
    static void run(GameTestHelper h,boolean exact){try{System.out.println("FINAL19_NATIVE_RUN_START family="+FAMILY);String run=Final19FamilyEvidence.begin(Final19WorldgenEvidence.root(),FAMILY,exact);next(h,Final19FamilyEvidence.rows(Final19WorldgenEvidence.root(),FAMILY,exact),0,run,exact);}catch(Throwable e){h.fail("Mixed begin: "+e);}}
    static void next(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact){
        if(i==rows.size()){try{Final19FamilyEvidence.complete(Final19WorldgenEvidence.root(),FAMILY,exact);System.out.println((exact?"TEMP_PROMOTABLE":"TEMP_DIAGNOSTIC")+"=PASS family="+FAMILY+" runId="+run+" entries="+rows.size());h.succeed();}catch(Throwable e){h.fail("Mixed completion: "+e);}return;}
        Context c=new Context(rows.get(i));try{c.pos=h.absolutePos(new BlockPos(4,2,4));c.actor=Final19NativeActors.join(h.getLevel(),c.pos);c.advancement=Final19NativeActors.advancement(c.actor,c.row);require(!done(c),"Precompleted target");if(c.row.get("criterion").getAsString().equals("boatception"))h.runAfterDelay(1,()->boat(h,rows,i,run,exact,c));else setupFrost(h,rows,i,run,exact,c);}catch(Throwable e){fail(h,c,e);}
    }
    static void boat(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c){try{
        var player=c.actor.player();var gate=Final19NativeActors.unlock(c.actor,AbilityType.GET_INTO_BOAT);var type=BuiltInRegistries.ENTITY_TYPE.getValue(Identifier.parse("minecraft:spruce_boat"));c.boat=type.create(h.getLevel(),EntitySpawnReason.COMMAND);require(c.boat!=null,"Boat construction failed");c.boat.setPos(Vec3.atBottomCenterOf(c.pos));require(h.getLevel().addFreshEntity(c.boat),"Boat spawn failed");
        var structure=h.getLevel().registryAccess().lookupOrThrow(Registries.STRUCTURE).getOrThrow(ResourceKey.create(Registries.STRUCTURE,Identifier.parse("minecraft:shipwreck")));require(!h.getLevel().structureManager().getStructureWithPieceAt(c.pos,structure.value()).isValid(),"Wrong-context control already inside shipwreck");
        new ServerboundInteractPacket(c.boat.getId(),InteractionHand.MAIN_HAND,c.boat.position(),false).handle(player.connection);require(player.getVehicle()==c.boat&&!done(c),"Wrong-context native boat mount negative failed");player.stopRiding();c.structure=SyntheticStructureHarness.inject(h.getLevel(),structure,c.pos);
        var visible=h.getLevel().structureManager().getStructureWithPieceAt(c.boat.blockPosition(),structure.value());require(visible==c.structure.injectedStart()&&visible.isValid()&&c.structure.pieceBox().isInside(c.boat.blockPosition()),"Real vehicle StructureManager lookup failed");boolean member=c.boat.getType().builtInRegistryHolder().is(TagKey.create(Registries.ENTITY_TYPE,Identifier.parse("blazeandcave:all_boats")));require(member,"Boat tag missing");boolean before=done(c);new ServerboundInteractPacket(c.boat.getId(),InteractionHand.MAIN_HAND,c.boat.position(),false).handle(player.connection);require(player.getVehicle()==c.boat&&done(c),"Native boat mount did not award criterion");
        var r=Final19NativeActors.receipt(c.actor,c.advancement,c.row,run,before);r.addProperty("nativeBoundary","ServerboundInteractPacket.handle -> Boat.interact -> startRiding");r.addProperty("wrongContextNegative",true);r.addProperty("nativeEvent",true);r.addProperty("boatTagMember",member);r.addProperty("vehicleStructurePresent",visible==c.structure.injectedStart());r.addProperty("nativeMount",player.getVehicle()==c.boat);r.addProperty("observedStructure",structure.unwrapKey().orElseThrow().identifier().toString());r.addProperty("observedVehicle",BuiltInRegistries.ENTITY_TYPE.getKey(c.boat.getType()).toString());r.addProperty("structureFixtureSource","OWNED_REGISTERED_STRUCTURE_START_PIECE_AND_REFERENCE");r.add("productionGateWitness",gate);finish(h,rows,i,run,exact,c,r);
    }catch(Throwable e){fail(h,c,e);}}
    static void setupFrost(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c)throws Exception{
        for(int x=-5;x<=5;x++)for(int z=-5;z<=5;z++)for(int y=-2;y<=2;y++){var p=c.pos.offset(x,y,z);c.blocks.put(p,h.getLevel().getBlockState(p));h.getLevel().setBlockAndUpdate(p,y==-2?Blocks.STONE.defaultBlockState():y==-1?Blocks.WATER.defaultBlockState():Blocks.AIR.defaultBlockState());}h.getLevel().setBlockAndUpdate(c.pos.below(),Blocks.STONE.defaultBlockState());
        for(int x=(c.pos.getX()-8)&~3;x<=((c.pos.getX()+8)&~3);x+=4)for(int z=(c.pos.getZ()-8)&~3;z<=((c.pos.getZ()+8)&~3);z+=4)for(int y=(c.pos.getY()-4)&~3;y<=((c.pos.getY()+4)&~3);y+=4){var p=new BlockPos(x,y,z);c.biomes.put(p,h.getLevel().getBiome(p));}
        fill(h,c,"minecraft:the_void");c.step=c.pos.offset(1,-1,0);c.boots=new ItemStack(Items.LEATHER_BOOTS);var enchant=h.getLevel().registryAccess().lookupOrThrow(Registries.ENCHANTMENT).getOrThrow(ResourceKey.create(Registries.ENCHANTMENT,Identifier.parse("minecraft:frost_walker")));require(enchant.value().canEnchant(c.boots)&&enchant.value().getMaxLevel()>=2,"Illegal Frost Walker boots");c.boots.enchant(enchant,2);
        c.actor.player().setItemSlot(EquipmentSlot.FEET,c.boots.copy());move(c,c.pos,.55);h.runAfterDelay(5,()->wrongBiome(h,rows,i,run,exact,c));
    }
    static void wrongBiome(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c){try{require(h.getLevel().getBlockState(c.step).is(Blocks.FROSTED_ICE),"Native enchantment did not freeze water in wrong-biome control");move(c,c.step.above(),.5);h.runAfterDelay(25,()->{try{require(!done(c),"Wrong biome completed target");c.observations.add("wrongBiome",negative(h,c));c.wrongBiome=true;c.actor.player().setItemSlot(EquipmentSlot.FEET,ItemStack.EMPTY);fill(h,c,"minecraft:deep_lukewarm_ocean");h.runAfterDelay(25,()->wrongBoots(h,rows,i,run,exact,c));}catch(Throwable e){fail(h,c,e);}});}catch(Throwable e){fail(h,c,e);}}
    static void wrongBoots(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c){try{require(!done(c)&&c.actor.player().getItemBySlot(EquipmentSlot.FEET).isEmpty(),"Wrong boots completed target");c.observations.add("wrongBoots",negative(h,c));c.wrongBoots=true;h.getLevel().setBlockAndUpdate(c.step,Blocks.ICE.defaultBlockState());c.actor.player().setItemSlot(EquipmentSlot.FEET,c.boots.copy());h.runAfterDelay(25,()->wrongIce(h,rows,i,run,exact,c));}catch(Throwable e){fail(h,c,e);}}
    static void wrongIce(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c){try{require(!done(c)&&h.getLevel().getBlockState(c.step).is(Blocks.ICE),"Ordinary ice completed target");c.observations.add("wrongIce",negative(h,c));c.wrongIce=true;c.actor.player().setGameMode(GameType.SPECTATOR);h.getLevel().setBlockAndUpdate(c.step,Blocks.FROSTED_ICE.defaultBlockState());h.runAfterDelay(25,()->spectator(h,rows,i,run,exact,c));}catch(Throwable e){fail(h,c,e);}}
    static void spectator(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c){try{require(!done(c)&&c.actor.player().isSpectator(),"Spectator completed target");c.observations.add("spectator",negative(h,c));c.spectator=true;c.actor.player().setGameMode(GameType.SURVIVAL);teleport(c,c.pos);for(int x=-4;x<=4;x++)for(int z=-4;z<=4;z++)h.getLevel().setBlockAndUpdate(c.pos.offset(x,-1,z),x==0&&z==0?Blocks.STONE.defaultBlockState():Blocks.WATER.defaultBlockState());require(h.getLevel().getBlockState(c.step).is(Blocks.WATER),"Positive native prewater missing");c.waterBefore=h.getLevel().getBlockState(c.step).toString();move(c,c.pos,.55);h.runAfterDelay(5,()->positiveFreeze(h,rows,i,run,exact,c));}catch(Throwable e){fail(h,c,e);}}
    static void positiveFreeze(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c){try{require(h.getLevel().getBlockState(c.step).is(Blocks.FROSTED_ICE),"Positive native water-to-frosted-ice mutation missing");c.iceAfter=h.getLevel().getBlockState(c.step).toString();require(!done(c),"Positive criterion completed before stepping event");move(c,c.step.above(),.5);h.runAfterDelay(25,()->positiveLocation(h,rows,i,run,exact,c));}catch(Throwable e){fail(h,c,e);}}
    static void positiveLocation(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c){try{var player=c.actor.player();String biome=h.getLevel().getBiome(player.blockPosition()).unwrapKey().orElseThrow().identifier().toString();var feet=player.getItemBySlot(EquipmentSlot.FEET);var enchants=feet.getOrDefault(DataComponents.ENCHANTMENTS,ItemEnchantments.EMPTY);int frost=0;for(var holder:enchants.keySet())if(holder.unwrapKey().orElseThrow().identifier().toString().equals("minecraft:frost_walker"))frost=enchants.getLevel(holder);require(done(c)&&frost==2&&player.onGround()&&h.getLevel().getBlockState(player.getOnPos()).is(Blocks.FROSTED_ICE)&&biome.equals("minecraft:deep_lukewarm_ocean"),"Native periodic Frost Walker location proof failed");var r=Final19NativeActors.receipt(c.actor,c.advancement,c.row,run,false);r.addProperty("nativeBoundary","ServerboundMovePlayerPacket.handle -> native enchantment location effect -> periodic location trigger");r.addProperty("nativeEvent",true);r.addProperty("wrongContextNegative",c.wrongBiome);r.addProperty("observedBiome",biome);r.addProperty("observedSteppingBlock",BuiltInRegistries.BLOCK.getKey(h.getLevel().getBlockState(player.getOnPos()).getBlock()).toString());r.addProperty("legalFrostWalkerBoots",feet.is(Items.LEATHER_BOOTS)&&frost==2);r.addProperty("observedBoots","minecraft:leather_boots");r.addProperty("observedFrostWalkerLevel",frost);r.addProperty("nativeWaterToFrostedIce",true);r.addProperty("waterBefore",c.waterBefore);r.addProperty("iceAfter",c.iceAfter);r.add("negativeObservations",c.observations);r.addProperty("wrongBootsNegative",c.wrongBoots);r.addProperty("wrongIceNegative",c.wrongIce);r.addProperty("spectatorNegative",c.spectator);finish(h,rows,i,run,exact,c,r);}catch(Throwable e){fail(h,c,e);}}
    static JsonObject negative(GameTestHelper h,Context c){var p=c.actor.player();var n=new JsonObject();n.addProperty("criterion",done(c));n.addProperty("gameMode",p.gameMode().name());n.addProperty("biome",h.getLevel().getBiome(p.blockPosition()).unwrapKey().orElseThrow().identifier().toString());n.addProperty("steppingBlock",BuiltInRegistries.BLOCK.getKey(h.getLevel().getBlockState(p.getOnPos()).getBlock()).toString());n.addProperty("bootsEmpty",p.getItemBySlot(EquipmentSlot.FEET).isEmpty());n.addProperty("observedTicks",25);return n;}
    static void move(Context c,BlockPos pos,double xOffset){var p=c.actor.player();new ServerboundMovePlayerPacket.Pos(pos.getX()+xOffset,pos.getY(),pos.getZ()+.5,true,false).handle(p.connection);}
    static void teleport(Context c,BlockPos pos){var p=c.actor.player();require(p.teleportTo(p.level(),pos.getX()+.5,pos.getY(),pos.getZ()+.5,Set.of(),0,0,true),"Owned teleport failed");Final19NativeActors.acknowledge(c.actor);}
    static void fill(GameTestHelper h,Context c,String id){var biome=h.getLevel().registryAccess().lookupOrThrow(Registries.BIOME).getOrThrow(ResourceKey.create(Registries.BIOME,Identifier.parse(id)));require(FillBiomeCommand.fill(h.getLevel(),c.pos.offset(-8,-4,-8),c.pos.offset(8,4,8),biome).right().isEmpty(),"Biome fixture failed");}
    static boolean done(Context c){return Final19NativeActors.done(c.actor,c.advancement,c.row.get("criterion").getAsString());}
    static void finish(GameTestHelper h,List<JsonObject> rows,int i,String run,boolean exact,Context c,JsonObject r)throws Exception{r.add("cleanup",cleanup(h,c));Final19FamilyEvidence.append(Final19WorldgenEvidence.root(),FAMILY,r);h.runAfterDelay(1,()->next(h,rows,i+1,run,exact));}
    static JsonObject cleanup(GameTestHelper h,Context c){boolean structures=true;if(c.actor!=null)c.actor.player().stopRiding();if(c.boat!=null)c.boat.discard();if(c.structure!=null){var original=c.structure;c.structure.close();structures=original.chunk().getAllStarts().equals(original.originalStarts())&&original.chunk().getAllReferences().equals(original.originalReferences());c.structure=null;}boolean biomes=true;for(var e:c.biomes.entrySet()){require(FillBiomeCommand.fill(h.getLevel(),e.getKey(),e.getKey(),e.getValue()).right().isEmpty(),"Biome restoration failed");biomes&=h.getLevel().getBiome(e.getKey()).equals(e.getValue());}c.biomes.clear();boolean blocks=true;for(var e:c.blocks.entrySet()){h.getLevel().setBlockAndUpdate(e.getKey(),e.getValue());blocks&=h.getLevel().getBlockState(e.getKey()).equals(e.getValue());}c.blocks.clear();var clean=c.actor==null?new JsonObject():Final19NativeActors.close(c.actor);clean.addProperty("fixtureEntitiesRemoved",c.boat==null||c.boat.isRemoved());clean.addProperty("structureRestored",structures);clean.addProperty("biomeRestored",biomes);clean.addProperty("blocksRestored",blocks);return clean;}
    static void fail(GameTestHelper h,Context c,Throwable e){try{cleanup(h,c);}catch(Throwable other){e.addSuppressed(other);}h.fail("Mixed worldgen "+c.row.get("criterion")+": "+e);}
    static class Context{JsonObject row;JsonObject observations=new JsonObject();BlockPos pos,step;Final19NativeActors.Actor actor;AdvancementHolder advancement;Entity boat;SyntheticStructureHarness.InjectedStructure structure;ItemStack boots;Map<BlockPos,BlockState> blocks=new LinkedHashMap<>();Map<BlockPos,Holder<Biome>> biomes=new LinkedHashMap<>();boolean wrongBiome,wrongBoots,wrongIce,spectator;String waterBefore,iceAfter;Context(JsonObject row){this.row=row;}}
    @Override public void invokeTestMethod(GameTestHelper h,Method method)throws ReflectiveOperationException{h.setBlock(0,0,0,Blocks.AIR);method.invoke(this,h);}
}
