package com.diskree.achievetodo.certification;
import com.diskree.achievetodo.AchieveToDoMod;
import com.diskree.achievetodo.ability.AbilityType;
import com.google.gson.*;
import com.mojang.serialization.JsonOps;
import net.fabricmc.fabric.api.gametest.v1.*;
import net.minecraft.advancements.*;
import net.minecraft.advancements.predicates.entity.RaiderPredicate;
import net.minecraft.core.*;
import net.minecraft.core.registries.*;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.network.protocol.game.ServerboundAttackPacket;
import net.minecraft.resources.Identifier;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.raid.*;
import net.minecraft.world.entity.npc.villager.Villager;
import net.minecraft.world.entity.ai.memory.MemoryModuleType;
import net.minecraft.world.entity.ai.village.poi.PoiTypes;
import net.minecraft.world.level.block.state.properties.BedPart;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.gamerules.GameRules;
import java.lang.reflect.Method;
import java.util.*;
import static com.diskree.achievetodo.certification.Final19StaticContext.require;
/** Owned role/raid fixtures, observed native codec state and ordinary packet kills. No trigger calls. */
public final class Final19RaiderGameTest implements CustomTestMethodInvoker {
 @GameTest(maxTicks=4000) public void raiderIntegrity16(GameTestHelper h){run(h,"raider_integrity",true);}
 @GameTest(maxTicks=1200) public void raiderCanary2(GameTestHelper h){run(h,"raider",false);}
 @GameTest(maxTicks=2400) public void raiderExact5(GameTestHelper h){run(h,"raider",true);}
 static void run(GameTestHelper h,String prefix,boolean exact){try{System.out.println("FINAL19_DIAGNOSTIC_WARMUP_START");var warm=Final19NativeActors.join(h.getLevel(),h.absolutePos(new BlockPos(3,1,3)));Final19NativeActors.unlock(warm,AbilityType.USE_WOODEN_TOOLS);var clean=Final19NativeActors.close(warm);for(String k:List.of("playerRemoved","connectionRemoved","channelSettled"))require(clean.get(k).getAsBoolean(),"Warmup cleanup failed");System.out.println("FINAL19_DIAGNOSTIC_WARMUP_COMPLETE cleanup="+clean);h.runAfterDelay(40,()->begin(h,prefix,exact));}catch(Throwable e){h.fail("FINAL19 warmup: "+e);}}
 static void begin(GameTestHelper h,String prefix,boolean exact){try{System.out.println("FINAL19_NATIVE_RUN_START family="+prefix);String run=Final19CombatEvidence.begin(prefix,exact);next(h,prefix,exact,new ArrayList<>(new TreeSet<>(Final19CombatEvidence.cases(prefix,exact))),0,run);}catch(Throwable e){h.fail("FINAL19 raider begin: "+e);}}
 static void next(GameTestHelper h,String prefix,boolean exact,List<String>cases,int index,String run){if(index==cases.size()){try{Final19CombatEvidence.complete(prefix,exact);System.out.println((exact?"TEMP_PROMOTABLE":"TEMP_DIAGNOSTIC")+"=PASS family="+prefix+" runId="+run+" entries="+cases.size());h.succeed();}catch(Throwable e){h.fail("FINAL19 raider audit: "+e);}return;}Context c=new Context(prefix,cases.get(index));try{
  c.pos=h.absolutePos(new BlockPos(3,1,3));for(int x=-1;x<=3;x++)for(int z=-1;z<=1;z++){var p=c.pos.offset(x,-1,z);c.blocks.put(p,h.getLevel().getBlockState(p));h.getLevel().setBlockAndUpdate(p,Blocks.STONE.defaultBlockState());}
  c.actor=Final19NativeActors.join(h.getLevel(),c.pos);c.gate=Final19NativeActors.unlock(c.actor,AbilityType.USE_WOODEN_TOOLS);c.actor.player().getInventory().setItem(c.actor.player().getInventory().getSelectedSlot(),new ItemStack(Items.WOODEN_SWORD));
  String type=c.key.contains("/")?c.key.split("/")[1]:c.key.equals("outsider")?"zombie":"pillager";String advancement=c.prefix.equals("raider")?"minecraft:adventure/voluntary_exile":"blazeandcave:"+(c.key.startsWith("feeling_ill")?"adventure/feeling_ill":"monsters/dungeon_crawler");c.criterion=c.prefix.equals("raider")?"bad_omen":type;c.adv=h.getLevel().getServer().getAdvancements().get(Identifier.parse(advancement));require(c.adv!=null&&!done(c),"Missing/precompleted target");var definition=Final19CombatEvidence.definition(advancement);var fields=definition.getAsJsonObject("criteria").getAsJsonObject(c.criterion).getAsJsonObject("conditions").getAsJsonArray("entity").get(0).getAsJsonObject().getAsJsonObject("predicate").getAsJsonObject("type_specific/raider");c.decoded=RaiderPredicate.CODEC.parse(JsonOps.INSTANCE,fields).result().orElseThrow();
  c.mob=(Mob)BuiltInRegistries.ENTITY_TYPE.getValue(Identifier.parse(type)).create(h.getLevel(),EntitySpawnReason.COMMAND);require(c.mob!=null,"Spawn failed");c.mob.setNoAi(true);c.mob.setPersistenceRequired();c.mob.setNoGravity(true);c.mob.teleportTo(c.pos.getX()+1.5,c.pos.getY(),c.pos.getZ()+.5);c.mob.setHealth(1);
  if(c.mob instanceof Raider raider){boolean leader=c.key.equals("captain")||c.key.equals("raid_captain"),banner=leader||c.key.equals("banner_only");raider.setPatrolLeader(leader);if(banner)raider.setItemSlot(EquipmentSlot.HEAD,Raid.getOminousBannerInstance(h.getLevel().registryAccess().lookupOrThrow(Registries.BANNER_PATTERN)));if(c.key.endsWith("/raid")||c.key.equals("raid_captain")){c.raidsRule=h.getLevel().getGameRules().get(GameRules.RAIDS);h.getLevel().getGameRules().set(GameRules.RAIDS,true,h.getLevel().getServer());c.head=c.pos.offset(3,0,1);var foot=c.head.south();for(var bp:List.of(foot,c.head)){c.blocks.put(bp,h.getLevel().getBlockState(bp));h.getLevel().setBlockAndUpdate(bp,BuiltInRegistries.BLOCK.getValue(Identifier.parse("red_bed")).defaultBlockState().setValue(BedBlock.FACING,Direction.NORTH).setValue(BedBlock.PART,bp.equals(c.head)?BedPart.HEAD:BedPart.FOOT));}c.villager=(Villager)BuiltInRegistries.ENTITY_TYPE.getValue(Identifier.parse("villager")).create(h.getLevel(),EntitySpawnReason.COMMAND);require(c.villager!=null,"Villager fixture missing");c.villager.setNoAi(true);c.villager.setNoGravity(true);c.villager.teleportTo(c.pos.getX()+3.5,c.pos.getY(),c.pos.getZ()+2.5);c.villager.getBrain().setMemory(MemoryModuleType.HOME,GlobalPos.of(h.getLevel().dimension(),c.head));require(h.getLevel().addFreshEntity(c.villager),"Village fixture spawn failed");}}
  require(h.getLevel().addFreshEntity(c.mob)&&!AchieveToDoMod.isTargetInLockedLandmark(c.actor.player(),c.mob),"Entity/landmark fixture failed");h.runAfterDelay(1,()->kill(h,prefix,exact,cases,index,run,c,0));
 }catch(Throwable e){fail(h,c,e);}}
 static void kill(GameTestHelper h,String prefix,boolean exact,List<String>cases,int i,String run,Context c,int ticks){try{if(c.actor.player().getAttackStrengthScale(.5F)<.95F){require(ticks<45,"Attack cooldown failed");h.runAfterDelay(1,()->kill(h,prefix,exact,cases,i,run,c,ticks+1));return;}require(!done(c)&&c.mob.isAlive(),"Pre-kill state drift");if(c.head!=null){var poi=h.getLevel().getPoiManager();require(poi.take(t->t.is(PoiTypes.HOME),(t,p)->p.equals(c.head),c.head,1).isPresent(),"HOME claim failed");c.claimed=true;require(h.getLevel().isVillage(c.pos),"Native village missing");c.raid=h.getLevel().getRaids().createOrExtendRaid(c.actor.player(),c.pos);require(c.raid!=null&&c.raid.isActive()&&h.getLevel().getRaids().getId(c.raid).isPresent(),"Live native raid missing");c.raid.joinRaid(h.getLevel(),1,(Raider)c.mob,null,true);}var w=new JsonObject();boolean has=c.mob instanceof Raider r&&r.hasRaid(),captain=c.mob instanceof Raider r&&r.isCaptain(),leader=c.mob instanceof Raider r&&r.isPatrolLeader();w.addProperty("hasRaid",has);w.addProperty("isCaptain",captain);w.addProperty("patrolLeader",leader);w.addProperty("activeRaid",c.mob instanceof Raider r&&r.hasActiveRaid());w.addProperty("exactOminousBanner",ItemStack.matches(c.mob.getItemBySlot(EquipmentSlot.HEAD),Raid.getOminousBannerInstance(h.getLevel().registryAccess().lookupOrThrow(Registries.BANNER_PATTERN))));w.addProperty("registeredLiveRaid",c.raid!=null&&c.raid.isActive()&&h.getLevel().getRaids().getId(c.raid).isPresent());w.addProperty("raiderTagMember",c.mob.getType().builtInRegistryHolder().is(TagKey.create(Registries.ENTITY_TYPE,Identifier.parse("minecraft:raiders"))));w.addProperty("decodedMatchesLiveBeforeKill",c.decoded.matches(c.mob,h.getLevel(),c.actor.player().position()));w.addProperty("raidStoppedBeforeKill",c.raid!=null&&c.raid.isStopped());w.addProperty("raidCurrentBeforeKill",c.mob instanceof Raider rr&&rr.getCurrentRaid()==c.raid);w.addProperty("entityType",BuiltInRegistries.ENTITY_TYPE.getKey(c.mob.getType()).toString());
  new ServerboundAttackPacket(c.mob.getId()).handle(c.actor.player().connection);require(!c.mob.isAlive()&&c.mob.getLastDamageSource()!=null&&c.mob.getLastDamageSource().getEntity()==c.actor.player()&&c.mob.getKillCredit()==c.actor.player(),"Native attributed kill missing");w.addProperty("nativeKillCredit",c.mob.getKillCredit()==c.actor.player());w.addProperty("damageType",c.mob.getLastDamageSource().typeHolder().unwrapKey().orElseThrow().identifier().toString());w.addProperty("hasRaidAfterKill",c.mob instanceof Raider rr&&rr.hasRaid());w.addProperty("criterionImmediatelyAfterKill",done(c));System.out.println("FINAL19_RAIDER_DIAGNOSTIC case="+c.key+" witness="+w);c.witness=w;c.mob.discard();if(c.raid!=null){c.raid.removeFromRaid(h.getLevel(),(Raider)c.mob,true);c.raid.stop();}h.runAfterDelay(2,()->finish(h,prefix,exact,cases,i,run,c));
 }catch(Throwable e){fail(h,c,e);}}
 static void finish(GameTestHelper h,String prefix,boolean exact,List<String>cases,int i,String run,Context c){try{boolean positive=c.prefix.equals("raider")?c.key.equals("captain"):c.key.startsWith("feeling_ill")?c.key.endsWith("/raid"):c.key.endsWith("/nonraid");require(done(c)==positive,"Native criterion violated frozen semantics: "+c.key+" expected="+positive+" actual="+done(c));var p=c.actor.player();JsonObject r=new JsonObject();r.addProperty("case",c.key);r.addProperty("runId",run);r.addProperty("advancementId",c.adv.id().toString());r.addProperty("criterion",c.criterion);r.addProperty("requirementGroup",0);r.addProperty("playerUuid",p.getUUID().toString());r.addProperty("targetUuid",c.mob.getUUID().toString());r.addProperty("gameMode",p.gameMode().name());r.addProperty("joined",h.getLevel().getServer().getPlayerList().getPlayer(p.getUUID())==p);r.addProperty("connectionRegistered",h.getLevel().getServer().getConnection().getConnections().contains(c.actor.connection()));r.addProperty("clientLoaded",p.connection.hasClientLoaded());r.addProperty("finiteMaterials",!p.hasInfiniteMaterials());r.addProperty("criterionBefore",false);r.addProperty("criterionAfter",done(c));r.addProperty("advancementDone",p.getAdvancements().getOrStartProgress(c.adv).isDone());r.addProperty("nativeAction",!c.mob.isAlive()&&c.mob.getKillCredit()==p);r.addProperty("noDirectTrigger",true);r.addProperty("noManualAward",true);r.add("productionGate",c.gate);r.add("raiderWitness",c.witness);var decoded=new JsonObject();decoded.addProperty("hasRaid",c.decoded.hasRaid());decoded.addProperty("isCaptain",c.decoded.isCaptain());r.add("decodedPredicate",decoded);r.add("cleanup",cleanup(h,c));Final19CombatEvidence.append(prefix,r);h.runAfterDelay(1,()->next(h,prefix,exact,cases,i+1,run));}catch(Throwable e){fail(h,c,e);}}
 static boolean done(Context c){return Final19NativeActors.done(c.actor,c.adv,c.criterion);}
 static JsonObject cleanup(GameTestHelper h,Context c){if(c.mob!=null)c.mob.discard();if(c.villager!=null)c.villager.discard();if(c.claimed){h.getLevel().getPoiManager().release(c.head);c.claimed=false;}if(c.raid!=null){c.raid.stop();h.getLevel().getGameRules().set(GameRules.RAIDS,c.raidsRule,h.getLevel().getServer());}boolean restored=true;for(var e:c.blocks.entrySet()){h.getLevel().setBlockAndUpdate(e.getKey(),e.getValue());restored&=h.getLevel().getBlockState(e.getKey()).equals(e.getValue());}c.blocks.clear();var clean=c.actor==null?new JsonObject():Final19NativeActors.close(c.actor);clean.addProperty("fixtureEntitiesRemoved",c.mob==null||!c.mob.isAlive());clean.addProperty("blocksRestored",restored);clean.addProperty("raidStoppedAndUnregistered",c.raid==null||c.raid.isStopped()&&h.getLevel().getRaids().getId(c.raid).isEmpty());return clean;}
 static void fail(GameTestHelper h,Context c,Throwable e){try{cleanup(h,c);}catch(Throwable t){e.addSuppressed(t);}h.fail("FINAL19 raider "+c.key+": "+e);}
 static class Context{final String prefix,key;Context(String p,String k){prefix=p;key=k;}BlockPos pos,head;Villager villager;boolean claimed;Final19NativeActors.Actor actor;AdvancementHolder adv;String criterion;Mob mob;Raid raid;RaiderPredicate decoded;boolean raidsRule;JsonObject gate,witness;Map<BlockPos,BlockState>blocks=new LinkedHashMap<>();}
 @Override public void invokeTestMethod(GameTestHelper h,Method m)throws ReflectiveOperationException{h.setBlock(0,0,0,Blocks.AIR);m.invoke(this,h);}
}
